### ISSUE TITLE
Hot replicas with Stolon

### ISSUE THREAD

**Issue by kafkapre** [sorintlab/stolon#134]
Hi everybody, Stolon seem as a nice tool for Postgres failover on Kubernetes cluster. But when I was reading about it, I have not found that it is possible to do hot failover. I mean Master (read-write) and Standbys (read only). Is it possible to do this with Stolon? If it is not, will you improve Stolon in this way? Thank you.

**Comment by sgotti** [comment]
@kafkapre Probably this should be cleanly documented. Stolon does ha using streaming replication and by default all the stolon standbys are hot standbys. Currently, to access them, you have to discover or know the standbys addresses/ports (for "static" environments) or in future you can use the stolon proxy (to make it easy to connect to standbys under dynamic environments like kubernetes) (see #132).

Or do you mean something different?

**Comment by sgotti** [comment]
@kafkapre Did my previous comment answered your question?

**Comment by kafkapre** [comment]
Sorry for late response. Yes, I intended something like that. I like that stolon proxies would have "mapped" all postgres instances (master + slaves) and they woluld manage and loadbalance read requests among them. But it seem that this functionality is not implemented yet. When do you intend to imlement it? Thanks.

**Comment by sashgorokhov** [comment]
@sgotti so that means that in default installation all standbys are in hot standby mode and stolon proxies  proxy read requests to them?

**Comment by kafkapre** [comment]
Yes, exactly as you wrote. Only it does not have to be set up as default, it is enough to switch to it via e.g. environment property.

**Comment by sgotti** [comment]
As of now the main purpose is to provide ha and communication to the current master via the proxy. Future use of the proxy to also balance readonly connections to standbys is covered in #132.
