### ISSUE TITLE
Consul not supported in Kubernetes?

### ISSUE THREAD

**Issue by dts** [sorintlab/stolon#137]
I am having a hard time getting things to work on Kubernetes (on Google Container Engine), and I'll try to post as specific of issues as I can, but there may be a few - let me know if there's a better way to figure all of this out!

I couldn't find a reasonably durable way to launch etcd on Container Engine, so I went with Consul (with discovery through Atlast tokens), but Stolon appears to ignore my configuration.  In my modified stolon-keeper.yaml file:

```
          - name: STKEEPER_CLUSTER_NAME
          # TODO(sgotti) Get cluster name from "stoloncluster" label using a downward volume api instead of duplicating the name here
            value: "kube-stolon"
          - name: STKEEPER_STORE_BACKEND
            value: "consul" # Or consul
          - name: STKEEPER_STORE_ENDPOINTS
            value: "10.127.255.151:8500"
            # Enable debugging
```

I tried the service name (svc-consul), the IP address of the service, and and the above IP and port.  When executing this, the keeper crash-loops, with this output:

```
2016-05-23 17:16:36.587970 [keeper.go:772] I | keeper: id: 54974a8f
2016-05-23 17:16:36.588783 [keeper.go:782] C | keeper: cannot create keeper: error retrieving cluster data: client: etcd cluster is unavailable or misconfigured
```

It probably is a typo (mentioning etcd instead of the STORE_BACKEND), because consul appears to be running normally based on its logs, though I don't know how to test it from a command line or whatever.

**Comment by sgotti** [comment]
@dts sorry for the late reply. Not sure if you already resolved this.


> 2016-05-23 17:16:36.588783 [keeper.go:782] C | keeper: cannot create keeper: error retrieving cluster data: client: etcd cluster is unavailable or misconfigured

That message only comes from the etcd client so, looks like it's trying to use etcd.

I tested this by hand and since the store backend is a mandatory option it's needed or the keeper will exit with an error. So looks like the STKEEPER_STORE_BACKEND is setted to etcd. One possibility that comes to my mind is that the k8s definition wasn't updated on the k8s api server.

**Comment by dts** [comment]
Cool!  I'll check it out the next time I'm trying to deploy something.  I'm currently just using RDS, which is fine, I guess.  I'd love to have a kubernetes deployment folder I can configure, and then `kubectl create -f .`.

**Comment by sgotti** [comment]
@dts closing for now. Feel free to reopen or add additional info if you manage to retest this.
