### ISSUE TITLE
use as base the official postgres image

### ISSUE THREAD

**Issue by rimusz** [sorintlab/stolon#138]
would not make more sense to use the official postgres image as a base image for stolon?

**Comment by sgotti** [comment]
@rimusz Do you mean to use the postgres image in the k8s example right?

That's just an example so we started with what we worked most with (fedora). Being an example is not under CI so at the moment is difficult to test the impact of a change to it without testing it manually. There can be multiple better ways to use stolon under k8s (for example I was thinking on using the new petSets).

Feel free to open a PR to update the example to the official postgres image.

**Comment by rimusz** [comment]
the PR #149 just landed, that should sort this issue out.
So I'm going to close it.
