### ISSUE TITLE
Error image pull / stolon database not found?

### ISSUE THREAD

**Issue by Sharor** [sorintlab/stolon#152]
I've looked at stolon a little on off for a day or two now - sadly only in my spare time - specifically for use in a kubernetes cluster (just tested it on minikube) but haven't been able to get through to postgres following the tutorial (I am on Ubuntu 16.04 lts) 

I spun up ectd from https://github.com/coreos/etcd/tree/master/hack/kubernetes-deploy and pointed all stolon endpoints to the etcd client. 

After creating the keeper, sentinel, proxy, proxy service and secret it turns out that the endpoint is inside the cluster only, so I exposed the proxy service as a nodeport to allow testing. 

When running:
psql --host minikubeip --port describenodeport -U stolon -w (using password1) I get a: 
psql: FATAL:  database "stolon" does not exist

I tried it on another type of cluster that was not minikube (https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.html) with the same result. 

Reading the stolon-keeper, it says PG_SU_USERNAME is set to "stolon" and I have run the example completely as is, and haven't changed anything except the etcd endpoint. What am I doing wrong here?

This was yesterday - when I tried today I kept getting "ErrImagePull: "net/http: request canceled" on all the pods (trying with master, latest and 0.3.0 that I saw was comitted earlier).

Despite the trouble I am having, I think you made a really cool tech here. I love the idea and the implementation as well, it's quite clever.

**Comment by Sharor** [comment]
Just as followup - I think the error in image pull was caused by minikube not going up properly, since that part seems to work after reloading minikube, my apologies.

**Comment by sgotti** [comment]
@Sharor I think you forgot to specify the database name. The k8s example [README](https://github.com/sorintlab/stolon/tree/master/examples/kubernetes) uses `postgres` in the `psql` connection command (the db cluster is initialized by the keeper using initdb so the default postgres databases `postgresql, template0, template1` are created):

`psql --host minikubeip --port describenodeport postgres -U stolon -W`

**Comment by Sharor** [comment]
@sgotti  Ah ! Okay that makes sense - thank you so much. :+1: 

Also in case you did not know already, when you research kubernetes psql cluster everybody suggests your solution. Really good work here :)
