### ISSUE TITLE
Question: does a degraded/unhealthy keeper require manual intervention?

### ISSUE THREAD

**Issue by wchrisjohnson** [sorintlab/stolon#155]
I just performed an upgrade of my stolon cluster, and the cluster appeared to come up ok - I could log into my app and use it as normal. However, when I used stolonctl to look at the cluster, I saw the following:
```
=== Active sentinels ===

ID		LISTENADDRESS		LEADER
feb16396	172.18.22.9:6431	true

=== Active proxies ===

ID		LISTENADDRESS		CV VERSION
41c35f58	172.18.28.15:5432	5

=== Keepers ===

ID		LISTENADDRESS		PG LISTENADDRESS	CV VERSION	HEALTHY
1e3248eb	172.18.22.15:5431	172.18.22.15:5432	4		false
606b5dc6	172.18.28.18:5431	172.18.28.18:5432	5		true
6ce6660e	172.18.28.12:5431	172.18.28.12:5432	5		true

=== Required Cluster View ===

Version: 5
Master: 606b5dc6

===== Keepers tree =====

606b5dc6 (master)
├─1e3248eb
└─6ce6660e
```

I've looked thru the code for the keeper and the sentinel, and it doesn't look like degraded/unhealthy  keepers like the one above get automatically reprovisioned back into the cluster as a standby. I've been waiting for about 20 minutes now, and it doesn't appear to be going to reprovision. 

I kill the pod in Kubernetes and the keeper comes back, and none of the above changed. It shows the following in the log:
```
2016-10-08T22:51:36.019566201Z 2016-10-08 22:51:36.019463 [keeper.go:1049] I | keeper: id: 1e3248eb
2016-10-08T22:51:36.019590261Z 2016-10-08 22:51:36.019479 [keeper.go:1052] I | keeper: running under kubernetes.
2016-10-08T22:51:36.038971598Z 2016-10-08 22:51:36.038852 [postgresql.go:177] I | postgresql: Stopping database
2016-10-08T22:52:36.111371808Z 2016-10-08 22:52:36.111192 [postgresql.go:177] I | postgresql: Stopping database
```

**Comment by wchrisjohnson** [comment]
This is likely related to https://github.com/sorintlab/stolon/issues/153 for what it's worth.

**Comment by sgotti** [comment]
@wchrisjohnson Looks like a dup of #153. Closing.
