### ISSUE TITLE
Stolon "standby" cluster

### ISSUE THREAD

**Issue by sgotti** [sorintlab/stolon#157]
For multi datacenter replication (for disaster recovery) a good enhancement will be to be able to create a "standby" stolon cluster where the "master" pg instance (but this definition should be changed) node will be a postgres standby instance following an external pg instance. The other cluster instances will just be standbys of this instance like usual. The external instance can be another stolon cluster with the replication connection string pointing to one stolon proxies or multiple load balanced (or a k8s service) proxies. So we can achieve multi datacenter replicated stolon clusters. Obviously only one of these will be the "master" cluster and the user should manually promote a standby cluster to a master cluster.

Another interesting use case for this feature will be (near) zero downtime migration to a new stolon cluster from another postgres architecture (standalone, another kind of cluster etc...).

`stolonctl` will add a command to promote the "standby" cluster to a "master" cluster.

**Comment by gflarity** [comment]
@sgotti Could you please give an outline of what would be involved in supporting this and the correct way to go about it? Also an estimate of how long it would take you? This is a feature I'd really to see and I'd be willing to have one of our devs tackle it.

**Comment by sgotti** [comment]
@gflarity The basic idea is to be able to have the "master" instance being a standby of an external instance (than can be any postgresql instance, not only another stolon cluster).

The primary steps will be to be able to have a "master" instance being a standby. For this the basic code should already be in place. There's the need to extend the init mode for initializing the instance as a standby, add some integration tests and add a "promote" command to `stolonctl`.

I was hoping to work on this in the next weeks but if you want to take a stab at it I'll be very happy to help and review. Thanks!

**Comment by gflarity** [comment]
Thanks for the info @sgotti we're still in the process of figuring out how we can best spend our resources here. But we'd really like to help get this feature out sooner. I'll talk it over with the team.

**Comment by sgotti** [comment]
#283 implements this feature.

**Comment by sgotti** [comment]
#283 has been merged.
