### ISSUE TITLE
Disable alter system

### ISSUE THREAD

**Issue by sgotti** [sorintlab/stolon#189]
Stolon generates the `postgresql.conf` with it's managed and mandatory parameters and the user defined ones in the cluster spec. We aren't setting our managed parameters in command line since they need to be updated without restarting the instance.
With this logic changing them with an alter system should be disabled because it will write the defined settings inside `postgresql.auto.conf` that'll ovverride the `postgresql.conf`.
This causes various issues:
* Unaligned setting between instance
* No way to notice these changes without monitoring them.

So IMHO there's the need to disable `alter system` by default (ad let the user re-enable it with a cluster spec option).

For doing this I tested two different "hacks":

* create `postgresql.auto.conf` as a symlink to /dev/null
* remove write permissions to `postgresql.auto.conf`

Looks like both work. The latter is more verbose on error reporting in the log when querying the parameters since it reports a permission error.

**Comment by charles-dyfis-net** [comment]
Hmm. As a counterargument (re: selecting between implementations), the symlink is more obviously intentional -- I could see someone interpreting the error as a configuration mistake and modifying those permissions to "correct" them.

**Comment by sgotti** [comment]
@charles-dyfis-net thanks for the suggestion! I opened #343 that will make postgresql.auto.conf a symlink to /dev/null. NOTE that an ALTER SYSTEM will return an error since postgres cannot fsync /dev/null.

**Comment by sgotti** [comment]
Implemented in #343
