### ISSUE TITLE
Google Container Engine Compatibility

### ISSUE THREAD

**Issue by theothermike** [sorintlab/stolon#239]
I'm attempting to get Stolon to run on our GKE clusters, using the git version.  Even though GKE uses 'etcd' behind the scenes, it does not appear to be publicly exposed.   

There is the 'Kubernetes Master' service, but it's not running on etcd port, and I couldn't get it to work with Stolon.  I've also grabbed the 'etcd' pod from the 'coreos' project, and running an independent etcd store.  I've confirmed it works with internal and externally provided IPs, but the two ways I've tried to get Stolon to run, using the 'ReplicationController' and 'StatefulSet' approaches (with the STL*_ENDPOINTS defined to be the etcd cluster), they fail.

With the RC approach, 'stolonctl init <params>' always fails with 'cannot get cluster data: etcd cluster is unavailable or misconfigured'.

With the StatefulSet approach, I can get the pods and services up, but the Keeper, while initially complaining about etcd (but that went away with the additional etcd install on the same cluster), it complains that it's not initialized.

Have you guys successfully run this on GKE?  What am I missing?

**Comment by sgotti** [comment]
> There is the 'Kubernetes Master' service, but it's not running on etcd port, and I couldn't get it to work with Stolon.

Yes, that etcd is reserved for k8s api services.

> With the StatefulSet approach, I can get the pods and services up, but the Keeper, while initially complaining about etcd (but that went away with the additional etcd install on the same cluster), it complains that it's not initialized.

Both approach are the identical, the unique difference is how the keepers are managed. 

From what you wrote I can understand that the stolon components are able to talk with your deployed etcd pod right?

If so, the unique problem is that you're probably running stolonctl from you machine where you have not access to the etcd port.

You can run stolonctl inside one of the stolon pods (entering the pod with `kubectl exec podid -it /bin/bash`) or use `kubectl proxy` to expose the etcd port to your machine.

**Comment by theothermike** [comment]
Thanks, I will give this a try when time allows and update the ticket

**Comment by theothermike** [comment]
Connecting to the keeper pod, after starting up, allowed me to run init with the appropriate commandline args.  Looks like it worked!

I am in the process of integrating this with our own environment, and may send things like the init in pull requests as a k8s job to make it easier to run
