### ISSUE TITLE
Role of the "/stolon-data" directory under Kubernetes

### ISSUE THREAD

**Issue by testark** [sorintlab/stolon#240]
What is the role of the `/stolon-data` directory under Kubernetes?

https://github.com/sorintlab/stolon/blob/v0.5.0/examples/kubernetes/rc/stolon-keeper0.yaml#L55

I've had a look at a running keeper instance and the `/stolon-data` directory is always empty. Everything is stored under `/var/lib/postgresql/data`. Shouldn't the volume be mounted at `/var/lib/postgresql/data` instead of `/stolon-data`?

**Comment by sgotti** [comment]
Looks like with the latest examples refactor we forgot to set PGDATA to `/stolon-data` so its using the default image one. `/stolon-data` is the right one since we need persistent data. Will open a PR to fix it. Thanks!
