### ISSUE TITLE
There is a bracket in my synchronousStandbys

### ISSUE THREAD

**Issue by nh2** [sorintlab/stolon#242]
From my sentinel log after using `stolonctl update --patch` to change `minSynchronousStandbys`:

```
[E] 2017-03-10T15:24:25Z sentinel.go:234: no keeper info available db=a97fd754 keeper=stolon_3
[I] 2017-03-10T15:24:25Z sentinel.go:743: master db is failed db=a97fd754 keeper=stolon_3
[I] 2017-03-10T15:24:25Z sentinel.go:754: trying to find a new master to replace failed master
[W] 2017-03-10T15:24:25Z sentinel.go:771: cannot choose synchronous standby since the latest master reported synchronous standbys are different from the db spec ones reported=([]string) (len=1 cap=4) {
 (string) (len=9) "f7b5fa8d)"
}
 spec=([]string) (len=2 cap=4) {
 (string) (len=8) "35ff791c",
 (string) (len=8) "f7b5fa8d"
}
[E] 2017-03-10T15:24:25Z sentinel.go:788: no eligible masters
```

Note `(len=9) "f7b5fa8d)"` -- there is a `)` at the end of the string!?

Is that intended?

Inspecting consul, I can also see it in the `stolon/clusterdata`:

```
... "shared_buffers":"128MB","timezone":"UTC"},"synchronousStandbys":["f7b5fa8d)"]}}
```

What's going on, is this a data corruption of the stolon state in Consul or does the bracket have a meaning?

**Comment by sgotti** [comment]
@nh2 thank for you report.

I think this is a bug in parsing the `synchronous_standby_names` parameters [here](https://github.com/sorintlab/stolon/blob/0661b73322c3cab306378f397d76ba070c8d3f21/cmd/keeper/keeper.go#L475) since it's not considering the ending bracket.

We should also better validate keeper names before inserting them in the cluster data.

To fix this broken cluster data you can rewrite the fixed cluster data directly in the store. You should stop the sentinels (the keepers and proxies can be left active, get the latest cluster data, write it to the store and then restart the sentinels).

**Comment by nh2** [comment]
> I think this is a bug in parsing the synchronous_standby_names parameters here since it's not considering the ending bracket.

That is correct, e.g. the output of `select name, setting from pg_file_settings;` is:

```
...
 synchronous_standby_names  | 2 (stolon_2c3870f3,stolon_c874a3cb)
```

So I guess the code [here](synchronousStandbyNames := strings.Split(pgParameters["synchronous_standby_names"], ",")):

```go
synchronousStandbyNames := strings.Split(pgParameters["synchronous_standby_names"], ",")
```

splits `2 (stolon_2c3870f3,stolon_c874a3cb)` into `2 (stolon_2c3870f3` and `stolon_c874a3cb)`, then `common.IsStolonName(n)` is `false` on the first one and it silently continues, and for the second one `common.IsStolonName(n)` is `true` (despite the weird bracket) and that's how we arrive at this problem.

I assume this bug was introduced by postgres 9.6 changing the format of this field as compared to 9.5, as for 9.6 they have this k-out-of-n synchronous standby feature.

**Comment by nh2** [comment]
See #245 for a fix proposal. Please test it though, I've only tested it with 9.6's synchronous replication.
