### ISSUE TITLE
Make stolon-proxy listen on all intrfaces.

### ISSUE THREAD

**Issue by tarabanton** [sorintlab/stolon#243]
Hi. We have an environment where all of our IP's are dynamic and we have several interfaces. We select stolon-proxy based on information from consul. Is it possible to set up stolon-proxy the way, that it listens on ALL interfaces. Like in `*:5432` or `:::5432`

Now we need to directly configure external IP of node, to avoid binding to localhost of other IP.

**Comment by nh2** [comment]
I'm not sure I understand this, isn't what you want the same as binding to `0.0.0.0:5432`?

**Comment by tarabanton** [comment]
It was my mistake. Sorry
