### ISSUE TITLE
Postgres stderr logs as part of stolon-keeper

### ISSUE THREAD

**Issue by ksesong** [sorintlab/stolon#244]
I am running `stolon-keeper` as part of a docker image, and I cannot find a way to see logs (via the command `docker logs`) of both `stolon-keeper` and the underlying `postgres` process. Only the logs related to the operation of `stolon-keeper` are shown.
(I can of course `ssh` into the container and read the logs from there just fine, and I made sure that the postgres parameter`log_destination` is set to `stderr`)

Is there anything I should pay attention to?

**Comment by sajal** [comment]
Was wondering the same
https://github.com/sorintlab/stolon/blob/master/pkg/postgresql/postgresql.go#L196

I guess cmd.Std[err|out] needs to be redirected to os.Std[err|out]

**Comment by Elexy** [comment]
I know this is an old issue, but I was wondering what could be a reason I don't see any postgres logs in  my docker output?

I am using https://github.com/lwolf/stolon-chart which is based on the kubernetes example in this repo and my keeper logs look like this:
```
[I] 2017-08-24T14:41:15Z keeper.go:1235: our db requested role is master
[I] 2017-08-24T14:41:15Z keeper.go:1255: already master
[I] 2017-08-24T14:41:15Z keeper.go:1410: postgres parameters not changed
[I] 2017-08-24T14:41:20Z keeper.go:1235: our db requested role is master
[I] 2017-08-24T14:41:20Z keeper.go:1255: already master
[I] 2017-08-24T14:41:20Z keeper.go:1410: postgres parameters not changed
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
[I] 2017-08-24T14:41:25Z keeper.go:1235: our db requested role is master
[I] 2017-08-24T14:41:25Z keeper.go:1255: already master
[I] 2017-08-24T14:41:25Z keeper.go:1410: postgres parameters not changed
```
