### ISSUE TITLE
dbstate file can end up empty

### ISSUE THREAD

**Issue by nh2** [sorintlab/stolon#247]
I encountered a situation where the file `/path/to/dbstate` was empty (0 bytes length) and `stolon-keeper` would emit:

```
cannot create keeper: failed to load db local state file: unexpected end of JSON input
```

Is it possible that this happens if the keeper dies at the right moment? Maybe it should use an atomic move (write to a temp file first, then `mv` to the target location) to avoid this?

**Comment by nh2** [comment]
See #248 for a PR

**Comment by sgotti** [comment]
@nh2 you're right. I thought doing this when implementing but totally forgot. If I remember it correctly we are just doing some similar to #248 in `pkg/postgres` but inline.

Just for curiosity, do you saw what was the error causing this (something like a ENOSPC?)?

Thanks!

**Comment by nh2** [comment]
> Just for curiosity, do you saw what was the error causing this (something like a ENOSPC?)?

@sgotti The `keeper` getting killed due to reboot, while running on a slow network file system; that leaves lots of time for the file being written incompletely.
