### ISSUE TITLE
Issues with pitr init

### ISSUE THREAD

**Issue by sajal** [sorintlab/stolon#250]
stolonctl init '{ "initMode": "pitr", "pitrConfig": { "dataRestoreCommand": "wal-e backup-fetch %d LATEST" , "archiveRecoverySettings": { "restoreCommand": "wal-e wal-fetch \"%f\" \"%p\"" } } }'

(Wal-e environment is set already. )

I am evaluating stolon (on kubernetes) and these are the steps I have taken.

1. Setup stolon mostly based on examples. - success
2. Set up wal-e wal push  - success
3. Take a base backup - success
4. Tear down the whole cluster (to simulate data center going completely dark)  - success
5. Attempt to restore database in fresh cluster  - FAIL

Postgress gives this error : `LOG: WAL file is from different database system: WAL file database system identifier is 6371283279751802915, pg_control database system identifier is 6387300096061227044`

Should the `pg_control` be reset when recovering from scratch?

Complete log:

````
[I] 2017-03-16T10:00:54Z postgresql.go:191: starting database
waiting for server to start....LOG:  could not open usermap file "/stolon-data/postgres/pg_ident.conf": No such file or directory
LOG:  database system was interrupted; last known up at 2017-02-15 11:48:49 GMT
LOG:  creating missing WAL directory "pg_xlog/archive_status"
LOG:  starting archive recovery
wal_e.operator.backup INFO     MSG: begin wal restore
        STRUCTURED: time=2017-03-16T10:00:54.648664-00 pid=740 action=wal-fetch key=s3://<snipped>/experiment/wal_005/000000010000000000000004.lzo prefix=experiment/ seg=000000010000000000000004 state=begin
FATAL:  the database system is starting up
.FATAL:  the database system is starting up
[E] 2017-03-16T10:00:56Z keeper.go:462: cannot get configured pg parameters error=pq: the database system is starting up
FATAL:  the database system is starting up
.wal_e.blobstore.s3.s3_util INFO     MSG: completed download and decompression
        DETAIL: Downloaded and decompressed "s3://<snipped>/experiment/wal_005/000000010000000000000004.lzo" to "pg_xlog/RECOVERYXLOG"
        STRUCTURED: time=2017-03-16T10:00:56.526619-00 pid=740
wal_e.operator.backup INFO     MSG: complete wal restore
        STRUCTURED: time=2017-03-16T10:00:56.528862-00 pid=740 action=wal-fetch key=s3://<snipped>/experiment/wal_005/000000010000000000000004.lzo prefix=experiment/ seg=000000010000000000000004 state=complete
LOG:  restored log file "000000010000000000000004" from archive
LOG:  WAL file is from different database system: WAL file database system identifier is 6371283279751802915, pg_control database system identifier is 6387300096061227044
LOG:  invalid checkpoint record
FATAL:  could not locate required checkpoint record
HINT:  If you are not restoring from a backup, try removing the file "/stolon-data/postgres/backup_label".
LOG:  startup process (PID 738) exited with exit code 1
LOG:  aborting startup due to startup process failure
LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
````

**Comment by sgotti** [comment]
@sajal Just a wild guess. Looks like the wals are from a different database than the one of the basebackup. Can you check if this is the case?

The pg_control is the one provided from the basebackup and stolon doesn't touch it and there should be the need to do this.

**Comment by sajal** [comment]
@sgott you might be right, I will try dump and restore in a fresh place.

**Comment by sajal** [comment]
@sgotti : I can confirm it works now. What I was doing wrong earlier was I stupidly made base backups from multiple test clusters(but not at the same time) into the same s3 location. 

Closing this.

**Comment by sgotti** [comment]
Glad you figured out the problem. Thanks for reporting!
