### ISSUE TITLE
Removing dead keepers from clusterdata

### ISSUE THREAD

**Issue by cuu508** [sorintlab/stolon#258]
While practicing with a test cluster, I somehow got into a state where stolon remembers some keepers that don't exist any more. They show up in `stolonctl status` output and I can also see them kicking around in `stolon-sentinel` stdout log:

    no keeper info available db=.... keeper=...

Are they being cleaned up automatically? If not, what is the correct cleanup procedure?

I suppose I could get, edit, and then put back the "stolon/cluster/mycluster/clusterdara" key in consul, but is there a better way?

**Comment by sgotti** [comment]
@cuu508 There's an open enhancement (#87) to add keeper removal. I added some context to that issue just now. It's something that I'll work on in the next weeks.

> I suppose I could get, edit, and then put back the "stolon/cluster/mycluster/clusterdara" key in consul, but is there a better way?

Unfortunately this is the unique way right now and can be error prone causing problems to the cluster so I'll not do this. If you're going to do this be sure to stop all the sentinels to avoid concurrently (over)writing the data updated by the master sentinel.

**Comment by sgotti** [comment]
@cuu508 if you don't have other questions I'll close this and continue on #87
