### ISSUE TITLE
Why in cluster PSQL with 3 node one node - sync_state= sync and next node sync_state= async?

### ISSUE THREAD

**Issue by mausspb** [sorintlab/stolon#261]
I deployed PostgreSQL via docker local with default settings, but add in stolon/examples/docker/etc/init-spec.json `"synchronousReplication":true`. 
But when i check type SELECT * FROM pg_stat_replication;
- i get first node - sync_state=sync,and other async, what is ? Why its two different type ?

My ask in [stackoverflow](http://stackoverflow.com/questions/43527998/why-in-cluster-psql-with-3-node-one-node-sync-state-sync-and-next-node-sync-s)

How i can change config file (my cluster in docker containers) , example change this `wal_level` option?

**Comment by sgotti** [comment]
@mausspb this is probably a general postgres question. By default you'll have one synchronous standby so the one with the 'sync' state is the synchronous one. Starting with postgres 9.6 you can have more than one sync standbys and with stolon you can define in the cluster config a min and max number of sync standbys: https://github.com/sorintlab/stolon/blob/master/doc/syncrepl.md
