### ISSUE TITLE
can I initialize a cluster use some custom parameters in initdb

### ISSUE THREAD

**Issue by smkingsoft** [sorintlab/stolon#272]
when i use stolonctl and stolon-keeper init a pg cluster.
stolon exec command 
`initdb -D xxx -U xxx --pwfile xxx ` 
to initialize cluster database.

Now i need append some parameters just like -E UTF8 -k, how can i do?
thks.

-E encoding
--encoding=encoding
Selects the encoding of the template database. This will also be the default encoding of any
database you create later, unless you override it there. The default is derived from the locale, or
SQL_ASCII if that does not work. The character sets supported by the PostgreSQL server are
described in Section 23.3.1.
-k
--data-checksums
Use checksums on data pages to help detect corruption by the I/O system that would otherwise
be silent. Enabling checksums may incur a noticeable performance penalty. This option can only
be set during initialization, and cannot be changed later. If set, checksums are calculated for all
objects, in all databases.

**Comment by sgotti** [comment]
@smkingsoft  I answered in #179. Let's continue the discussion there.
