### ISSUE TITLE
Missing logs when recovering from base backups

### ISSUE THREAD

**Issue by ksesong** [sorintlab/stolon#273]
As I've been trying to do a point-in-time-recovery using `wal-e`, I've realised that the first step which consists in running the `dataRestoreCommand` (here, the `wal-e backup-fetch`) was not logged within the `stolon-keeper` process. The second step (database launch and archive recovery) is logged properly.

This could be useful to be notified about the fetching progress, but also to be aware of any restoration issues (in my case, there was an error related to the "lack of free space", but the only information I had in the logs were the repeating lines `restoring the database cluster`).
I had to run the command `wal-e backup-fetch` outside of `stolon` to learn about the error.

Thanks!

**Comment by sgotti** [comment]
@ksesong thank for you report! I'll need to check the code but probably we aren't capturing and emitting the `dataRestoreCommand` stdout/stderr or there's a bug somewhere.

**Comment by sgotti** [comment]
Created PR #286

**Comment by sgotti** [comment]
Fixed in #286
