### ISSUE TITLE
Possible bug (SIGSEGV) when both master and slave go down?

### ISSUE THREAD

**Issue by Jorl17** [sorintlab/stolon#276]
Hi,

During some of our experiments, we have run into an issue. Assume the following scenario:
* A (master)
* B (replicating from master)

1. Terminate B
2. Insert data into A
3. Terminate A
4. Start B. It obviously cannot sync (this is expected)
5. Start A.

In our scenario, we are hitting this:

```keeper_1  | [D] 2017-05-12T12:50:34Z keeper.go:839: db status started=false
keeper_1  | [I] 2017-05-12T12:50:34Z keeper.go:856: current db UID different than cluster data db UID db= cdDB=68407c0c
keeper_1  | [I] 2017-05-12T12:50:34Z keeper.go:996: resyncing the database cluster
keeper_1  | [I] 2017-05-12T12:50:34Z keeper.go:1025: database cluster not initialized
keeper_1  | panic: runtime error: invalid memory address or nil pointer dereference
keeper_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x93a3da]
keeper_1  |
keeper_1  | goroutine 31 [running]:
keeper_1  | main.(*PostgresKeeper).postgresKeeperSM(0xc42006f080, 0x7fc7b3c3e840, 0xc4201586c0)
keeper_1  | 	/stolon/gopath/src/github.com/sorintlab/stolon/cmd/keeper/keeper.go:1034 +0x848a
keeper_1  | main.(*PostgresKeeper).Start.func1(0xc42006f080, 0x7fc7b3c3e840, 0xc4201586c0, 0xc4200136e0)
keeper_1  | 	/stolon/gopath/src/github.com/sorintlab/stolon/cmd/keeper/keeper.go:631 +0x3f
keeper_1  | created by main.(*PostgresKeeper).Start
keeper_1  | 	/stolon/gopath/src/github.com/sorintlab/stolon/cmd/keeper/keeper.go:633 +0xc92```

Is this a known bug or is something being incorrectly configured? I can provide more details if required.

Thanks!

**Comment by sgotti** [comment]
@Jorl17 that's a really basic scenario and is covered by various integration testa so it shouldn't fail badly as in your case.

If the provided log is from the master I have the suspect that the keeper started from an empty datadir (so no keeper and master db data). Can you check if this is the case?

How are you deploying stolon (standalone, under kubernetes etc...)?
Are you providing a "persistent" datadir to your keepers?

**Comment by Jorl17** [comment]
Thank you for your answer. I suspected this was an issue on our part (hence "possible bug" and not "bug"). You pointed us in the right direction: although we are using a custom docker solution with persistent volumes, there was a typo in our named volume path and, so, the directory was empty on reboot.

Once again thank you much for your answer, without which we would not have easily found the problem!

**Comment by sgotti** [comment]
@Jorl17 glad you figured it out. To improve this we should handle this case in the code and report a better error. Now this case isn't handled and the keeper crashes. Thought I'm not sure what's the reason so I'll need to to reproduce it.
