### ISSUE TITLE
Postgres contrib modules support e.g multicorn

### ISSUE THREAD

**Issue by themsay** [sorintlab/stolon#277]
Hi,

I'm happy to see this project. Looking through the docs, I can't find how to add Postgres modules like postgresql-contrib, python-multicorn etc.

If Stolon support installing module or custom Postgres image build, I'll be happy to know which way to go about it?

Thanks in advance for your responses.

**Comment by sgotti** [comment]
@themsay we want stolon to only manage high availability (and what's is related like pitr). So you should be able to install any extension (just be sure to keep all the binaries in sync).

The stolon docker image if just an example for the k8s examples so you should create your image (if you're using k8s, docker etc...) with your preferred extensions.

**Comment by themsay** [comment]
Thanks @sgotti your right on point.
