### ISSUE TITLE
Is it possible to use a ETCD3 storage ?

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#302]
Hello,

I am using Kubernetes v1.6 and v1.7, which need ETCD3 cluster to work.

I would like to take this ETCD3 HA storage also for STOLON, and not to install another additional DB.

In the configuration file of sentinel, I use the following environment variables:
```
- name: STSENTINEL_STORE_BACKEND
  value: "etcd"
- name: STSENTINEL_STORE_ENDPOINTS
  value: "http://x.x.x.x:2379"
```

But this error messages are repeating every 3 seconds on the **sentinel**:
```
...
[I] 2017-07-04T07:28:10Z sentinel.go:101: Trying to acquire sentinels leadership
[E] 2017-07-04T07:28:10Z sentinel.go:121: election loop error error=client: etcd cluster is unavailable or misconfigured
[E] 2017-07-04T07:28:10Z sentinel.go:1430: error retrieving cluster data error=client: etcd cluster is unavailable or misconfigured
...
```
I know which is the problem, Stolon uses API v2, even if the database is ETCDv3:
https://github.com/sorintlab/stolon/issues/300#issuecomment-312742495

The question is: Is there any param to say sentinel to use an ETCDv3 database, although using API v2 ?

Thank you.

**Comment by sgotti** [comment]
@guillelb stolon works with etcd v3 but uses the etcd v2 API. So I think there's something wrong on your configuration side but the libkv etcd implementation returns very generic error making it difficult to debug. So you should check on your side for what can be wrong. How is your etcd cluster configured, does it requires tls? etc... Have you tried using etcdctl, that by default (if not specifing the ETCDCTL_API=3) also uses the v2 api, if using the same endpoints it works?

PS. these kind of questions should be asked on the mailing list. The answer is already provided in #100 and #300 so I'm closing this and if you want please continue on the mailing list.

**Comment by guillelb** [comment]
From sentinel docker:

- With API v3:
```
ETCDCTL_API=3 etcdctl --endpoints=http://x.x.x.x:2379 put hola adios
OK
```

- Without that:
```
# etcdctl --endpoints=http://x.x.x.x:2379 put hola adios
Error:  client: etcd cluster is unavailable or misconfigured
```

This is the same error that shows sentinel
`[E] 2017-07-04T07:28:10Z sentinel.go:121: election loop error error=client: etcd cluster is unavailable or misconfigured`
