### ISSUE TITLE
StatefulSet deployment in kubernetes

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#309]
Hello,

StatefulSets are a still beta feature in k8s v1.7. [https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/](url)

Do you recommend to use it in a production environment?

Or, Is it better use PetSet also in the last k8s version?

**Comment by sgotti** [comment]
@guillelb from what I know statefulset is the new name of petset from k8s 1.5: https://kubernetes.io/docs/concepts/workloads/controllers/petset/ . Please use the mailing list or gitter for this kind of questions.
