### ISSUE TITLE
Slave DB not promoted into master is case of the network split

### ISSUE THREAD

**Issue by kimss** [sorintlab/stolon#327]
Hi the Sorintlab Guys,
can you please assist me with the problem - question. We have eumlated the network split and discovered the stable case which we don't understand.

The environment:
1) Server A.
   - ETCD instance
2) Server B.
  - ETCD instance
  - Stolon instance (Sentinel, Keeper, Proxy)
  - PostgreSQL 9.6 instance
3) Server C.
  - ETCD instance
  - Stolon instance (Sentinel, Keeper, Proxy)
  - PostgreSQL 9.6 instance
Master DB is being hosted by the Server B, the "stolonctl status" command confirms it. Also the ETCD cluster has quorum (3 nodes). The synchronous replication from Server B to server C is configured.

Test:  emulate network split by executing the "ifdown on Server B".

After the network is disconnected we observe that the slave PostgreSQL on Server C is not promoted into Master. Should the PostgreSQL on Server C be promoted into Master?

P/S: Probably it is the design of the solution which we don't understand so far.

**Comment by sgotti** [comment]
@kimss the mailing list is a better place to ask for support: https://groups.google.com/forum/#!forum/stolon (this github issue tracker is for talking about reproducible issues or feature requests). 

Can you please write to the mailing list and in the meantime provide your clusterspec and the keepers and sentinel logs? (as I see you said synchronous replication I have a clue on what could be the problem but I need to take a look at the logs). Thanks!

**Comment by sgotti** [comment]
@kimss I answered on https://groups.google.com/forum/#!topic/stolon/X_Ymz1jWfCE . Closing this. Thanks!
