### ISSUE TITLE
Using stolon without a password

### ISSUE THREAD

**Issue by nh2** [sorintlab/stolon#339]
Hi,

It seems that stolon can't be used without a password; if I use `pg-repl-password` with the empty string then `stolon-keeper` doesn't seem to be able to start the db.

I'm running stolon in a fully firewalled setup where it would be convenient to use it without password, as all services behind the firewall are allowed to use the db.

Would it be possible to support not giving a password? What would be needed for this?
Thanks!

**Comment by sgotti** [comment]
@nh2 now stolon by default uses md5 password authentication. I think we can improve it to accept different authentication methods. In your case I think you'd like to use the `trust` auth method right?
A solution will be to add a keeper option `--pg-repl-auth-method` and initially accept only the most simple to implement ones (like trust, md5, password, pam). This options will basically affect the pg_hba.conf generated replication entries and the user creation when initializing a new pg db cluster.

In addition if you pass an empty replication user password (`--pg-repl-password=""`) it considers it an error. But postgres accepts empty passwords so also empty passwords could  be accepted.

> If I use pg-repl-password with the empty string then stolon-keeper doesn't seem to be able to start the db.

It should return an error but you said it failed to start the db. Can you provide more details?

**Comment by nh2** [comment]
> It should return an error but you said it failed to start the db. Can you provide more details?

@sgotti I have an automated setup that boots into a stolon cluster on AWS; it works fine when setting a password, but when I set it to the empty string I currently get this output:

```
systemd[1]: Started stolon-keeper.service.
stolon-keeper: warning: superuser name and replication user name are the same. Different users are suggested.
stolon-keeper: [I] 2017-08-17T12:26:55Z keeper.go:1567: exclusive lock on data dir taken
stolon-keeper: [I] 2017-08-17T12:26:55Z keeper.go:408: keeper uid uid=node_1
stolon-keeper: [I] 2017-08-17T12:26:55Z postgresql.go:215: stopping database
stolon-keeper: pg_ctl: directory "/var/lib/postgres/node_1/postgres" does not exist
stolon-keeper: [I] 2017-08-17T12:26:55Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper: [I] 2017-08-17T12:26:56Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper: [I] 2017-08-17T12:26:57Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper: [I] 2017-08-17T12:26:58Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper: [I] 2017-08-17T12:26:59Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper: [I] 2017-08-17T12:27:00Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper: [I] 2017-08-17T12:27:01Z keeper.go:834: no db assigned
stolon-keeper: [I] 2017-08-17T12:27:02Z keeper.go:834: no db assigned
stolon-keeper: [I] 2017-08-17T12:27:03Z keeper.go:834: no db assigned
stolon-keeper: [I] 2017-08-17T12:27:04Z keeper.go:834: no db assigned
stolon-keeper: [I] 2017-08-17T12:27:05Z keeper.go:834: no db assigned
stolon-keeper: [I] 2017-08-17T12:27:06Z keeper.go:834: no db assigned
stolon-keeper: [I] 2017-08-17T12:27:07Z keeper.go:834: no db assigned
```

That doesn't look like the error you were expecting.

**Comment by sgotti** [comment]
@nh2 probably the errror is on another node, this one is just waiting for a db to be assigned.

By the way, do you agree on the proposed enhancement?

**Comment by nh2** [comment]
@sgotti Yep you're right, on node 3 I've got `initdb: password file ... is empty`:

```
systemd[1]: Started stolon-keeper.service.
stolon-keeper[4597]: warning: superuser name and replication user name are the same. Different users are suggested.
stolon-keeper[4597]: [I] 2017-08-17T12:26:55Z keeper.go:1567: exclusive lock on data dir taken
stolon-keeper[4597]: [I] 2017-08-17T12:26:55Z keeper.go:408: keeper uid uid=node_3
stolon-keeper[4597]: [I] 2017-08-17T12:26:55Z postgresql.go:215: stopping database
stolon-keeper[4597]: pg_ctl: directory "/var/lib/postgres/node_3/postgres" does not exist
stolon-keeper[4597]: [I] 2017-08-17T12:26:55Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper[4597]: [I] 2017-08-17T12:26:56Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper[4597]: [I] 2017-08-17T12:26:57Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper[4597]: [I] 2017-08-17T12:26:58Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper[4597]: [I] 2017-08-17T12:26:59Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper[4597]: [I] 2017-08-17T12:27:00Z keeper.go:828: our keeper data is not available, waiting for it to appear
stolon-keeper[4597]: [I] 2017-08-17T12:27:01Z keeper.go:903: current db UID different than cluster data db UID db= cdDB=d332c8e8
stolon-keeper[4597]: [I] 2017-08-17T12:27:01Z keeper.go:906: initializing the database cluster
stolon-keeper[4597]: The files belonging to this database system will be owned by user "postgres".
stolon-keeper[4597]: This user must also own the server process.
stolon-keeper[4597]: The database cluster will be initialized with locale "en_US.UTF-8".
stolon-keeper[4597]: The default database encoding has accordingly been set to "UTF8".
stolon-keeper[4597]: The default text search configuration will be set to "english".
stolon-keeper[4597]: Data page checksums are disabled.
stolon-keeper[4597]: initdb: password file "/tmp/pwfile182516992" is empty
stolon-keeper[4597]: [E] 2017-08-17T12:27:01Z keeper.go:936: failed to initialize postgres database cluster error=error: exit status 1
stolon-keeper[4597]: [E] 2017-08-17T12:27:02Z keeper.go:853: db failed to initialize or resync
stolon-keeper[4597]: [I] 2017-08-17T12:27:02Z keeper.go:903: current db UID different than cluster data db UID db= cdDB=d332c8e8
stolon-keeper[4597]: [I] 2017-08-17T12:27:02Z keeper.go:906: initializing the database cluster
stolon-keeper[4597]: The files belonging to this database system will be owned by user "postgres".
stolon-keeper[4597]: This user must also own the server process.
stolon-keeper[4597]: The database cluster will be initialized with locale "en_US.UTF-8".
stolon-keeper[4597]: The default database encoding has accordingly been set to "UTF8".
stolon-keeper[4597]: The default text search configuration will be set to "english".
stolon-keeper[4597]: Data page checksums are disabled.
stolon-keeper[4597]: initdb: password file "/tmp/pwfile362952681" is empty
```

> By the way, do you agree on the proposed enhancement?

I think so. I'm not sure though if switching away from md5 is needed to make the most basic form of this work, or if it "just works" (e.g. psql asking for no PW) if you use md5 + empty string (though `initdb` itself doesn't seem to like empty files so maybe that won't work).

**Comment by sgotti** [comment]
> Yep you're right, on node 3 I've got initdb: password file ... is empty:

@nh2 looks like you're also setting the superuser password as empty (since you're using the same user as super user and replication user) but looks initdb is erroring on an empty password file. To handle such case we should change some pg db cluster initialization logic:

* run initdb without providing a super user password
* temporarily set pg_hba local connections to trust
* create the super user with the specified password.



> I think so. I'm not sure though if switching away from md5 is needed to make the most basic form of this work, or if it "just works" (e.g. psql asking for no PW) if you use md5 + empty string (though initdb itself doesn't seem to like empty files so maybe that won't work).

I'll open another issue for supporting different auth mechanism for super users and replication users.

**Comment by sgotti** [comment]
@nh2 from https://www.postgresql.org/about/news/1772/ looks likes postgres disabled empty password for every auth type. I think it's a good idea.

So the solution to avoid using password remains my proposal to handle other auth methods (like trust in your case) for superuser and replication users used by stolon.

**Comment by nh2** [comment]
OK, that makes sense.

**Comment by nh2** [comment]
@sgotti Do we close this though? Where do we track being able to handle other auth types like `trust`?

**Comment by sgotti** [comment]
@nh2 created #362 to track the possibility to accept different auth types.
