### ISSUE TITLE
Remove/Replace old or not syncing keepers

### ISSUE THREAD

**Issue by sgotti** [sorintlab/stolon#35]
If a keeper is dead or not syncing for a configuration defined time it should be removed from the cluster or from the cluster view. In this way the related replication slot on the sender can be freed and the unnecessary wal to be archived.

**Comment by dineshba** [comment]
Can we close this issue as you have already implemented https://github.com/sorintlab/stolon/blob/master/cmd/sentinel/cmd/sentinel.go#L948

**Comment by lawrencejones** [comment]
As @dineshba mentions, this is already provided by the `deadKeeperRemovalInterval` configuration parameter. Closing.
