### ISSUE TITLE
@sgotti Question：the slave postgresql‘s replication status not ok，but the keeper status seams all ok

### ISSUE THREAD

**Issue by abcxiaod** [sorintlab/stolon#352]
@sgotti
# **## Because the below error on the slave pg，the postgresql's process on the slave pg is ok, but the replication is not ok，the wal receiver process is not exist:**
    2017-09-13 09:29:16.206 CST,,,100990,,59b889ec.18a7e,1,,2017-09-13 09:29:16 CST,,0,LOG,00000,"started streaming WAL from primary at 0/7C000000 on timeline 3",,,,,,,,"WalReceiverMain, walreceiver.c:379",""
    2017-09-13 09:29:16.206 CST,,,100990,,59b889ec.18a7e,2,,2017-09-13 09:29:16 CST,,0,FATAL,XX000,"could not receive data from WAL stream: ERROR:  requested WAL segment 00000003000000000000001F has already been removed

# **## the postgresql's process on the slave pg，the wal receiver process is not exist：**
    postgres  16741      1  0 Sep11 pts/0    00:01:10 /home/postgres/pgsql_964/bin/postgres -D /pgdata/postgres -c unix_socket_directories=/tmp
    postgres  16742  16741  0 Sep11 ?        00:00:33 postgres: logger process                                                                        
    postgres  16743  16741  0 Sep11 ?        00:00:04 postgres: startup process                                                                       
    postgres  16744  16741  0 Sep11 ?        00:00:00 postgres: checkpointer process                                                                  
    postgres  16745  16741  0 Sep11 ?        00:00:26 postgres: writer process                                                                        
    postgres  16746  16741  0 Sep11 ?        00:00:16 postgres: stats collector process  

# **## but the stolon status seams all ok, is this a bug?**
=== Active sentinels ===

ID              LEADER
525cc05b        true
bca3ad93        false
c3fe8222        false

=== Active proxies ===

No active proxies

=== Keepers ===

UID             PG LISTENADDRESS        HEALTHY PGWANTEDGENERATION      PGCURRENTGENERATION
postgres_132    10.47.122.132:5432      true    2                       2
postgres_133    10.47.122.133:5432      true    2                       2
postgres_134    10.47.122.134:5432      true    4                       4

=== Cluster Info ===

Master: postgres_134

===== Keepers tree =====

postgres_134 (master)
├─postgres_133
└─postgres_132

**Comment by sgotti** [comment]
@abcxiaod missing wal detection has been added some time ago #312 . What version are you running?

**Comment by sgotti** [comment]
@abcxiaod ping

**Comment by sgotti** [comment]
@abcxiaod I'm going to close this. Will reopen if you can provide the requested information.

**Comment by abcxiaod** [comment]
ok,thanks very much


| |
aaaaaa
|
|
邮箱：abcxiaod@126.com
|
On 11/29/2017 16:48, Simone Gotti wrote:

@abcxiaod I'm going to close this. Will reopen if you can provide the requested information.
