### ISSUE TITLE
Error "Transport endpoint is not connected" don't change the master keeper

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#354]
Hello,

I am using stolon in kubernetes.

This morning, the database was unaccessible, but the cluster status seems to be OK:
```
=== Active sentinels ===

ID              LEADER
304e7386        true
81f3d7cd        false

=== Active proxies ===

ID
2a585628
a206dd27

=== Keepers ===

UID     PG LISTENADDRESS        HEALTHY PGWANTEDGENERATION      PGCURRENTGENERATION
keeper0 172.24.32.3:5432        true    4                       4
keeper1 172.24.0.1:5432         true    2                       2

=== Cluster Info ===

Master: keeper0

===== Keepers tree =====

keeper0 (master)
└─keeper1
```

The log in the master keeper was repeating few hours ago:
`[E] xxx: Transport endpoint is not connected`

To solve it, I had to delete the keeper0 Pod and the master was changed to keeper1.

- Do you know this error?
- Why sentinels don't detect this and change the master keeper automatically?

Thank you.

**Comment by sgotti** [comment]
> [E] xxx: Transport endpoint is not connected

this looks like an os error, without the full logs is difficult to know the cause. They can be related to some fuse fs error. What kind of persistent volumes are you using?

**Comment by guillelb** [comment]
I got a similar error today:

In one keeper:
```
FATAL:  could not open relation mapping file "global/pg_filenode.map": Transport endpoint is not connected
[E] 2017-09-28T06:57:03Z keeper.go:452: failed to get pg state error=stat /stolon-data/postgres/PG_VERSION: transport endpoint is not connected
ERROR:  could not seek to end of file "global/1262": Transport endpoint is not connected
ERROR:  could not open directory "pg_logical/snapshots": Transport endpoint is not connected
ERROR:  could not seek to end of file "global/1262": Transport endpoint is not connected
ERROR:  could not open directory "pg_logical/snapshots": Transport endpoint is not connected
ERROR:  could not seek to end of file "global/1262": Transport endpoint is not connected
ERROR:  could not open directory "pg_logical/snapshots": Transport endpoint is not connected
[E] 2017-09-28T06:57:06Z keeper.go:873: failed to detect if instance is initialized error=stat /stolon-data/postgres/PG_VERSION: transport endpoint is not connected
[E] 2017-09-28T06:57:06Z keeper.go:452: failed to get pg state error=stat /stolon-data/postgres/PG_VERSION: transport endpoint is not connected
ERROR:  could not open directory "pg_logical/snapshots": Transport endpoint is not connected
ERROR:  could not seek to end of file "global/1262": Transport endpoint is not connected
```

In the other keeper:

```
[E] 2017-09-28T06:58:36Z keeper.go:873: failed to detect if instance is initialized error=stat /stolon-data/postgres/PG_VERSION: transport endpoint is not connected
[E] 2017-09-28T06:58:38Z keeper.go:452: failed to get pg state error=stat /stolon-data/postgres/PG_VERSION: transport endpoint is not connected
```

Why the HEALTHY status is true?
```
=== Active sentinels ===

ID              LEADER
39e6eaa3        true
693d361e        false

=== Active proxies ===

ID
42f51f4d
54eddd08

=== Keepers ===

UID     PG LISTENADDRESS        HEALTHY PGWANTEDGENERATION      PGCURRENTGENERATION
keeper0 172.24.128.18:5432      true    4                       4
keeper1 172.24.32.3:5432        true    2                       2

=== Cluster Info ===

Master: keeper0

===== Keepers tree =====

keeper0 (master)
└─keeper1
```

**Comment by sgotti** [comment]
@guillelb can you provide the information I asked in the previous comment?

**Comment by guillelb** [comment]
I am using gluster volumes, directly passed in the yaml file:

```
      volumeMounts:
        - mountPath: /stolon-data
          name: stolon-data
        - mountPath: /etc/secrets/stolon
          name: stolon
      volumes:
        - name: stolon
          secret:
            secretName: stolon
        - name: stolon-data 
          glusterfs:
            endpoints: glusterfs-machines
            path: glvStolon0
            readOnly: false
```

**Comment by sgotti** [comment]
@guillelb so the `Transport endpoint is not connected` error says that were some problems accessing the glusterfs mount point. You should investigate on the causes of that error.

Looks like the db is answering the keeper queries despite the storage error since we are only querying it's in memory data but I'll expect that postgres will exit when failing reading/writing its datafiles or wals, I don't have enough information on the reason why this isn't happening (the read could be cached). Are you doing some writes on it?

At the moment I would like to avoid adding to the keeper checks on the storage status. I'm expecting that postgres will exit and if this isn't happening the check could be done externally using a script or inside k8s as a liveness probe .

**Comment by guillelb** [comment]
I have put a liveness probe on the keepers every 5 seconds, and the problem have never appear again.

It seems maybe entered in a slpeeping state if no oneis using it.
