### ISSUE TITLE
Support wal_level=logical.

### ISSUE THREAD

**Issue by gregorycollins** [sorintlab/stolon#356]
I'm interested in doing logical replication and need wal_level=logical to do it, either as an option or as a replacement for the existing default "hot_standby".

**Comment by sgotti** [comment]
@gregorycollins thanks for the suggestion. I think an option to the cluster spec to define accepted wal levels will be good. Probably the accepted levels could be `hot_standby` (to keep compatibility with pg < 9.6), `replica` and `logical`.

Are you willing to create a PR to implement this?

**Comment by gregorycollins** [comment]
Is logical is a superset of hot_standby? Since 9.4 is the minimum version for wal_level=logical and for stolon it could just be made default, although it's pure overhead if you don't have a use case for it.

I will think about learning just enough Go to implement this, it's not rocket science. I don't need it myself right away, I decided to do the logical transaction shipping for my project at the application level.

**Comment by sgotti** [comment]
> Is logical is a superset of hot_standby? Since 9.4 is the minimum version for wal_level=logical and for stolon it could just be made default, although it's pure overhead if you don't have a use case for it.

Yes, I will avoid forcing logical if the user doesn't need it.

Another implementation solution will be to just read the configured clusterspec pgparameters and see if `wal_level` is defined, if it's not defined or not a valid value (not `hot_standby`, `replica` or `logical`) then set it to `hot_standby` as of now; if defined use its value.

**Comment by sgotti** [comment]
@gregorycollins created PR #450

**Comment by KoT45** [comment]
Hello @sgotti, I'm a university student. I'm working on a project called "Automatic Failover in PostgreSQL Cluster with the Logical Replication" and I think that it will be more useful if I add this feature to an existing open source solution.
What would be the first steps at working on this issue? Are there any materials that could help me?

**Comment by sgotti** [comment]
@KoT45 Hi! This is very interesting and there was already a postgres GSOC related to this: https://wiki.postgresql.org/wiki/GSoC_2018#High_availability_.2F_failover_based_on_logical_replication_for_Stolon_.282018.29

Can you please start this discussion on the Mailing list or gitter channel since I was going to close this issue because it's related to a different feature and I was going to close it since PR #450 has been merged? Thanks!

**Comment by sgotti** [comment]
Fixed in #450

**Comment by gregorycollins** [comment]
@sgotti that's awesome, thank you!
