### ISSUE TITLE
Stolon PITR with WAL-E

### ISSUE THREAD

**Issue by yagooar** [sorintlab/stolon#361]
I implemented the steps needed to use WAL-E as a backup / restore mechanism, following this guide: https://github.com/sorintlab/stolon/blob/master/doc/pitr.md

Yet I found out, that there is no `wal-e` binary in `stolon-keeper`. I assume I need to install the binary there, otherwise I don't see how I can backup the database. In case of Kubernetes, I'd need to create a custom Docker image with the `wal-e` being present.

Is this the way to go, or is there something that I'm missing here?

**Comment by sgotti** [comment]
@yagooar The provided image is an example image for the k8s example and it contains only the stolon binaries.

Everyone has different needs (postgresql extensions, different backup tools etc...) so it won't make sense to put in the example image every possible extension, tool etc...

For the wal-e case you should create an image adding also wal-e and all it's requirementsl or alternatively add an additional containers in the same pod  (i.e. a backup sidecar container with an image containing wal-e and all it's requirements).

**Comment by rimusz** [comment]
@yagooar if you are using kubernetes setup, you could easily add `initContainer` which downloads `wal-e` binary

**Comment by lastonoga** [comment]
Did you solve problem with backups?

**Comment by sgotti** [comment]
@yagooar I'm going to close this since it's not an issue but a question. If you have more questions please use the gitter channel or the mailing list. Thanks.
