### ISSUE TITLE
Feature request: stolonctl status (more fine grained output or REST service)

### ISSUE THREAD

**Issue by Krieke** [sorintlab/stolon#363]
It would be nice to get the status for a zookeeper(s), sentinal(s), proxie(s) service via REST or more fine grained specific stolonctl output. Currently a lot of sed/awk parsing in manual created scripts is required.

**Comment by sgotti** [comment]
@Krieke You can use the `stolonctl clusterdata` output, see #358 .

**Comment by Krieke** [comment]
Cool thx. This can be closed
