### ISSUE TITLE
Long timeout for client when master goes down

### ISSUE THREAD

**Issue by PierreF** [sorintlab/stolon#365]
If a client try to open a connection just after the master goes down, the client may experience a timeout of 2 minutes.

It should be expected that proxy abort the connection as soon as a new master is elected.

Step to reproduce this issue on minikube: https://gist.github.com/PierreF/cbde2755ce460b58b524707c554b61d1

I think the cause is that [net.Dial](https://github.com/sorintlab/stolon/blob/149980c23f193989f7b08eeb1a1f35bda420042d/vendor/github.com/sorintlab/pollon/pollon.go#L71) hang for up to 2 minutes.

net.Dial will hang because:
* The master was up, thus the ARP address is present in arp cache
* When the master goes down (here it's kubectl delete po/...), the IP goes unassigned and the ARP address also. But stay present in arp cache
* When a client try to open a connection, the proxy will net.Dial() the IP of the now down master. Since arp cache is filled, this result in a TCP/IP packet being send to that IP. Nothing will response to this packet, because the address is unassigned.
* TCP will retry sending this TCP/IP packet, while the arp cache is filled, no error will occur.
* As soon as the arp cache is purged and TCP make another retry, no an "host unreachable" error will be raised and net.Dial will fail.

By making net.Dial cancellable (https://github.com/sorintlab/pollon/pull/8), the client fail as soon as the new master is elected as expected.

**Comment by sgotti** [comment]
@PierreF great catch! Thanks! Indeed also the dial call should be cancelled. Let's use this issue to track the vendoring of the fixed pollon.
