### ISSUE TITLE
STKEEPER_PG_LISTEN_ADDRESS is set but port 5432 is mapped to 127.0.0.1

### ISSUE THREAD

**Issue by Krieke** [sorintlab/stolon#366]
When setting the STKEEPER_PG_LISTEN_ADDRESS to a FQDN address that can be resolved I notice that within the Keeper docker container with command ss -tnap that port 5432 only is bound to address 127.0.0.1.

The same principal for stolon-proxy with STPROXY_LISTEN_ADDRESS I notice that the port is correctly bound to the host ip.  

It seems that to this I am not able to connect to the db instance Keeper via the stolon-proxy.

**Comment by Krieke** [comment]
using the docker container: sorintlab/stolon:master-pg9.6

**Comment by sgotti** [comment]
@Krieke Does the the fqdn inside the container resolves to localhost?

**Comment by Krieke** [comment]
ping stolon-keeper-1-apigateway-dsh.marathon.mesos
PING stolon-keeper-1-apigateway-dsh.marathon.mesos (10.142.30.195) 56(84) bytes of data.
64 bytes from 10.142.30.195 (10.142.30.195): icmp_seq=1 ttl=64 time=0.045 ms

The FQDN doesn't resolve to localhost as you can see in the above output.

**Comment by Krieke** [comment]
But now it seems to be as what I am expecting:

State       Recv-Q Send-Q                                               Local Address:Port                                                 Peer Address:Port 
LISTEN      0      128                                                  10.142.30.195:5432                                                            *:*      users:(("postgres",pid=46,fd=5))
LISTEN      0      128                                                      127.0.0.1:5432

**Comment by Krieke** [comment]
So this can be closed.
