### ISSUE TITLE
Automatic DB creation via stolon-sentinel --initial-cluster-spec

### ISSUE THREAD

**Issue by Krieke** [sorintlab/stolon#367]
Since the stolon docker image (sorintlab/stolon:master-pg9.6) is based on the offical postgres 9.6 image I thought I could use the env vars:
    "POSTGRES_DB": "whatever",
    "POSTGRES_PASSWORD": "whatever",
    "POSTGRES_USER": "whatever"
which is ofcourse not the case although that the docker-entrypoint.sh is still the default as is for the postgres 9.6 image.

Then I thought that since I can use the stolon-keeper vars:
    "STKEEPER_PG_SU_USERNAME": "whatever",
    "STKEEPER_PG_SU_PASSWORD": "whatever"
This in combination with the stolon-sentinel --initial-cluster-spec <init-file>
Where init-file : 
{
	"additionalWalSenders": null,
	"initMode": "new",
	"pgHBA": null,
	"synchronousReplication": true,
	"pgParameters": {"pg_database" : "whatever"}
}

But it seems that the "whatever" database is not created.

**Comment by Krieke** [comment]
Any help or feedback on this... it is currently blocking for us to use stolon in case this would not be possible without having additional scripts to be defined.

**Comment by sgotti** [comment]
@Krieke sorry I lost this issue. This can be done providing STKEEPER_  env variables but the pgParameter `pg_database` is not a valid postgres parameter.

**Comment by sgotti** [comment]
I'm going to close this since I can't see the issue here. The image is used only since it's the official postgres image but everything is managed by stolon.
