### ISSUE TITLE
Postgres 10 support

### ISSUE THREAD

**Issue by nh2** [sorintlab/stolon#369]
Not urgent to have this from my side, but I already wanted to point out:

* Postgres 10 has new/additional syntax for `synchronous_standby_names`. See [here](https://wiki.postgresql.org/wiki/New_in_postgres_10#Quorum_Commit_for_Synchronous_Replication). We'd need to handle that so that we don't get something like #242 when they changed the syntax last time.
* Postgres 10 has [Connection Failover and Routing in libpq](https://wiki.postgresql.org/wiki/New_in_postgres_10#Connection_Failover_and_Routing_in_libpq) which may make the entire HA postgres situation better. I don't know though whether this means we don't need `stolon-proxy` any more, or if it cannot handle all its use cases.

**Comment by nh2** [comment]
Also potentially relevant:

https://wiki.postgresql.org/wiki/New_in_postgres_10#Change_Defaults_around_Replication_and_pg_basebackup

**Comment by sgotti** [comment]
Stolon already works and is tested with postgres 10. 

About the new sync standbys options I think this was already discussed on the gitter channel. Do you have an example on where they should help in comparison on how stolon currently handles sync repl?

**Comment by nh2** [comment]
> Stolon already works and is tested with postgres 10.

Ah, I missed [this](https://github.com/sorintlab/stolon/commit/836df948410579d65b62240501b77ab5fafc8338#diff-04c6e90faac2675aa89e2176d2eec7d8R50), I must have been reading the REAME on a non-master commit.

> Do you have an example on where they should help in comparison on how stolon currently handles sync repl?

@sgotti No, I haven't thought about that yet -- what I care most about is that stolon can correctly parse them if it encouters them for any reason, so that it can raise an appropriate warning, versus potentially misunderstanding something like `FIRST 2(node1,node2)` as one node called `FIRST 2(node1` and one called `node2)`.

But thinking about it now, I think stolon could use these to improve performance, e.g. `ANY 2(node1,node2,node3)` might be a good use in a stolon cluster of 3 to reduce write latency (the slower of the 2 standbys will then not matter and won't be able to slow down writes).

**Comment by kedare** [comment]
Any ETA before releasing docker images with Postgresql10 ? :)

**Comment by galvez** [comment]
@kedare https://github.com/sorintlab/stolon/blob/master/examples/kubernetes/image/docker/Dockerfile.template

**Comment by sgotti** [comment]
@nh2 Can you share your ideas to improve sync repl in dedicated issues so we can better discuss them? I'm going to close this.

**Comment by nh2** [comment]
Done in https://github.com/sorintlab/stolon/issues/515 for the `ANY` idea.

I'm not filing a separate issue for the idea of

> Postgres 10 has Connection Failover and Routing in libpq which may make the entire HA postgres situation better. I don't know though whether this means we don't need stolon-proxy any more, or if it cannot handle all its use cases.

because I couldn't see a direct benefit that does things better than `stolon-proxy` does now.
