### ISSUE TITLE
Wal-e backups

### ISSUE THREAD

**Issue by lastonoga** [sorintlab/stolon#373]
**Suggestion:**

Make full documentation for backups. Backups scheme for stolon and how does it exectly works in general.

**Problem:**

I tried to set wal-e backups up. Stolon creates archive backups and everything is fine except basics backups.

Wal-e commands does not work inside stolon-keeper pod. But they works if i put them inside config. 
So thats why i cant do basic backups. Has stolon any requirements? How do you solve that?

**Comment by sgotti** [comment]
@lastonoga There's already documentation for backups. If there's something not clear please detail what's missing and open a PR to improve it.

Stolon can be integrated with any backup tool and doesn't force any choice. There's a wal-e example but it's just an example. It's up to you to implement your preferred backup method and, if you're using containers, create your image with the provided tools.

**Comment by lastonoga** [comment]
@sgotti 

Will be cool if you describe base backups in wal-e pitr section.

Yes, the problem is that i can't do base backups with wal-e as i do it with usual postgres.
Am i right? Execute command in stolon-keeper like
`envdir /env wal-e backup-push /stolon-data`

But there are a lot of errors, it can not find psql and data folder

**Comment by lastonoga** [comment]
@sgotti

What do you think?

**Comment by lastonoga** [comment]
Did not found in docs where db files stores to make backups even with built-in tools

**Comment by lastonoga** [comment]
@sgotti So what about base backups?

**Comment by lastonoga** [comment]
Okey. For everyone else who have that problem.

The right command is 
```
PGUSER=stolon \
PGPASSWORD="your_password" \
envdir /etc/wal-e.d/env wal-e backup-push /stolon-data/postgres
```

But you should also change `/stolon-data/postgres/pg_hba.conf` to allow all local connection.
```
local all all trust
host all all 0.0.0.0/0 trust
```

Also you need it reload configs after
```
sudo - stolon
/usr/lib/postgresql/9.6/bin/pg_ctl reload
```

But it's better to change in out etcd store. **But that doesn't work. And i don't know how to solve that. Documentation says that its right one, but its not!**

```
stolonctl \
--cluster-name=kube-stolon \
--store-backend=etcd \
--store-endpoints=http://etcd-client.default.svc.cluster.local:2379 \
update --patch '{ "pgHBA" : [ "host all all 0.0.0.0/0 trust", "host all all ::0/0 trust", "local all all trust", "host replication repluser 0.0.0.0/0 md5", "host replication repluser ::0/0 md5" ] }'
```

Who knows, please, help

**Comment by sgotti** [comment]
@lastonoga please, as already asked before, don't use the issue tracker as a support forum, you just asked the same question on the gitter channel.

**Comment by lastonoga** [comment]
@sgotti i described for others who will have the same problem to save their time.
Also it seems like a bug because i do that as it describes in documentation.

**Comment by lastonoga** [comment]
@sgotti to make a PR i need to finally solve that

**Comment by sgotti** [comment]
Closing this since it was already discussed on gitter.

**Comment by shishirkh** [comment]
Were you able to figure this one out @lastonoga ? If yes, pls share.
