### ISSUE TITLE
how to custom pg_hba.con

### ISSUE THREAD

**Issue by xingyan532** [sorintlab/stolon#374]
My setting command is as follows:
stolonctl --cluster-name=pgcluster --store-backend=etcd update '{"pgHBA" : "local zabbix zabbix 0.0.0.0/0 trust"}'
The wrong information is as follows:
failed to unmarshal cluster spec: json: cannot unmarshal string into Go struct field ClusterSpec.pgHBA of type []string
how can i set this parameter

**Comment by sgotti** [comment]
@xingyan532 pgHBA is a list of strings: `"pgHBA" : [ "local zabbix zabbix 0.0.0.0/0 trust" ]`

**Comment by lastonoga** [comment]
@xingyan532 
Did you find a solution? Does pg_hba.conf file change?

**Comment by xingyan532** [comment]
I changed pg_hba.conf this way :

stolonctl --cluster-name pgcluster --store-backend=etcd update --patch '{"pgHBA" : [ "local all all trust" ]}'




xingyan532@sina.com
 
From: Kirill
Date: 2017-11-03 22:27
To: sorintlab/stolon
CC: xingyan532; Mention
Subject: Re: [sorintlab/stolon] how to custom pg_hba.con (#374)
@xingyan532
Did you find a solution? Does pg_hba.conf file change?
―

**Comment by sgotti** [comment]
Closing. In future please ask such questions on the mailing list or gitter.
