### ISSUE TITLE
Log statements outputted to stderr instead of stdout

### ISSUE THREAD

**Issue by ntsim** [sorintlab/stolon#375]
Currently all log statements (using Zap) seem to be outputted to stderr, which seems counter-intuitive given that not all log statements are necessarily errors.

If you use something like GCP's Stackdriver, output from stderr is automatically considered to be at the ERROR log level. This means you can't filter the logs properly and is quite problematic for extracting useful information.

Unless I'm missing something here, is there a reason why stdout is not used instead for all log statements?

**Comment by charles-dyfis-net** [comment]
The POSIX standard specifies that stderr is the correct stream for "diagnostic information". This means not just errors, but *all* content that is not in fact a program's expected output.

**Comment by ntsim** [comment]
> Moreover, switching between logging to stdout and logging to stderr based on an individual message's severity means that ordering information between those writes is not guaranteed to be preserved -- which can do serious harm to attempts to reconstruct what was going on when an error took place.

I'm not suggesting that severity should change the message between stdout and stderr, but I am suggesting that log statements (i.e. method calls to the logging library) could be directed to stdout exclusively. It feels to me that it would still conform to the POSIX standard as stderr would still be the place for things such as exceptions and stack traces.

**Comment by charles-dyfis-net** [comment]
"Semantically" only if you aren't familiar with decades-old UNIX conventions -- conventions that exist for extremely compelling reasons.

Consider the case:

```
find / -print0 | xargs -0 run-some-command
```

If `find` printed even a non-error log message on stdout (say, a note that predicate ordering is suboptimal), that content would be read as stdin by `xargs`, and *not* emitted for the user to read.

---

If running under a framework which expects diagnostic messages to be on stdout, the simple thing is simply to redirect stderr to stdout on or before starting consul.

**Comment by ntsim** [comment]
Okay I can see where you're coming from. Whilst correct, I would say that it is somewhat awkward to apply the UNIX/POSIX standards strictly as we are aren't working in the realm of running `find` and `xargs` as some user. I imagine that most people are probably not piping Stolon's output directly into some other program.

All said and done though, thank you for the alternative. I think this is probably the best thing to do if no action is taken from this issue by the project maintainers.

**Comment by sgotti** [comment]
@ntsim I used stderr because it's the unix way of logging (and it's the default for zap but also for the go std log). I noticed that other logging libraries like glog use stdout by default with an option to change it to stderr or set which severity to put to stderr.

As stated by @charles-dyfis-net you can always redirect the stderr to stdout on the command invocation.

If instead you want to easily parse and distinguish the error level, since we are using zap structured logging, we can add an option to format the log output in json format. Now it uses a console colored encoder.

**Comment by ntsim** [comment]
Yes that sounds great, would be good to have more options to control the logging output a bit more in general. Would also suggest having the option for non-coloured output as well.

**Comment by sgotti** [comment]
I'm not sure if there's something else to do in this issue. If someone wants to add more options related to command output format (like json output) fell free to open a PR. Everything else can be done using commands piping without any change to stolon. Closing.
