### ISSUE TITLE
Setting pgHBA up doesn't work

### ISSUE THREAD

**Issue by lastonoga** [sorintlab/stolon#376]
I try to change my pgHBA config as it describes in documentation with

```
stolonctl \
--cluster-name=kube-stolon \
--store-backend=etcd \
--store-endpoints=http://etcd-client.default.svc.cluster.local:2379 \
update --patch '{ "pgHBA" : [ "host all all 0.0.0.0/0 trust", "host all all ::0/0 trust", "local all all trust", "host replication repluser 0.0.0.0/0 md5", "host replication repluser ::0/0 md5" ] }'
```

There are no errors and warning after command usage. And also there are no errors in keeper log.

I tried to `spec` and there is no pgHBA section as i was expected.

**Comment by lastonoga** [comment]
Tried to reset cluster and init with new parameters. Still no effect.
pg_hba.conf file doesn't change. Only manual file editing and reloading configuration works.

**Comment by sgotti** [comment]
@lastonoga since stolonctl doesn't report the pgHBA section looks like you are using an old stolonctl/stolon version.
