### ISSUE TITLE
Keeper_2 (standby) Not able to become standby anymore

### ISSUE THREAD

**Issue by Krieke** [sorintlab/stolon#378]
I have added a log of the keeper_2 If more information is required it can always be given. Currently we notice this in an operational environment so a init of the cluster is not done at the moment.

The service knows that its role should be standby, but it reports its status is none:
2017-11-06T13:29:59.251Z	[34mINFO[0m	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "b6656606"}
2017-11-06T13:29:59.251Z	[34mINFO[0m	keeper/keeper.go:1457	our db role is none

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

2017-11-06T13:29:59.250Z	[35mDEBUG[0m	keeper/keeper.go:841	cd dump: (*cluster.ClusterData)(0xc420011d70)({
 FormatVersion: (uint64) 1,
 Cluster: (*cluster.Cluster)(0xc42044bb60)({
  UID: (string) (len=8) "9843f6f5",
  Generation: (int64) 1,
  ChangeTime: (time.Time) 2017-11-06 07:03:27.709521612 +0000 UTC,
  Spec: (*cluster.ClusterSpec)(0xc4201ba0d0)({
   SleepInterval: (*cluster.Duration)(<nil>),
   RequestTimeout: (*cluster.Duration)(<nil>),
   ConvergenceTimeout: (*cluster.Duration)(<nil>),
   InitTimeout: (*cluster.Duration)(<nil>),
   SyncTimeout: (*cluster.Duration)(<nil>),
   FailInterval: (*cluster.Duration)(<nil>),
   DeadKeeperRemovalInterval: (*cluster.Duration)(<nil>),
   MaxStandbys: (*uint16)(<nil>),
   MaxStandbysPerSender: (*uint16)(<nil>),
   MaxStandbyLag: (*uint32)(<nil>),
   SynchronousReplication: (*bool)(<nil>),
   MinSynchronousStandbys: (*uint16)(<nil>),
   MaxSynchronousStandbys: (*uint16)(<nil>),
   AdditionalWalSenders: (*uint16)(<nil>),
   UsePgrewind: (*bool)(<nil>),
   InitMode: (*cluster.ClusterInitMode)(0xc4204553f0)((len=3) "new"),
   MergePgParameters: (*bool)(<nil>),
   Role: (*cluster.ClusterRole)(<nil>),
   NewConfig: (*cluster.NewConfig)(<nil>),
   PITRConfig: (*cluster.PITRConfig)(<nil>),
   ExistingConfig: (*cluster.ExistingConfig)(<nil>),
   StandbySettings: (*cluster.StandbySettings)(<nil>),
   PGParameters: (cluster.PGParameters) (len=11) {
    (string) (len=11) "lc_monetary": (string) (len=10) "en_US.utf8",
    (string) (len=10) "lc_numeric": (string) (len=10) "en_US.utf8",
    (string) (len=8) "timezone": (string) (len=3) "UTC",
    (string) (len=9) "datestyle": (string) (len=8) "iso, mdy",
    (string) (len=26) "default_text_search_config": (string) (len=18) "pg_catalog.english",
    (string) (len=11) "lc_messages": (string) (len=10) "en_US.utf8",
    (string) (len=15) "max_connections": (string) (len=3) "100",
    (string) (len=14) "shared_buffers": (string) (len=5) "128MB",
    (string) (len=26) "dynamic_shared_memory_type": (string) (len=5) "posix",
    (string) (len=7) "lc_time": (string) (len=10) "en_US.utf8",
    (string) (len=12) "log_timezone": (string) (len=3) "UTC"
   },
   PGHBA: ([]string) <nil>
  }),
  Status: (cluster.ClusterStatus) {
   CurrentGeneration: (int64) 0,
   Phase: (cluster.ClusterPhase) (len=6) "normal",
   Master: (string) (len=8) "b6656606"
  }
 }),
 Keepers: (cluster.Keepers) (len=2) {
  (string) (len=8) "keeper_2": (*cluster.Keeper)(0xc420375650)({
   UID: (string) (len=8) "keeper_2",
   Generation: (int64) 1,
   ChangeTime: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
   Spec: (*cluster.KeeperSpec)(0xe2a5e8)({
   }),
   Status: (cluster.KeeperStatus) {
    Healthy: (bool) true,
    LastHealthyTime: (time.Time) 2017-11-06 13:29:56.528169724 +0000 UTC,
    BootUUID: (string) (len=36) "e50bdbe1-f0ae-43b9-9f70-d154f5d7f0f9"
   }
  }),
  (string) (len=8) "keeper_1": (*cluster.Keeper)(0xc4203755e0)({
   UID: (string) (len=8) "keeper_1",
   Generation: (int64) 1,
   ChangeTime: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
   Spec: (*cluster.KeeperSpec)(0xe2a5e8)({
   }),
   Status: (cluster.KeeperStatus) {
    Healthy: (bool) true,
    LastHealthyTime: (time.Time) 2017-11-06 13:29:56.528171374 +0000 UTC,
    BootUUID: (string) (len=36) "222a167b-762d-429b-9bb7-c2b2877761e5"
   }
  })
 },
 DBs: (cluster.DBs) (len=2) {
  (string) (len=8) "539d747e": (*cluster.DB)(0xc4201ba270)({
   UID: (string) (len=8) "539d747e",
   Generation: (int64) 2,
   ChangeTime: (time.Time) 2017-11-06 07:07:28.711399823 +0000 UTC,
   Spec: (*cluster.DBSpec)(0xc4201e33f0)({
    KeeperUID: (string) (len=8) "keeper_2",
    RequestTimeout: (cluster.Duration) 10s,
    MaxStandbys: (uint16) 20,
    SynchronousReplication: (bool) false,
    UsePgrewind: (bool) false,
    AdditionalWalSenders: (uint16) 5,
    InitMode: (cluster.DBInitMode) (len=4) "none",
    NewConfig: (*cluster.NewConfig)(<nil>),
    PITRConfig: (*cluster.PITRConfig)(<nil>),
    PGParameters: (cluster.PGParameters) (len=11) {
     (string) (len=10) "lc_numeric": (string) (len=10) "en_US.utf8",
     (string) (len=14) "shared_buffers": (string) (len=5) "128MB",
     (string) (len=8) "timezone": (string) (len=3) "UTC",
     (string) (len=12) "log_timezone": (string) (len=3) "UTC",
     (string) (len=15) "max_connections": (string) (len=3) "100",
     (string) (len=9) "datestyle": (string) (len=8) "iso, mdy",
     (string) (len=26) "default_text_search_config": (string) (len=18) "pg_catalog.english",
     (string) (len=26) "dynamic_shared_memory_type": (string) (len=5) "posix",
     (string) (len=11) "lc_messages": (string) (len=10) "en_US.utf8",
     (string) (len=11) "lc_monetary": (string) (len=10) "en_US.utf8",
     (string) (len=7) "lc_time": (string) (len=10) "en_US.utf8"
    },
    PGHBA: ([]string) <nil>,
    Role: (common.Role) (len=7) "standby",
    FollowConfig: (*cluster.FollowConfig)(0xc4204f0120)({
     Type: (cluster.FollowType) (len=8) "internal",
     DBUID: (string) (len=8) "b6656606",
     StandbySettings: (*cluster.StandbySettings)(<nil>)
    }),
    Followers: ([]string) {
    },
    IncludeConfig: (bool) false,
    SynchronousStandbys: ([]string) <nil>
   }),
   Status: (cluster.DBStatus) {
    Healthy: (bool) false,
    CurrentGeneration: (int64) 0,
    ListenAddress: (string) (len=45) "stolon-keeper-2-apigateway-dsh.marathon.mesos",
    Port: (string) (len=4) "5432",
    SystemID: (string) (len=19) "6485194152724537395",
    TimelineID: (uint64) 1,
    XLogPos: (uint64) 51420648,
    TimelinesHistory: (cluster.PostgresTimelinesHistory) <nil>,
    PGParameters: (cluster.PGParameters) (len=11) {
     (string) (len=26) "dynamic_shared_memory_type": (string) (len=5) "posix",
     (string) (len=11) "lc_messages": (string) (len=10) "en_US.utf8",
     (string) (len=11) "lc_monetary": (string) (len=10) "en_US.utf8",
     (string) (len=12) "log_timezone": (string) (len=3) "UTC",
     (string) (len=8) "timezone": (string) (len=3) "UTC",
     (string) (len=14) "shared_buffers": (string) (len=5) "128MB",
     (string) (len=9) "datestyle": (string) (len=8) "iso, mdy",
     (string) (len=26) "default_text_search_config": (string) (len=18) "pg_catalog.english",
     (string) (len=10) "lc_numeric": (string) (len=10) "en_US.utf8",
     (string) (len=7) "lc_time": (string) (len=10) "en_US.utf8",
     (string) (len=15) "max_connections": (string) (len=3) "100"
    },
    SynchronousStandbys: ([]string) {
    },
    OlderWalFile: (string) (len=24) "000000010000000000000002"
   }
  }),
  (string) (len=8) "b6656606": (*cluster.DB)(0xc4201ba410)({
   UID: (string) (len=8) "b6656606",
   Generation: (int64) 3,
   ChangeTime: (time.Time) 2017-11-06 07:07:13.638436918 +0000 UTC,
   Spec: (*cluster.DBSpec)(0xc4201e34a0)({
    KeeperUID: (string) (len=8) "keeper_1",
    RequestTimeout: (cluster.Duration) 10s,
    MaxStandbys: (uint16) 20,
    SynchronousReplication: (bool) false,
    UsePgrewind: (bool) false,
    AdditionalWalSenders: (uint16) 5,
    InitMode: (cluster.DBInitMode) (len=4) "none",
    NewConfig: (*cluster.NewConfig)(<nil>),
    PITRConfig: (*cluster.PITRConfig)(<nil>),
    PGParameters: (cluster.PGParameters) (len=11) {
     (string) (len=9) "datestyle": (string) (len=8) "iso, mdy",
     (string) (len=26) "default_text_search_config": (string) (len=18) "pg_catalog.english",
     (string) (len=26) "dynamic_shared_memory_type": (string) (len=5) "posix",
     (string) (len=11) "lc_messages": (string) (len=10) "en_US.utf8",
     (string) (len=11) "lc_monetary": (string) (len=10) "en_US.utf8",
     (string) (len=10) "lc_numeric": (string) (len=10) "en_US.utf8",
     (string) (len=7) "lc_time": (string) (len=10) "en_US.utf8",
     (string) (len=12) "log_timezone": (string) (len=3) "UTC",
     (string) (len=15) "max_connections": (string) (len=3) "100",
     (string) (len=14) "shared_buffers": (string) (len=5) "128MB",
     (string) (len=8) "timezone": (string) (len=3) "UTC"
    },
    PGHBA: ([]string) <nil>,
    Role: (common.Role) (len=6) "master",
    FollowConfig: (*cluster.FollowConfig)(<nil>),
    Followers: ([]string) (len=1 cap=4) {
     (string) (len=8) "539d747e"
    },
    IncludeConfig: (bool) false,
    SynchronousStandbys: ([]string) <nil>
   }),
   Status: (cluster.DBStatus) {
    Healthy: (bool) true,
    CurrentGeneration: (int64) 3,
    ListenAddress: (string) (len=45) "stolon-keeper-1-apigateway-dsh.marathon.mesos",
    Port: (string) (len=4) "5432",
    SystemID: (string) (len=19) "6485194152724537395",
    TimelineID: (uint64) 1,
    XLogPos: (uint64) 51428064,
    TimelinesHistory: (cluster.PostgresTimelinesHistory) <nil>,
    PGParameters: (cluster.PGParameters) (len=11) {
     (string) (len=26) "default_text_search_config": (string) (len=18) "pg_catalog.english",
     (string) (len=11) "lc_monetary": (string) (len=10) "en_US.utf8",
     (string) (len=15) "max_connections": (string) (len=3) "100",
     (string) (len=14) "shared_buffers": (string) (len=5) "128MB",
     (string) (len=9) "datestyle": (string) (len=8) "iso, mdy",
     (string) (len=26) "dynamic_shared_memory_type": (string) (len=5) "posix",
     (string) (len=11) "lc_messages": (string) (len=10) "en_US.utf8",
     (string) (len=10) "lc_numeric": (string) (len=10) "en_US.utf8",
     (string) (len=7) "lc_time": (string) (len=10) "en_US.utf8",
     (string) (len=12) "log_timezone": (string) (len=3) "UTC",
     (string) (len=8) "timezone": (string) (len=3) "UTC"
    },
    SynchronousStandbys: ([]string) {
    },
    OlderWalFile: (string) (len=24) "000000010000000000000001"
   }
  })
 },
 Proxy: (*cluster.Proxy)(0xc42044bbc0)({
  UID: (string) "",
  Generation: (int64) 37,
  ChangeTime: (time.Time) 2017-11-06 07:08:44.120146771 +0000 UTC,
  Spec: (cluster.ProxySpec) {
   MasterDBUID: (string) (len=8) "b6656606",
   EnabledProxies: ([]string) (len=1 cap=4) {
    (string) (len=8) "4d8c962a"
   }
  },
  Status: (cluster.ProxyStatus) {
  }
 })
})

2017-11-06T13:29:59.251Z	[35mDEBUG[0m	keeper/keeper.go:932	db status	{"started": false}
2017-11-06T13:29:59.251Z	[34mINFO[0m	keeper/keeper.go:1298	database cluster not initialized
2017-11-06T13:29:59.251Z	[35mDEBUG[0m	keeper/keeper.go:1309	target role	{"targetRole": "standby"}
2017-11-06T13:29:59.251Z	[34mINFO[0m	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "b6656606"}
2017-11-06T13:29:59.251Z	[34mINFO[0m	keeper/keeper.go:1457	our db role is none

**Comment by sgotti** [comment]
@Krieke Is your data on a persistent storage? Looks like the keeper_2 postgres data is empty.

**Comment by Krieke** [comment]
@sgotti Yes the data directory for the keepers are mapped to an AWS EBS volume. It is normal that it is empty since it should synchronize with the Master. Not?

**Comment by Krieke** [comment]
@sgotti yes... there is an persistent volume and it contains data

**Comment by Krieke** [comment]
@sgotti What does actually the Generation:0 mean?

**Comment by Krieke** [comment]
Sorry.. closing was not the intention.

**Comment by sgotti** [comment]
@Krieke from the data looks like keeper2 was a standby and it was syncing but now the postgres directory is disappeared and the dbstate file is empty. So something strange happened. Are you sure the ebs volume is the same and it's not been substituted by an empty one?

Can you provide somewhere the keepers and sentinels logs?

**Comment by Krieke** [comment]
@sgotti I can provide you the log of the keepers and sentinals: but it is only for the last hour. Due to the full debug logging we have enabled for now (since stolon is only very recently a service we use) the logration for 9x2MB files is only 40 minutes. Since I am actually a developer I was during the incident in an architecture meeting... so logs are gone.

**Comment by Krieke** [comment]
@sgotti What I can see on AWS is that the EBS volumes were created with a difference of a few seconds. So not removed / re-created. So only the stolon-keeper-2 process could have cleaned the data at a given point in time. Is the only process that has access to the volume

**Comment by Krieke** [comment]
![image](https://user-images.githubusercontent.com/19797982/32458777-c8b4213c-c32d-11e7-9f0b-df32c78c3e04.png)

**Comment by Krieke** [comment]
@sgotti do you want the logs of the last 40 minutes? They propably don't give any input anymore about the cause that cleaned the data.  But on the other hand I should be able to startup a slave node not? So how can I restart my keeper-2 in a way that we have an working standby server? Also the answer on the meaning of "GENERATION"-id would be nice. Thx in advance

**Comment by sgotti** [comment]
@Krieke The last 40 minutes log won't be useful. I can't know what happened but the keeper will remove the data only if instructed to do so by the sentinel. If you haven't done anything to the cluster I can't imagine how this should have happened.

**Comment by Krieke** [comment]
@sgotti I can assure you that I haven't done anything to the cluster. But ok.. it is what it is. How can I bring this keeper-2 up again?

**Comment by sgotti** [comment]
@Krieke if it happens again please keep and provide the keepers and sentinels logs.

Since #301 isn't merged you have various options:

* Stop the keeper,  add another keeper with a different uid,  set MaxStandbysPerSender to 1 and lower deadKeeperRemovalInterval to some seconds.
* Reinitialize the cluster with initmode = existing (see the doc)
* Manually rewrite the cluster data removing the keeper and related db (very dangerous).

**Comment by sgotti** [comment]
@Krieke keeper remove command has been merged in #383. I'm going to close this. Please let us know if you encounter the same problem providing the related logs.
