### ISSUE TITLE
Question: Memory overhead

### ISSUE THREAD

**Issue by malejpavouk** [sorintlab/stolon#382]
Hi,

I read through the documentation, but unfortunatelly I have not found what is the memory overhead per instance of sentinel and proxy? We have a memory sensitive environment and using as little memory as possible is crucial for us.

Question 2: The minimal number of proxies and sentinels for HA is 2 (each) I suppose?

Thanks!

Pavel

**Comment by sgotti** [comment]
@malejpavouk In future please ask such questions using the mailing list or the gitter channel: https://github.com/sorintlab/stolon#contacts

> I read through the documentation, but unfortunatelly I have not found what is the memory overhead per instance of sentinel and proxy? We have a memory sensitive environment and using as little memory as possible is crucial for us.

We don't have scientific data so you should check it by yourself testing and monitoring the processes. The stolon processes don't allocate much memory and don't have spikes so the memory allocated is the one needed by the go runtime plus a little bit (on my machine the keeper uses 15MB and the sentinel and proxy 10MB). Or given in other words: probably postgres requires much more memory than stolon.

> Question 2: The minimal number of proxies and sentinels for HA is 2 (each) I suppose?

yes

**Comment by malejpavouk** [comment]
Thanks for a quick answer!
