### ISSUE TITLE
Increase postgresql max_connections in stolon keeper permanently

### ISSUE THREAD

**Issue by alamgn** [sorintlab/stolon#388]
Hello,

How do I increase postgresql max_connections in stolon keeper permanently? because postgresql.conf file always deleted when keeper node restoring database.

Best Regads,
Alam

**Comment by sgotti** [comment]
Take a look at the doc: https://github.com/sorintlab/stolon/blob/master/doc/postgres_parameters.md

For such kind of questions please use the mailing list or the gitter channel next time. Thanks.
