### ISSUE TITLE
Support for multiple masters

### ISSUE THREAD

**Issue by thedrow** [sorintlab/stolon#40]
If stolon already supports multiple masters, let's specify that in the README.
If it doesn't let's discuss if we want to add it.

**Comment by sgotti** [comment]
@thedrow. Right. We should probably clarify this in the doc.

Stolon was designed as a clustering system that uses postgresql streaming replication to have data replicated on multiple postgresql instances. It ensures that all the members converge to the calculated cluster view. The stolon proxies enforces that all the client connects to the right master trying to avoiding partitioning scenarios where some clients will try to write to an "old" (unelected) master.
But it's not a replication system on top of postgresql like pgpool-II. For this reason there can be only one master per cluster.

**Comment by thedrow** [comment]
The problem I have with pgpool is that it's static and doesn't use service discovery to discover new masters.
As I already said in #39 I'd like to replace it with a modern component.
Feel free to close this if we're not going to add support for multiple masters right now but I do see a potential for a one stop shop here.

**Comment by sgotti** [comment]
@thedrow stolon achieve HA using native postgreSQL streaming replication (async and sync). Doing something like pgpool-II is a completely different replication mode and architecture. It'll be better to contribute and improve pgpool-II (if possible) or create another project.
