### ISSUE TITLE
pg_basebackup: could not connect to server: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by patsevanton** [sorintlab/stolon#409]
Hello!
I try run cluster stolon winth PostgreSQL 9.6 on CentOS 7
Version:
CentOS Linux release - 7.4.1708 (Core)
etcd - 3.2.0-0.1.rc1.el7.centos
stolon - 0.7.0-1.fec5140.el7.centos

Please add boot order run command to https://github.com/sorintlab/stolon/blob/master/doc/simplecluster.md
maybe I'm doing something wrong
Thank you.

1) stolonctl --cluster-name stolon-cluster --store-backend=etcd init - run on First server
2) stolon-sentinel --cluster-name stolon-cluster --store-backend=etcd - run on every servers
3) stolon-keeper --cluster-name stolon-cluster --store-backend=etcd --uid postgres0 --data-dir 9.6/data/postgres0 --pg-su-password=supassword --pg-repl-username=repluser --pg-repl-password=replpassword --pg-listen-address=127.0.0.1 - run on First server
4) stolon-keeper --cluster-name stolon-cluster --store-backend=etcd --uid postgres1 --data-dir data/postgres1 --pg-su-password=supassword --pg-repl-username=repluser --pg-repl-password=replpassword --pg-listen-address=127.0.0.1 --pg-port 5435

> 
> 2018-01-13T19:28:22.699+0300	INFO	keeper/keeper.go:1672	exclusive lock on data dir taken
> 2018-01-13T19:28:22.699+0300	INFO	keeper/keeper.go:442	keeper uid	{"uid": "postgres1"}
> 2018-01-13T19:28:22.707+0300	INFO	postgresql/postgresql.go:264	stopping database
> pg_ctl: directory "/var/lib/pgsql/data/postgres1/postgres" is not a database cluster directory
> 2018-01-13T19:28:22.727+0300	INFO	keeper/keeper.go:881	our db boot UID is different than the cluster data one, waiting for it to be updated	{"bootUUID": "7c440b26-69ab-480b-b5cf-8c9c7e6195fc", "clusterBootUUID": "8a449b52-4782-4305-ad57-e9fd19088547"}
> 2018-01-13T19:28:22.727+0300	INFO	postgresql/postgresql.go:264	stopping database
> pg_ctl: directory "/var/lib/pgsql/data/postgres1/postgres" is not a database cluster directory
> 2018-01-13T19:28:27.740+0300	ERROR	keeper/keeper.go:896	db failed to initialize or resync
> 2018-01-13T19:28:27.740+0300	INFO	postgresql/postgresql.go:264	stopping database
> pg_ctl: directory "/var/lib/pgsql/data/postgres1/postgres" is not a database cluster directory
> 2018-01-13T19:28:27.753+0300	INFO	keeper/keeper.go:949	current db UID different than cluster data db UID	{"db": "", "cdDB": "e55b4a59"}
> 2018-01-13T19:28:27.754+0300	INFO	keeper/keeper.go:1103	resyncing the database cluster
> 2018-01-13T19:28:27.758+0300	INFO	keeper/keeper.go:1132	database cluster not initialized
> 2018-01-13T19:28:27.759+0300	INFO	keeper/keeper.go:744	syncing from followed db	{"followedDB": "ec94e66c", "keeper": "postgres0"}
> 2018-01-13T19:28:27.759+0300	INFO	postgresql/postgresql.go:726	running pg_basebackup
> pg_basebackup: could not connect to server: could not connect to server: Connection refused
> 	Is the server running on host "127.0.0.1" and accepting
> 	TCP/IP connections on port 5432?

> 
> 2018-01-13T19:25:43.663+0300	INFO	sentinel/sentinel.go:773	db initialized	{"db": "ec94e66c", "keeper": "postgres0"}
> 2018-01-13T19:27:49.491+0300	INFO	sentinel/sentinel.go:1287	added new standby db	{"db": "e55b4a59", "keeper": "postgres1"}
> 2018-01-13T19:27:54.525+0300	WARN	sentinel/sentinel.go:298	received db state for unexpected db uid	{"receivedDB": "", "db": "e55b4a59"}
> 2018-01-13T19:28:09.629+0300	ERROR	sentinel/sentinel.go:287	no keeper info available	{"db": "e55b4a59", "keeper": "postgres1"}

**Comment by sgotti** [comment]
@patsevanton simple cluster, as explained at the start, is just for a test cluster on ONE host. If you want to test on multiple hosts you have to change at least the `--pg-listen-address` to a reachable ip. BTW there's no start/restart order, the cluster will work anyway regardless if the start order.

If you have additional questions like these, since they don't look like issues, please write to the gitter channel or the mailing list as specified when you open an issue.

**Comment by patsevanton** [comment]
I am sorry.
I edit 127.0.0.1 to 10.233.60.3X and error fixed.
Thank you
