### ISSUE TITLE
Option to choose the StoreBasePath

### ISSUE THREAD

**Issue by kemko** [sorintlab/stolon#424]
### Submission type

 - Request for enhancement (RFE)

### Environment
At least stolon with etcdv3 backend

#### Stolon version
0.8.0

### Enhancement Description
Add an option to choose the StoreBasePath. For example, confd, for now, can't work with keys without leading slash (https://github.com/kelseyhightower/confd/issues/657). I'm just runned stolon locally yesterday and can't yet provide less specific use cases for this RFE unfortunately.

P.S. I have a bad knowledge of Go, so I can't provide PR.

**Comment by sgotti** [comment]
@kemko I create PR #425 . Do you have time to test it?
