### ISSUE TITLE
Advice for an HA at the proxy level

### ISSUE THREAD

**Issue by jf-prevost** [sorintlab/stolon#451]
### Submission type

 - Setup advice

### Environment
Ubuntu 16.04
Openstack Mitaka

#### Stolon version
0.9.0

#### Additional environment information if useful to understand the bug
Deployment of a 3 x 3 agents/VM cluster (3 keepers, 3sentinels and 3 proxies) + 1 VM hosting etcd.

### Enhancement Description

I'm currently setting up a stolon cluster on Openstack but would like to have an HA feature at the proxy level (with virtual IP).

In fact, as far as I understood the way the stolon cluster works, the DB (postgres) availability is transparent for a client.
But this client needs to know the proxy IP address to access postgresql.
If the involved proxy dies, the client will have to know and use another proxy and thus the other proxy's IP address to access postgresql again.

My first guess was to set up a neutron load-balancer (neutron lbaas) in front of the proxies but it turned out to not being satisfying and IMHO a bit overkill (proxy the access to a proxy ...).

What would the best bet to achieve an HA service on the proxies ? (clearly through an unique IP address)

I thought about setting a Keepalived service on the 3 stolon proxies, would that be the right solution ?
Which technology would you advise ?

Thank you for your advice.

**Comment by sgotti** [comment]
@jf-prevost Since the answer and the discussion are already on going on [gitter](https://gitter.im/sorintlab/stolon?at=5a969e4c6f8b4b9946d162a2) let's close this and continue there. Thanks.
