### ISSUE TITLE
cannot find package "context" in any of

### ISSUE THREAD

**Issue by wuhaowen56** [sorintlab/stolon#465]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

**Comment by sgotti** [comment]
https://github.com/sorintlab/stolon#build you need at lest go 1.9

**Comment by sgotti** [comment]
@wuhaowen56 I'm going to close this since it not really an issue.

**Comment by wuhaowen56** [comment]
ok thank you!

At 2018-04-09 14:43:19, "Simone Gotti" <notifications@github.com> wrote:


@wuhaowen56 I'm going to close this since it not really an issue.
