### ISSUE TITLE
Service discovery with kuberentes backend 

### ISSUE THREAD

**Issue by Flowkap** [sorintlab/stolon#466]
### Submission type

 - Request for enhancement (RFE) (possibly a bug though)

#### Stolon version

v0.10 with kubernetes backend

#### Additional environment information if useful to understand the bug

The service discovery does not work properly if the components app label contain a release info (like with helm deploys) Refer to: 

https://github.com/lwolf/stolon-chart/issues/18

https://github.com/sorintlab/stolon/pull/433#issuecomment-377169416

In https://github.com/sorintlab/stolon/pull/433#issuecomment-377220731 it seems as if only the component and cluster-name label should be considered but as mentioned https://github.com/sorintlab/stolon/commit/38ae6b13b5e161a5bfe0fbe01084ca060eaf2e76#diff-95cdd374e9440fde010ff35d65f8cf3fR54 states that the app labels must match exactly as well (and that is what I observed as well.) 

### Expected behaviour you didn't see

Only select matches based upon the component and cluster-name labels NOT the app label as it might be containing release infos.

### Unexpected behaviour you saw

Components can't start because no data assigned to them.

### Steps to reproduce the problem

Change app label of keepers, sentinels and proxy pods.

**Comment by sgotti** [comment]
@Flowkap I wasn't aware that app label must respect special format. This is probably just an helm practice?

Are you suggesting to change the `app` label name to `component`? 

Can you open a PR trying to explain what you are proposing since this isn't clear to me.

BTW The current implementation is just strict, we can change it to use custom selectors.

**Comment by Flowkap** [comment]
No, stolon requires the app-label to exact "stolon-keeper" for a keeper. So it can'T be fully qalified if you're deploying multiple stolo in one cluster like "stolon-cluster1-keeper" or similar. 

We worked around this in the chart but this is a flaw we want to get fixed. As far as I understand the sentinels query the pods by app label as well as the stolon-chart label. This should be a different label (like component + stolon-chart) instead so that app labels can be anything.

**Comment by sgotti** [comment]
@Flowkap I think we are saying the same. What's you proposed label name instead of `app`(`stolon-component`, etc...)?

**Comment by Flowkap** [comment]
Ah I see. Sorry. I thought that the component label from the chart is originated in your example. but it isn'T

If "component " (like currently also set in the chart) is too generic for your taste "stolon-component" would be perfect addition to stolon-cluster label and both should be unique in all Scenarios combined.

**Comment by sgotti** [comment]
@Flowkap The sentinel queries by `app` label (that must be set to the component type: `stolon-keeper`, `stolon-sentinel`, `stolon-proxy`) and by `stolon-cluster` set to the stolon cluster name.

See the doc: https://github.com/sorintlab/stolon/blob/master/doc/architecture.md#kubernetes-store-backend

So changing `app` to `component` will be enough for you? I did it here in this commit https://github.com/sgotti/stolon/commit/9428b6440ecdc62b7436681501758f3f0f54ea10

**Comment by Flowkap** [comment]
I think this looks good. 

That way the full qualified app label can be used again. 

As component itself is a helm standard label (but we would use it in accordance I think) this should be fine. (https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md )

We'd just nee dto change them to component: stolon-keeper instead of component: keeper and so on.

What do you think @lwolf?

**Comment by sgotti** [comment]
@Flowkap @lwolf I'll create the PR tomorrow and when merged we'll do a release with few other fixes.
