### ISSUE TITLE
pg_rewind is failed when postgresql.auto.conf is symlink

### ISSUE THREAD

**Issue by deepdivenow** [sorintlab/stolon#468]
On stolon cluster after init IT create symlink postgresql.auto.conf -> /dev/null.
This symlink file does not allow normal execution of pg_rewind:

$ pg_rewind -D . --source-server='host=192.168.2.11 port=5432 user=postgres password=***** '
servers diverged at WAL position 0/D000060 on timeline 5
rewinding from last common checkpoint at 0/C000098 on timeline 5

"./postgresql.auto.conf" is not a regular file
Failure, exiting

$ rm postgresql.auto.conf 
$ pg_rewind -D . --source-server='host=192.168.2.11 port=5432 user=postgres password=***** '
servers diverged at WAL position 0/D000060 on timeline 5
rewinding from last common checkpoint at 0/C000098 on timeline 5
Done!

Can you delete this symlink (if it exists and set to /dev/null) before run pg_rewind and create it after pg_rewind is has done.

$ stolonctl version
stolonctl version v0.10.0

$ /usr/pgsql-9.5/bin/pg_rewind --version
pg_rewind (PostgreSQL) 9.5.12

**Comment by sgotti** [comment]
@deepdivenow good catch. So is it enough to remove it on the target server also if it's a symlink to /dev/null on the source server?

**Comment by deepdivenow** [comment]
Problem exist only with symlink (postgresql.auto.conf -> /dev/null) on target system.
If symlink(postgresql.auto.conf -> /dev/null) exists on source system pg_rewind work fine.

**Comment by sgotti** [comment]
@deepdivenow Thanks, created PR #470
