### ISSUE TITLE
requested WAL segment has already been removed

### ISSUE THREAD

**Issue by alesz** [sorintlab/stolon#476]
### Submission type

 - Bug report

### Environment
- RHEL 7.5
- PGSQL 10.3

#### Stolon version
0.10.0

### Expected behaviour you didn't see
Slave node synchronizes successfully

### Unexpected behaviour you saw
`pg_basebackup` fails due to WAL segments already missing by the time it is done.

### Steps to reproduce the problem

Stolon executes pg_basebackup as:
```
/usr/pgsql-10/bin/pg_basebackup -R -Xf -D /var/lib/pgsql/10/data/postgres -d application_name=stolon_33a935d2 options=-c\ synchronous_commit=off sslmode=disable user=repluser host=x.x.x.x port=5431
```

According to [docs](https://www.postgresql.org/docs/10/static/app-pgbasebackup.html), WAL segments will rotate even if replication haven't caught up when using `-Xf` flag.

`-Xs` flag should fix the issue.

**Comment by sgotti** [comment]
@alesz I think we should switch to wal streaming in pg_basebackup. This will require doubling the number of wal receivers to be on the safe side.

If I got the doc correctly in postgres 10 a temporary replication slot will be created if `--slot` is not provided. We could directly provide `--slot` to make it work also on older version but a side effect will be that sometimes the initial pg_basebackup will fail if the slot is not yet created on the source instance by the keeper, but a second try will succeed (so user will see a pg_basebackup error but this is better that not using a replication slot).

There is another similar issues #372

**Comment by sgotti** [comment]
Create PR #477
