### ISSUE TITLE
New & clean cluster doesn't elect a sentinel leader: election loop error	{"error": "102: Not a file (/stolon/cluster/kube-stolon/sentinel-leader) [9079]"}

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#478]
### Submission type

 - Bug report

### Environment
Kubernetes 1.7.11

#### Stolon version
Image: sorintlab/stolon:master-pg9.6
Command:
      /bin/bash
      -ec
      exec gosu stolon stolon-sentinel

### Expected behaviour you didn't see
```
=== Active sentinels ===

ID              LEADER
yyyyyyyyy        false
xxxxxxxxx        true
```
& 
No errors in sentinel log.

### Unexpected behaviour you saw

No sentinel leader is elected.
Sentinel 0 without errors:

```
.
.
.
2018-04-23T11:35:52.604Z	DEBUG	sentinel/sentinel.go:1646	cd dump: (*cluster.ClusterData)(0xc420267620)({
.
.
.
2018-04-23T11:35:52.604Z	DEBUG	sentinel/sentinel.go:141	sentinelInfo dump	{"sentinelInfo": {"UID":"3144ea59"}}
2018-04-23T11:35:52.619Z	DEBUG	sentinel/sentinel.go:1674	keepersInfo dump: (cluster.KeepersInfo) (len=2) {
.
.
.
2018-04-23T11:35:52.654Z	DEBUG	sentinel/sentinel.go:287	received db state	{"db": "2942f167", "keeper": "keeper0"}
2018-04-23T11:35:52.654Z	DEBUG	sentinel/sentinel.go:287	received db state	{"db": "5bc6776a", "keeper": "keeper1"}
2018-04-23T11:35:52.654Z	DEBUG	sentinel/sentinel.go:1709	newcd dump after updateKeepersStatus: (*cluster.ClusterData)(0xc4203be5a0)({
.
.
.
2018-04-23T11:35:52.657Z	DEBUG	sentinel/sentinel.go:980	db dump: (*cluster.DB)(0xc4200689c0)({
.
.
.
2018-04-23T11:35:52.657Z	DEBUG	sentinel/sentinel.go:1174	standbys states	{"good": 1, "failed": 0, "converging": 0}
2018-04-23T11:35:52.658Z	DEBUG	sentinel/sentinel.go:1718	newcd dump after updateCluster: (*cluster.ClusterData)(0xc4203bf560)({
.
.
.
```

Sentinel 1 with error "**_election loop error	{"error": "102: Not a file (/stolon/cluster/kube-stolon/sentinel-leader) [9079]"}_**":
```
.
.
.
2018-04-23T11:11:07.409Z	DEBUG	sentinel/sentinel.go:152	sentinelInfo dump	{"sentinelInfo": {"UID":"95fc1b83"}}
2018-04-23T11:11:07.429Z	DEBUG	sentinel/sentinel.go:1629	keepersInfo dump: (cluster.KeepersInfo) (len=2) {
.
.
.
2018-04-23T11:11:11.267Z	INFO	sentinel/sentinel.go:107	Trying to acquire sentinels leadership
2018-04-23T11:11:11.367Z	ERROR	sentinel/sentinel.go:127	election loop error	{"error": "102: Not a file (/stolon/cluster/kube-stolon/sentinel-leader) [9079]"}
2018-04-23T11:11:12.445Z	DEBUG	sentinel/sentinel.go:1599	cd dump: (*cluster.ClusterData)(0xc420413bc0)({
.
.
.
2018-04-23T11:11:12.445Z	DEBUG	sentinel/sentinel.go:152	sentinelInfo dump	{"sentinelInfo": {"UID":"95fc1b83"}}
2018-04-23T11:11:12.482Z	DEBUG	sentinel/sentinel.go:1629	keepersInfo dump: (cluster.KeepersInfo) (len=2) {
.
.
.
```

Cluster Status:
```
=== Active sentinels ===

ID              LEADER
3144ea59        false
95fc1b83        false

=== Active proxies ===

ID
2c8985c5
cda27222

=== Keepers ===

UID     HEALTHY PG LISTENADDRESS        PG HEALTHY      PG WANTEDGENERATION     PG CURRENTGENERATION
keeper0 true    172.16.128.7:5432       true            2                       2
keeper1 true    172.16.96.2:5432        true            3                       3

=== Cluster Info ===

Master: keeper1

===== Keepers/DB tree =====

keeper1 (master)
└─keeper0
```

### Steps to reproduce the problem

Launch a new stolon cluster.

**Comment by sgotti** [comment]
@guillelb What kind of store are you using? (etcdv2, etcdv3, kubernetes) etc...?

That errors (that never happended to me) looks like an etcd error. If so you should try to see if inside etcd `/stolon/cluster/kube-stolon/sentinel-leader` exists and its contents to see why this error is happening.

**Comment by guillelb** [comment]
```
# etcdctl --version
etcdctl version: 3.3.0
API version: 2
```

**Comment by guillelb** [comment]
/stolon/cluster/kube-stolon/sentinel-leader  lives in ETCD:
```
# etcdctl ls /stolon/cluster/kube-stolon/
 /stolon/cluster/kube-stolon/clusterdata
 /stolon/cluster/kube-stolon/sentinel-leader
 /stolon/cluster/kube-stolon/sentinels
 /stolon/cluster/kube-stolon/proxies
 /stolon/cluster/kube-stolon/keepers
```

But It appear to be a directory:
```
/ # etcdctl get /stolon/cluster/kube-stolon/sentinel-leader
/stolon/cluster/kube-stolon/sentinel-leader: is a directory
```

How is this possible?

**Comment by sgotti** [comment]
@guillelb I'm quite sure that the stolon code will never create a directory so it should be something external to stolon that did this (do you have some external commands doing something on etcd?).

Are you able to reproduce it?

**Comment by sgotti** [comment]
@guillelb Nevermind. I think this is a bug introduced when adding the k8s store backend that added another level to the sentinel key.

Looks like you're running 2 different versions of the sentinel (or the error won't happen). Since you're using the same label `master-pg96)`one of your k8s node didn't fetched the latest version. Remember that that stolon images are only an example and not for production runs.

I will open a PR. I will also suggest you to use the etcdv3 store backend since it's the new de facto api for etcdv3.

**Comment by guillelb** [comment]
Thank you @sgotti for your quick answers.

My ETCD db is only used by Stolon components, I guarantee you that.

It seems to be that It is running two versions of the sentinels docker image:

K8S Machine 1:
```
# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
sorintlab/stolon           master-pg9.6        24e6f9353ef2        4 months ago        359MB
```

K8S Machine 2:
```
# docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
sorintlab/stolon            master-pg9.6        635b16a074ed        2 months ago        375MB
```

Then, 

1. If I can not use the images `master-pg96`, which of these image should I use for my environment?

2. As I wrote previously, I use `etcdctl version: 3.3.0`,  but without me touching anything `API version: 2` is active. How should I tell to Stolon or to ETCD to use API v3 ?

**Comment by sgotti** [comment]
PR #479

**Comment by sgotti** [comment]
@guillelb The tag `master-pg96` is the same for every built image from the current master, so their content will change. These are images provided for the example. In a production cluster you should build you own image and tag them differently for every new built image so kubernetes know that it should pull the new image or you can force k8s to always pull the image also with the same tag (see k8s docs).
 

> If I can not use the image with TAG master-pg96, which of these image should I use for my environment?

You should build and tag your own image with your customizations. If you want to use the example images see above.

> As I wrote previously, I use etcdctl version: 3.3.0, but without me touching anything API version: 2 is active. How should I tell to Stolon or to ETCD to use API v3 ?

For stolon pass the right store backend `--store-backend=etcdv3` or with the right env variable in the k8s yaml definition. For etcd set ETCDCTL_API=3. Remember that etcd has 2 totally distinct stores so the v3 api won't see the v2 data and viceversa. If you're creating a new stolon cluster that's ok, if you want to migrate an existing stolon cluster from etcdv2 to v3 you should copy the clusterdata file `/stolon/cluster/$CLUSTERNAME/clusterdata` to the right path in the etcdv3 api or you should reinitialize the cluster using an existing keeper (see the doc for cluster initialization with mode set to existing).

**Comment by guillelb** [comment]
@sgotti Thank you for your help.
