### ISSUE TITLE
When ETCD /.../member/snap/db reaches 2GB (in ~8 days) stolon cluster goes down

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#485]
Hello:

When ETCD /.../member/snap/db reaches 2GB (in ~8 days) stolon cluster goes down, is this normal?

I am using "etcdv3"  as  STKEEPER_STORE_BACKEND.

**Comment by sgotti** [comment]
@guillelb I imagine that etcd isn't working right. If so if etcd has some problems stolon will have problems. So you should take a look at the etcd status and debug what's the problem. Closing since it's not related to stolon. Reopen if you think is a stolon issue.
