### ISSUE TITLE
Let the user define server parameters in cluster config.

### ISSUE THREAD

**Issue by sgotti** [sorintlab/stolon#49]
Excluding the parameters controlled by the keeper, an user should be able to set the other server parameters.

We'll need to understand if and how to handle wrong parameters (unknown or with bad value) and rollback to the previous configuration since a reload will ignore them but a restart or new start will fail.

**Comment by jberkus** [comment]
An alternative would be for stolon to support postgresql conf.d directory by default.  Then users could just drop whatever configuration files into that directory that they wanted, without involving stolon at all.  This would be better for integration with systems like Puppet, Chef, etc.

**Comment by sgotti** [comment]
@jberkus Thanks for the suggestion! I think we can do like you described for some environments but it won't be the best/feasible way for others were instead a centralized control will be better.

Long response:

We thought about it. The main problem is, given the cloud nature of stolon, members can come and go, for example on kubernetes, it becomes difficult/anti-pattern to enter all the containers, change the config and reload.

Althought for static environments, that we'd like to support, this will be more practical. So I think we can give the users the power of doing both ways.

**Comment by sgotti** [comment]
@jberkus Created #85. It implements your suggestion of including a conf.d.

**Comment by jberkus** [comment]
Great!

So there's actually two circumstances where using a conf.d makes sense:

1. when new images are being partly provisioned using a CMF like Ansible. 
2. when the user defines fairly specific pg.conf settings in the image definition, but still wants Stolon to initdb.

**Comment by sgotti** [comment]
@jberkus Thanks. Does it looks good to you or do you see some improvements in it's behavior or in the docs?

**Comment by jberkus** [comment]
Description looks fine.  I haven't actually tried it yet.

**Comment by sgotti** [comment]
@jberkus Thanks. Commited and also added centralized postgres parameters (#95)
