### ISSUE TITLE
Error while deploying stolon

### ISSUE THREAD

**Issue by kiranmudemela** [sorintlab/stolon#491]
We see the following error logs

bash-3.2$ pwd
/Users/mac/stolon/examples/kubernetes/image/docker

bash-3.2$  make PGVERSION=9.6 TAG=stolon:master-pg9.6
sed -e "s/\${PGVERSION}/9.6/" Dockerfile.template > Dockerfile
docker build -t stolon:master-pg9.6 .
Sending build context to Docker daemon  4.096kB
Step 1/5 : FROM postgres:9.6
 ---> 9fda677631e8
Step 2/5 : RUN useradd -ms /bin/bash stolon
 ---> Using cache
 ---> 16d78b4f9a55
Step 3/5 : EXPOSE 5432
 ---> Using cache
 ---> f499c44ff1e9
Step 4/5 : ADD bin/stolon-keeper bin/stolon-sentinel bin/stolon-proxy bin/stolonctl /usr/local/bin/
ADD failed: stat /var/lib/docker/tmp/docker-builder940622277/bin/stolon-keeper: no such file or directory
make: *** [build] Error 1
bash-3.2$

**Comment by sgotti** [comment]
@kiranmudemela to build the image you have to first build stolon. And if you want to run it under k8s you should probably build it for linux. See the README.md.
