### ISSUE TITLE
stolon-sentinel: Missing environment variable description

### ISSUE THREAD

**Issue by nseyvet** [sorintlab/stolon#523]
### Submission type

 - Request for enhancement (RFE)

#### Stolon version
N/A.
### Expected behaviour you didn't see
Documentation on exported variables.
### Enhancement Description
Add a description to stolon-sentinel that exemplify that most options can be exported as variables. While used in the helm charts this is not documented explicitly.

**Comment by sgotti** [comment]
Closing for the same reason of #525
