### ISSUE TITLE
stolon-proxy: missing environment vars description

### ISSUE THREAD

**Issue by nseyvet** [sorintlab/stolon#525]
### Submission type

 - Request for enhancement (RFE)

### Enhancement Description
Add a description to stolon-proxy that exemplify that most options can be exported as variables. While used in the helm charts this is not documented explicitly.

**Comment by sgotti** [comment]
@nseyvet This is already documented here: https://github.com/sorintlab/stolon/blob/master/doc/commands_invocation.md

**Comment by sgotti** [comment]
closing since already documented [here](https://github.com/sorintlab/stolon/blob/master/doc/commands_invocation.md). As discussed on [gitter](https://gitter.im/sorintlab/stolon?at=5b39e7a933b0282df4f8a35a) feel free to create a PR with your proposed documentation changes.
