### ISSUE TITLE
Update tools and other documentation regarding --metrics-listen-address

### ISSUE THREAD

**Issue by tdddblog** [sorintlab/stolon#533]
--metrics-listen-address and metrics feature is not described anywhere in documentation.

**Comment by sgotti** [comment]
@tdddblog I updated the generated doc in https://github.com/sorintlab/stolon/tree/master. Currently the exported metrics are only the base one provided by the prometheus golang client. Please open a PR if you meant to add additional documentation.

**Comment by sgotti** [comment]
Closing since the docs has been updated.
