### ISSUE TITLE
Allow fetching of WALs using both restore_command and streaming replication

### ISSUE THREAD

**Issue by jonjomckay** [sorintlab/stolon#538]
### Submission type

 - Request for enhancement (RFE)

#### Stolon version
v0.12.0
### Enhancement Description
It would be incredibly helpful to allow fetching of WALs using both the `restore_command` and streaming replication (`primary_conninfo`) for standby clusters.

Currently, Stolon only supports fetching WALs using streaming replication after the initial PITR, but PostgreSQL itself supports combining both inside the `recovery.conf`. It's helpful for people who already have their WALs shipped to somewhere external (e.g. using wal-e), and don't want to (or can't) duplicate those WALs on the master using replication slots.

**Comment by sgotti** [comment]
@jonjomckay I implemented this in #543 . Do you have time test that PR to see if this works correctly for you and fits your needs? (I added an integration tests that creates a standby cluster recovering only using the archived wals).

Please note that `standbySettings` has been renamed to `standbyConfig` and it accepts two sub options: `standbySettings` (where you can set the `primary_conninfo`) and `archiveRecoverySettings` (the same of pitr, where you can set the `restore_command`).

You can omit one of them (or also both ending with a cluster not syncing) so you can use only the streaming replication or the wal restore.

**Comment by jonjomckay** [comment]
Thanks @sgotti! I'm out of the country this week, but I'll make sure to test it out when I'm back in the office next week.

**Comment by sgotti** [comment]
Resolved by #543 

@jonjomckay Feel free to test it and report if if works for you.
