### ISSUE TITLE
Can't start stolon's keeper in Kubernetes

### ISSUE THREAD

**Issue by twelfthdoctor** [sorintlab/stolon#539]
Hello. I'm trying to run a stolon-based PostgreSQL cluster with Kubernetes 1.11
But I can't connect with stolon`s proxy.
```
doctor@doctor:~/stolon$ psql -h 10.98.207.36
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
Logs from proxy(**stolon-proxy-db976479d-gxqxz**):
```
2018-08-08T20:01:04.362Z	INFO	cmd/proxy.go:236	no db object available, closing connections to master	{"db": ""}
```
Logs from sentinel(**stolon-sentinel-54579c7dd-qk8vv **):
```2018-08-08T19:57:14.310Z	INFO	cmd/sentinel.go:1965	sentinel uid	{"uid": "378bfbea"}
2018-08-08T19:57:14.323Z	INFO	cmd/sentinel.go:96	Trying to acquire sentinels leadership
ERROR: logging before flag.Parse: I0808 19:57:14.323379       1 leaderelection.go:174] attempting to acquire leader lease...
ERROR: logging before flag.Parse: I0808 19:57:14.379482       1 leaderelection.go:184] successfully acquired lease default/stolon-cluster-kube-stolon
2018-08-08T19:57:14.388Z	INFO	cmd/sentinel.go:103	sentinel leadership acquired
2018-08-08T19:57:14.442Z	INFO	cmd/sentinel.go:771	trying to find initial master
2018-08-08T19:57:14.442Z	ERROR	cmd/sentinel.go:1906	failed to update cluster data	{"error": "cannot choose initial master: no keepers registered"}
```
And I can see that I have only one pod with keeper instead of two. This pod also has **pending** status.
```packet@dziminv:~/stolon$ kubectl get pods
NAME                              READY     STATUS    RESTARTS   AGE
stolon-keeper-0                   0/1       Pending   0          7m
stolon-proxy-db976479d-gxqxz      1/1       Running   0          6m
stolon-proxy-db976479d-jk754      1/1       Running   0          6m
stolon-sentinel-54579c7dd-gvd9x   1/1       Running   0          7m
stolon-sentinel-54579c7dd-qk8vv   1/1       Running   0          7m
```
Logs of **stolon-keeper-0** are empty:
```
doctor@doctor:~/stolon$ kubectl logs stolon-keeper-0
doctor@doctor:~/stolon$ 
```

**Comment by sgotti** [comment]
@twelfthdoctor since you already asked on gitter let's continue there (I don't see any issue here, just the keeper in pending state probably due to wrong PV configuration)

**Comment by matheus666matheus** [comment]
Same issue here....

**Comment by GeneratorEVil** [comment]
Hi all ! I have the same problem. Told me pls how to fix it?

**Comment by meirhazonAnyVision** [comment]
Hello, same issue. were you able to fix this? How?
Thanks so much

**Comment by JWDobken** [comment]
I have the same issue

**Comment by sgotti** [comment]
There was no stolon issue here. Just k8s stuck creating pods since there was no storage provisioner configured that are reported in the kubernetes pod events (and the stolon k8s examples is just an example and should be adapted for custom k8s configurations)

If someone has troubles with stolon should ask on gitter reporting all the information that can be useful: https://github.com/sorintlab/stolon#contacts
