### ISSUE TITLE
RFE: Secure docker images

### ISSUE THREAD

**Issue by izelnakri** [sorintlab/stolon#550]
- Request for enhancement (RFE)

### Enhancement Description

Currently stolon is distributed with versioned tags along with postgres versions which is very nice. However I'm still bit concerned running a production database cluster through 3rd party images in general, what if sorintlab dockerhub account gets compromised somehow? 

Apparently we can reference images with their last docker layer hash:
```
sorintlab/stolon:v0.12.0-pg10@sha256:5615637474e108f2920f2b6e7d6cd3d4e8fa1e145827eb882d3ba2fae48dc6fc
```

This will truly lock down the image for security. The other concern is what if an image with certain tag gets updated on dockerhub? I'm not sure if the previous image with the same tag does get deleted from the dockerhub or not when there is a patch. If it does get deleted, it might be a better idea to distribute the images via datestamp-version-pg-version tags, example:

```
sorintlab/stolon:2018-08-01-v0.12.0-pg10
```
This way I can use the following in my kubernetes cluster to make sure I'm always fetching the right image:

```
sorintlab/stolon:2018-08-01-v0.12.0-pg10@sha256:5615637474e108f2920f2b6e7d6cd3d4e8fa1e145827eb882d3ba2fae48dc6fc
```

Of course if there is true semantic versioning we can upgrade the version reference for patches, then we dont need datestamps. I'm not sure if they are implemented right now, my actual request is to document a production security guide under /docs for other people.

**Comment by sgotti** [comment]
@izelnakri Stolon images are **example** images. It has always been stated also in the dockerhub page to not use them for production: `stolon EXAMPLE image. Don't use it in production but build your own image.`

You should build you own image using the example as a starting point (and add you extension, backup  tools etc...)

**Comment by sgotti** [comment]
#559 Add some more notes in the examples doc explaining that these are just example images. I think this could be closed.
