### ISSUE TITLE
error: failed switching to "stolon": operation not permitted

### ISSUE THREAD

**Issue by frelist** [sorintlab/stolon#551]
### Submission type

 - Bug report

### Environment
OpenShift Online

#### Stolon version
v0.12.0

### Expected behaviour you didn't see
Sentinel up and running

### Unexpected behaviour you saw
error: failed switching to "stolon": operation not permitted

### Steps to reproduce the problem
Just follow the example running stolon-sentinel.yaml

### Enhancement Description
Got "error: failed switching to "stolon": operation not permitted" when creating sentinel.
I have a look to files in docker image.  May be it is caused by NO sticky bit in gosu.  Below is ls -l output in stolon docker image in docker hub

-rwxr-xr-x. 1 root staff  1286720 May 24  2017 gosu

**Comment by sgotti** [comment]
@frelist the example is for a standalone kubernetes installation. Openshift, by default, runs a container using a random user without root privileges so gosu fails. You should adapt the example/image to run without gosu or relax the openshift policy (see openshift docs).

**Comment by sgotti** [comment]
@frelist Any news on this?

**Comment by sgotti** [comment]
@frelist I'm going ot close this. Feel free to reopen if you have more info or to provide a PR with the possible changes to make it run on openshift without changing its policy.

**Comment by frelist** [comment]
@sgotti i finally got a chance to test it out.

First of all, our image is built from rhscl/postgresql-10-rhel7 + stolon executables.  If you are using other docker image, the behavior may not be the same.


Below are 4 changes to kubernetes example in order to run stolon cluster under openshift.

1.  create role with below permission

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: stolon
  namespace: stolon-postgresql-primary
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - "get"
  - "create"
  - "update"
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - "get"
  - "list"

2.  Remove gosu and run the stolon executable directly.  Openshift runs the container using random uid with root gid.

To avoid keeper container got error "cannot get current user: cannot detect current user" because uid not found in /etc/passwd.  2 more actions.

3.  add 1 line in dockerfile - "run chmod g+w /etc/passwd"

4.  when initialize keeper container, add record to /etc/passwd about the current uid

Please take note to https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/
