### ISSUE TITLE
Unnecessary reloads postgresql due to pg_hba.conf host order with "defaultSUReplAccessMode": "strict"

### ISSUE THREAD

**Issue by ruatag** [sorintlab/stolon#556]
### Submission type

 - Bug report

### Environment
CentOS 7
PostgreSQL 10
go 1.10.4
consul 1.10
#### Stolon version
0.12.0
### Expected behaviour you didn't see
no changes in cluster config - "postgres hba entries not changed"
no reload postgresql configuration
### Unexpected behaviour you saw
no changes in cluster config - "postgres hba entries changed, reloading postgres instance"
2018-08-28T17:59:47.161+0300    INFO    cmd/keeper.go:1591      postgres hba entries changed, reloading postgres instance
2018-08-28T17:59:47.161+0300    INFO    postgresql/postgresql.go:388    reloading database configuration
server signaled
### Steps to reproduce the problem
Activate "defaultSUReplAccessMode": "strict" for 2 slaves or more
it sometimes (not regular intervals) produses pg_hba.conf with cluster host IPs in different sort order and unnecessary reloads postgresql configuration
From PostgreSQL these pg_hba.conf are equal but not for stolon
local postgres postgres md5
local replication repl md5
host all postgres 10.xx.xx.xx/32 md5
host replication repl 10.xx.xx.xx/32 md5
host all postgres 10.yy.yy.yy/32 md5
host replication repl 10.yy.yy.yy/32 md5
host all all 127.0.0.1/32 md5
host all all ::1/128 md5
hostssl all all 10.0.0.0/8 md5

local postgres postgres md5
local replication repl md5
host all postgres 10.yy.yy.yy/32 md5
host replication repl 10.yy.yy.yy/32 md5
host all postgres 10.xx.xx.xx/32 md5
host replication repl 10.xx.xx.xx/32 md5
host all all 127.0.0.1/32 md5
host all all ::1/128 md5
hostssl all all 10.0.0.0/8 md5

May be it depends how consul returned values
cmd\keeper\cmd\keeper.go
Probably it's necesary to sort by dbElt.Status.ListenAddress for case cluster.SUReplAccessStrict:
or compare sorted here
if !reflect.DeepEqual(newHBA, pgm.CurHba()) {

**Comment by sgotti** [comment]
@ruatag Thanks for the detailed report. Would you like to create a PR?

**Comment by sgotti** [comment]
@ruatag Created PR #558
