### ISSUE TITLE
Keeper can't rejoin cluster on AWS storage optimized instances

### ISSUE THREAD

**Issue by merlineus** [sorintlab/stolon#562]
Hi,

We are investigating Stolon usage in our projects and discovered that keeper can't rejoin cluster after instance type changing on AWS storage optimized nodes (i3, c5d). This operation leads to keeper's storage lost due to ephemeral nature of attached SSD disks in AWS. Of course we changing instance type one by one so cluster is healthy at any time.

Logs:
```
2018-09-06T08:45:59.019Z	INFO	cmd/keeper.go:1049	current db UID different than cluster data db UID	{"db": "", "cdDB": "b408a597"}
2018-09-06T08:45:59.019Z	ERROR	cmd/keeper.go:1346	different local dbUID but init mode is none, this shouldn't happen. Something bad happened to the keeper data. Check that keeper data is on a persistent volume and that the keeper state files weren't removed
```

Could you please suggest the right way to handle this case with Stolon?

We are using Stolon v0.12.0.

**Comment by sgotti** [comment]
@merlineus the keeper needs persistent data and it'll return an error if the data has been replaced with an empty one (see the architecture doc: https://github.com/sorintlab/stolon/blob/master/doc/architecture.md#keepers).

What you should do, when replacing the data with a new one, is to firstly stop the keeper and remove it from the cluster data (`stolonctl removekeeper`), then restart it with the new data.

**Comment by sgotti** [comment]
@merlineus I hope I answered your question. If you have further questions please (if it's not a possible bug/enhancement) discuss this on the gitter channel or the mailing list: https://github.com/sorintlab/stolon#contacts

**Comment by merlineus** [comment]
Yes, thank you!
