### ISSUE TITLE
How to restore the stolon cluster

### ISSUE THREAD

**Issue by oceanho** [sorintlab/stolon#563]
Hi.
I have some confusion about the stolon.

I have a stolon cluster, backend store is consul.
But if the consul goes down and lose all of data  for some reason.

Now.
All of client connect will be refuse(because of the consul goes down)
How can i restore my stolon-cluster, under the circumstances.

Can you give me some related links or any ideas? 

Thanks a lot. 😃

**Comment by sgotti** [comment]
@oceanho It'll be better to ask such support questions on the stolon gitter channel or the mailing list: https://github.com/sorintlab/stolon#contacts The issue tracker is to track issues.

Anyway it's already documented here: https://github.com/sorintlab/stolon/blob/master/doc/architecture.md#handling-permanent-loss-of-the-store
