### ISSUE TITLE
how to increase the number of connections in stolon kubernetes

### ISSUE THREAD

**Issue by nbabured** [sorintlab/stolon#571]
how to increase the number of connections in stolon kubernetes

currently its 100, we need to set it too 200.

**Comment by sgotti** [comment]
Please see the doc on how to manage the postgres parameters: https://github.com/sorintlab/stolon/blob/master/doc/postgres_parameters.md

If you have further questions please use the gitter channel or the mailing list: https://github.com/sorintlab/stolon#contacts . The issues tracker is for issues.
