### ISSUE TITLE
Add a possibility to override configmap name

### ISSUE THREAD

**Issue by IvanovOleg** [sorintlab/stolon#572]
### Submission type

 - Request for enhancement (RFE)

### Environment
Kubernetes 1.12.1
#### Stolon version
0.13.0
### Enhancement Description
**failed to get latest version of configmap: configmaps "stolon-cluster-$CLUSTER_NAME"**
I want to have a possibility to set "postgres" as a configmap name

**Comment by sgotti** [comment]
@IvanovOleg The name is created in that way to avoid clashes between multiple clusters in the same k8s namespace. Overriding it can lead to a lot of issues if users don't understand the implications and use the same configmap for multiple clusters. I'm not willing to change this if there isn't a good reason.

Can you provide a reason why you want to override it?

> failed to get latest version of configmap: configmaps "stolon-cluster-$CLUSTER_NAME"

I'm not sure if this is an unwanted paste in the description. If you're getting this error then you have messed up the some fields in the k8s resources yaml files. But this isn't related to this issue.

**Comment by IvanovOleg** [comment]
I wish to change stolon to postgres in each resource name because some users don't understand what stolon is and why they need it. I hate to explain it each time.

**Comment by sgotti** [comment]
@IvanovOleg There are other places inside k8s where the stolon name is used (for example the labels used for discovery contains stolon name). I'm sorry but changing it will require a lot of work for no great gains.

PRs are welcome but this will require adding various options to be passed to every stolon component invocation (and will be very error prone).
