### ISSUE TITLE
automate post DB creation actions

### ISSUE THREAD

**Issue by frelist** [sorintlab/stolon#573]
### Submission type

 - Request for enhancement (RFE)

#### Stolon version
latest

### Enhancement Description

After primary DB got created in keeper process, we need to run below actions.  Now, we run them manually.  Is it possible to add feature to run scripts after DB creation?

1.  run command "CREATE EXTENSION pgaudit"
2.  run command "revoke create on schema public from public" in template1 db
3.  create predefined DB and application user
4.  run command "grant create on schema public to app user" in new db

**Comment by sgotti** [comment]
@frelist This can be automated by an external script that will detect when the cluster is ready ( just trying to connect until the db is up or improve it parsing `stolonctl clusterdata`). There's no need to add this to stolon since it's not related to postgres HA.
