### ISSUE TITLE
Request for Dockerfile details for stolon

### ISSUE THREAD

**Issue by reachbharathan** [sorintlab/stolon#580]
### Submission type
Clarification 

I wanted to know the current construction of stolon container, can you help us to know the container build info.
Referred the same in 'https://hub.docker.com/r/sorintlab/stolon/ ' no details available

**Comment by sgotti** [comment]
@reachbharathan The dockerfile template used to build them is here: https://github.com/sorintlab/stolon/tree/master/examples/kubernetes/image/docker

The doc on how it's built is here: https://github.com/sorintlab/stolon/tree/master/examples/kubernetes#docker-image
