### ISSUE TITLE
Error messages in Sentinel running on openshift while DB cluster is up and running

### ISSUE THREAD

**Issue by frelist** [sorintlab/stolon#582]
### Submission type

 - Bug report

### Environment
openshift origin 3.11

#### Stolon version
0.13.0

#### Additional environment information if useful to understand the bug
DB can be created.  Keeper and Proxy pods are running fine and no error message.  Application can connect DB.
Look like sentinel is working but got errors.  The frequency is around 1 error message per hour.

### Expected behaviour you didn't see
No error message

### Unexpected behaviour you saw
error messages in sentinel

ERROR: logging before flag.Parse: E1102 17:09:39.306871      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E1102 17:23:28.010448      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E1102 17:51:25.397321      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E1102 18:18:02.531086      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
2018-11-02T19:38:34.437Z	WARN	cmd/sentinel.go:275	no keeper info available	{"db": "13bea5a9", "keeper": "keeper0"}
ERROR: logging before flag.Parse: E1102 20:24:26.762406      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E1103 00:21:06.265490      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
2018-11-03T00:23:57.014Z	WARN	cmd/sentinel.go:275	no keeper info available	{"db": "13bea5a9", "keeper": "keeper0"}
ERROR: logging before flag.Parse: E1103 00:57:41.198705      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E1103 01:10:19.685575      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E1103 02:04:04.215193      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E1103 02:17:42.843178      10 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-test1-postgresql": the object has been modified; please apply your changes to the latest version and try again

### Steps to reproduce the problem
build a simple cluster on openshift or kubernetes

**Comment by frelist** [comment]
@sgotti  except these 2 type of errors messages, DB cluster is running as expected.
So, should we ignore them?

**Comment by sgotti** [comment]
@frelist yes. We cannot do much about them.

**Comment by lhzw** [comment]
> @frelist yes. We cannot do much about them.

What about changing the log to a Warning?
Don't know should ignore it or something else as it is a ERROR.
