### ISSUE TITLE
change client_addr of pg_stat_activity to show application client address rather than proxy address.

### ISSUE THREAD

**Issue by frelist** [sorintlab/stolon#589]
### Submission type

 - Request for enhancement (RFE)
change client_addr of pg_stat_activity to show application client address rather than proxy address.  This is behavior of standalone postgresql without cluster software.

### Environment
OpenShift Origin 3.11

#### Stolon version
0.13.0

### Expected behaviour you didn't see

client_addr of pg_stat_activity shows application address rather than proxy address

### Unexpected behaviour you saw

>oc get pod pg-test2-ha-stolon-proxy-6b889d89cb-kkh2s -o wide
NAME                                        READY     STATUS    RESTARTS   AGE       IP             NODE         NOMINATED NODE
pg-test2-ha-stolon-proxy-6b889d89cb-kkh2s   1/1       Running   0          1d        10.129.1.250   zhkdlp1826   <none>

>oc rsh pg-test2-ha-stolon-proxy-6b889d89cb-kkh2s
sh-4.2$
sh-4.2$
sh-4.2$ psql -h pg-test2
Password:
psql (10.3)
Type "help" for help.

postgres=# select client_addr, application_name from pg_stat_activity ;
 client_addr  |     application_name
--------------+--------------------------
              |
              | pglogical supervisor
              |
 10.129.1.250 | walreceiver
 10.129.1.250 | DBeaver 5.1.0 - Main
 10.129.1.250 | DBeaver 5.1.0 - Metadata
 10.129.1.250 | DBeaver 5.1.0 - Main
 10.129.1.250 | DBeaver 5.1.0 - Metadata
 10.129.1.250 | DBeaver 5.1.0 - Main
 10.129.1.250 | DBeaver 5.1.0 - Metadata
 10.129.1.250 | pg_receivewal
 10.129.1.250 | DBeaver 5.1.0 - Main
 10.129.1.250 | DBeaver 5.1.0 - Metadata
 10.129.1.250 | psql
              |
              |
              |
(17 rows)

### Enhancement Description
change client_addr of pg_stat_activity to show application client address rather than proxy address.  This is behavior of standalone postgresql without cluster software.

Knowing the client application address is critical when troubling issue.  In case it is not possible to "fix/change" view pg_stat_activity, how we can know the client address?

**Comment by sgotti** [comment]
@frelist the client address will always be the proxy. If you really have the need to rely on it than that's not possible.

The unique way to really see the real client address will be to make the stolon proxy work in transparent proxy mode but this will only work if you have full control of your instance and correctly setup ip routing and netfilter.
