### ISSUE TITLE
pg-listen-address Unexpected behavior

### ISSUE THREAD

**Issue by BaronMsk** [sorintlab/stolon#593]
### Submission type

 - Bug report
 

#### Stolon version
stolon-keeper version v0.13.0

#### Additional environment information if useful to understand the bug
Run service
sorintlab/stolon:v0.13.0-pg11 \
  gosu \
  stolon \
  stolon-keeper \
  --cluster-name=test \
  --store-backend=etcdv3 \
  --store-ca-file=/etc/ssl/certs/ca.crt \
  --store-cert-file=/etc/ssl/certs/stolon.crt \
  --store-key=/etc/ssl/certs/stolon.key \
  --store-endpoints=https://etcd:2379 \
  --pg-bin-path=/usr/lib/postgresql/11/bin/ \
  --uid=postgres02 \
  --data-dir=/var/lib/stolon/postgres02 \
  --pg-su-password=supassword \
  --pg-repl-username=repluser \
  --pg-repl-password=password \
  --pg-listen-address=0.0.0.0

### Expected behaviour you didn't see
netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5432          0.0.0.0:*               LISTEN      20095/postgres      
tcp6       0      0 :::25432                :::*                    LISTEN      16868/stolon-proxy  
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd           
raw6       0      0 :::58                   :::*                    7           676/systemd-network 
### Unexpected behaviour you saw
netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      20095/postgres      
tcp6       0      0 :::25432                :::*                    LISTEN      16868/stolon-proxy  
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd           
raw6       0      0 :::58                   :::*                    7           676/systemd-network
### Steps to reproduce the problem
Quick start Cluster

**Comment by sgotti** [comment]
@BaronMsk Currently stolon configure postgres to list also on 127.0.0.1 and setting listen address to 0.0.0.0 doesn't make sense and your cluster won't work since 0.0.0.0 will also become the advertized address that the proxy will use to connect and obviously will fail. For an enhancement see PR #581. Until it's not merged you have to choose a real and externally reachable ip address as the postgres listen address.
