### ISSUE TITLE
Deploy multiple stolon clusters in one k8s cluster

### ISSUE THREAD

**Issue by aixeshunter** [sorintlab/stolon#594]
### Question
Hi, I deployed a stolon cluster with yaml files in stolon/examples/kubernetes/ and had a question.
Can I deploy multiple stolon postgresql clusters in one k8s environment?

### Environment
kubernetes v1.11+

**Comment by prabhu43** [comment]
@aixeshunter yes, you can deploy multiple stolon cluster in one k8s cluster. make sure you use different stolon cluster name. You can also use helm chart for stolon. https://github.com/helm/charts/tree/master/stable/stolon

**Comment by aixeshunter** [comment]
> @aixeshunter yes, you can deploy multiple stolon cluster in one k8s cluster. make sure you use different stolon cluster name. You can also use helm chart for stolon. https://github.com/helm/charts/tree/master/stable/stolon

@prabhu43 Thanks! And can I deploy multiple stolon clusters in single namespace?

**Comment by prabhu43** [comment]
@aixeshunter yes, you can deploy multiple stolon clusters in same namespace

**Comment by aixeshunter** [comment]
@prabhu43 Thanks!
