### ISSUE TITLE
Checksum mismatch, cannot build from source

### ISSUE THREAD

**Issue by jnicholls** [sorintlab/stolon#597]
```
go: verifying github.com/coreos/etcd@v3.2.11+incompatible: checksum mismatch
	downloaded: h1:S3HFWk+1nkDWvYPJnWNNqi/dWnXJa3S3zQgFOycHbC8=
	go.sum:     h1:6Xrc6QL7mya9CDf0G+hiyb53kO7L5OQ6HZ3EvBsrAUI=
```

go 1.11.4

**Comment by jnicholls** [comment]
I'm working around this by replacing `go.sum` with a modified version during my build process until the hashes are adjusted upstream.

**Comment by sgotti** [comment]
@jnicholls Thanks, looks like go 1.11.4 changed (again) the checksum calculation. Created #598 . 
(to build this just remove the go.sum instead of fixing it by hand)
