### ISSUE TITLE
"error": "cannot get cluster data: failed to get latest version of configmap: Get https://10.96.0.1:443/api/v1/namespaces/k8poc-sathya/configmaps/stolon-cluster-kube-stolon:

### ISSUE THREAD

**Issue by sathyu** [sorintlab/stolon#602]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

**Comment by sathyu** [comment]
I am running this  prebuilt image in k8  version 1.10.
when I try to run proxy, I am getting this error.  I also get his error when I ran stolonctl from Sentinel pod.
not sure why it is trying https:/10.9.0.1  .

Any help on this is appreciated.
Thanks

**Comment by sathyu** [comment]
sorry, wrongly closed this.

**Comment by qasimmaqbool** [comment]
@sathyu did you figure out the cause behind this error? I am seeing this too.

**Comment by phlegx** [comment]
@sathyu May I ask how you solved this? Thanks!
