### ISSUE TITLE
Expose metrics related to stolon cluster for prometheus

### ISSUE THREAD

**Issue by prabhu43** [sorintlab/stolon#603]
### Submission type
 - Request for enhancement (RFE)

### Stolon version
Latest

### Enhancement Description
Expose Stolon cluster metrics like master keeper, sentinel leader, health status of keeper, proxy and sentinels

#### Need for enhancement
Currently, we dont have any metrics to know the stolon cluster status. It will be useful to know certain information like which keeper is the master and its health status without having to access the cluster data.

**Comment by prabhu43** [comment]
Hi @sgotti,
I and @vidhig are planning to work on this. Let us know if you have some inputs or suggestions

**Comment by dbarkin** [comment]
metrics would be very useful. need to monitor stolon cluster components.

**Comment by judexzhu** [comment]
would it be possible showing the same metrics as regular PostgreSQL exporter?

https://github.com/wrouesnel/postgres_exporter

It would be a convenience to use the same dashboard and rules .

**Comment by jpds** [comment]
c5e1e982 added the prometheus client libraries but it only exposes golang metrics at the moment.

**Comment by jpds** [comment]
Some metrics are available in 71d109541f800fcacb2d8e3222715d84e569ccb5.

**Comment by sgotti** [comment]
Initial metrics for keeper and sentinel have been implemented in #639 and #656. I'm going to close this. Feel free to propose/implement new metrics.

**Comment by petrovicZiko** [comment]
Hello @sgotti, is it possible to get metrics from the database itself(like metrics for transactions, connections,...)?
In the docker-compose configuration, with stolon image and prometheuscommunity/postgres-exporter, it is possible to get those metrics. But, in the cluster I only get metrics from the stolon cluster itself, tried to deploy helm chart for postgres-exporter as well, but it provides only stolon cluster metrics.

Thanks
