### ISSUE TITLE
How to force a non master keeper to resync with master data?

### ISSUE THREAD

**Issue by pedromvieira** [sorintlab/stolon#604]
I'm using Stolon with Postgres 11 and Kubernetes.
I've created a new empty disk for stolon-data (with less storage but bigger than database size).
The container / pod starts but dosent sync data (around 13 GB).
How to force this keeper to get master data and sync again?

root@stolon-keeper-0:/stolon-data# stolonctl status --cluster-name kube-stolon --store-backend kubernetes --kube-resource-kind=configmap init
=== Active sentinels ===

ID		LEADER
160cd6c5	false
4b7963aa	false
ee965815	true

=== Active proxies ===

ID
8ab614aa
af07a53f
b4e28181

=== Keepers ===

UID	HEALTHY	PG LISTENADDRESS	PG HEALTHY	PG WANTEDGENERATION	PG CURRENTGENERATION
keeper0	true	10.4.2.218:5432		false		3			3
keeper1	true	10.4.0.48:5432		true		2			2
keeper2	true	10.4.1.42:5432		true		5			5

=== Cluster Info ===

Master: keeper2

===== Keepers/DB tree =====

keeper2 (master)
├─keeper1
└─keeper0

**Comment by pedromvieira** [comment]
After digging logs with "kubectl logs -f stolon-keeper-0", I founded the issue and a keeperremove solved the issue.

`stolonctl removekeeper keeper0 --cluster-name kube-stolon --store-backend kubernetes --kube-resource-kind=configmap`

**Comment by mmpei** [comment]
so the slave starts to resync from master after you remove it from cluster?
i want to know how to add a slave to cluster or how to do when a slave becomes inconsistent with master in k8s.
create a new PV then increase the replica of keeper, then removekeeper?
@pedromvieira @sajal
