### ISSUE TITLE
Install stolon while preserving old pg data

### ISSUE THREAD

**Issue by DanielVaknin** [sorintlab/stolon#607]
### Environment
Kubernetes 1.10

#### Stolon version
v0.13

#### Additional environment information if useful to understand the bug
Installing stolon using helm

### Expected behaviour you didn't see
When having a `postgres` folder containing pg data already in `/stolon-data/postgres` (which is mounted in keeper pod), I expected stolon to not override the files there, so the data will remain.

### Unexpected behaviour you saw
When having the `postgres` folder in place, stolon will override the entire folder, and the data will be lost.

### Steps to reproduce the problem
1. Install stolon helm chart
2. write some data to pg
3. delete helm chart and all files in `/stolon-data/` folder except for the `postgres` folder
4. re-install stolon helm chart

My main question is: how can I install Stolon while preserving the pg data I already have (in the `postgres` folder)

**Comment by aswinkarthik** [comment]
Did you use the [stable stolon chart](https://github.com/helm/charts/tree/master/stable/stolon)?

A post-install hook Job is running `stolonctl init` with `initMode` as "new". If you **skip** that it should be able to preserve data. As long as it is in a persistent disk, the data will not go. This will work only if your clusterdata is preserved in store.

If you lost your clusterdata as well, you can use `initMode` as "existing" as in docs [here](https://github.com/sorintlab/stolon/blob/master/doc/initialization.md#initialize-a-new-stolon-cluster-using-an-existing-keeper)

However,

**Comment by DanielVaknin** [comment]
Thanks for the answer!

I've tried to skip the hook job (by setting `--set job.autoCreateCluster=false` but when I only had the `postgres` folder (but no keeperstate and dbstate files), stolon keeper's failed to start.
I'm trying now again with preserving those files but it'll not answer my use-case.

I'll try to better explain the use-case: we currently have Postgres running in a different server, and we want to migrate its' data to Stolon (but not use export and import since it'll take too much time).
So my expectation was that if I'd take the `postgres` folder from the "old" Postgres server, and try to run Stolon with that folder (I don't have the other files since I don't yet have stolon), It'd just start and keep the current PGDATA.

Regarding using `initMode` as "existing", as I understood, It'd work only if I already have keepers running, but in my initial state there are no keepers running, but rather just PGDATA folder that I want to keep.

Hopefully my use-case is more clear now.

**Comment by aswinkarthik** [comment]
Got it. Just that I have one question. Is your "old" postgres server still running?

If yes, you could do a  `initMode`: `pitr` as documented [here](https://github.com/sorintlab/stolon/blob/master/doc/standbycluster.md#a-standby-cluster-of-a-standalone-postgres-instance) 

If your old postgres server is not running and all you have is just the PGDATA directory. Then this does not work. We would have to think of a different way.

**Comment by DanielVaknin** [comment]
Unfortunately this "old" postgres server is not running...

But even if it was, I think that there should be an option/flag to start stolon with existing PGDATA directory.

I'll try a workaround where I'l create new stolon cluster, then replace the "empty" PGDATA directory with my own, then recreate stolon, and see if that works

**Comment by sgotti** [comment]
@DanielVaknin the keeper data dir is not the postgres data dir. You should put the postgres data insidie `$keeperdatadir/postgres`  then start the stolon components without auto init and manually init the cluster using initmode existing. You should also migrate the postgres parameters and pg_hba options to the stolon clusterspec. See the related doc.

**Comment by Valeriyy** [comment]
Hello dears!
I just now realized that Keeper going to initialize the database at the first start. Because I have errorL
```
sudo -u postgres ./bin/stolon-keeper --cluster-name postgresql --store-backend=consul --uid pg0 --data-dir /home/stolon/pg0 --pg-su-username=root --pg-su-password=mydevpass --pg-repl-auth-method trust --pg-repl-us[40/1832]
pl --pg-listen-address=10.246.0.95 --pg-bin-path=/usr/pgsql-9.6/bin
2019-03-01T16:31:30.979+0300    WARN    cmd/keeper.go:1820      not utilizing a password for replication between hosts is extremely dangerous
2019-03-01T16:31:30.980+0300    INFO    cmd/keeper.go:1911      exclusive lock on data dir taken
2019-03-01T16:31:30.992+0300    INFO    cmd/keeper.go:492       keeper uid      {"uid": "pg0"}
2019-03-01T16:31:31.019+0300    INFO    cmd/keeper.go:990       our db boot UID is different than the cluster data one, waiting for it to be updated    {"bootUUID": "95f464bc-b907-452b-b629-3dbc6ed342c6", "clusterBootUUID": "4fd05f26-1fc9-4c8e-ae68-2fb9b8ed413f"}
2019-03-01T16:31:36.055+0300    INFO    cmd/keeper.go:990       our db boot UID is different than the cluster data one, waiting for it to be updated    {"bootUUID": "95f464bc-b907-452b-b629-3dbc6ed342c6", "clusterBootUUID": "4fd05f26-1fc9-4c8e-ae68-2fb9b8ed413f"}
2019-03-01T16:31:41.069+0300    INFO    cmd/keeper.go:1037      current db UID different than cluster data db UID       {"db": "", "cdDB": "ed5fa158"}
2019-03-01T16:31:41.069+0300    INFO    cmd/keeper.go:1044      initializing the database cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/stolon/pg0/postgres ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/pgsql-9.6/bin/pg_ctl -D /home/stolon/pg0/postgres -l logfile start

2019-03-01T16:31:42.537+0300    INFO    postgresql/postgresql.go:307    starting database
< 2019-03-01 16:31:42.557 MSK > LOG:  could not bind IPv4 socket: Address already in use
< 2019-03-01 16:31:42.557 MSK > HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
< 2019-03-01 16:31:42.557 MSK > WARNING:  could not create listen socket for "127.0.0.1"
< 2019-03-01 16:31:42.557 MSK > LOG:  could not bind IPv4 socket: Address already in use
< 2019-03-01 16:31:42.557 MSK > HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
< 2019-03-01 16:31:42.557 MSK > WARNING:  could not create listen socket for "10.246.0.95"
< 2019-03-01 16:31:42.557 MSK > FATAL:  could not create any TCP/IP sockets
< 2019-03-01 16:31:42.557 MSK > LOG:  database system is shut down
2019-03-01T16:31:42.738+0300    ERROR   cmd/keeper.go:1083      failed to start instance        {"error": "postgres exited unexpectedly"}
2019-03-01T16:31:47.744+0300    ERROR   cmd/keeper.go:1006      db failed to initialize or resync
2019-03-01T16:31:47.807+0300    INFO    cmd/keeper.go:1037      current db UID different than cluster data db UID       {"db": "", "cdDB": "ed5fa158"}
2019-03-01T16:31:47.807+0300    INFO    cmd/keeper.go:1044      initializing the database cluster
```
I already have master-slave PostgreSQL cluster and I want to implement Stolon without downtime and initialize. How do I do that?

**Comment by Valeriyy** [comment]
[It's easy](https://github.com/sorintlab/stolon/blob/master/doc/initialization.md). The whole question is how to run Stolon in the current PostgreSQL cluster without downtime master.

**Comment by sgotti** [comment]
@DanielVaknin My last comment should have explained how to do this. If not please ask further questions in the gitter channel: https://github.com/sorintlab/stolon#contacts
