### ISSUE TITLE
stolon-sentinel can`t attach to consul kv storage

### ISSUE THREAD

**Issue by skilyazhnev** [sorintlab/stolon#608]
Hi.  

i have Problem on oracle linux.
Stolon version: 0.13

At the start stolon-sentinel 

`stolon-sentinel --cluster-name mycluster --store-backend consul --store-prefix Platform/stolon/cluster --log-level debug`

gives an error

`"ERROR   cmd/sentinel.go:100     election loop error     {"error": "Unexpected response code: 403 (rpc error making call: rpc error making call: Permission denied)"}"`

I use Consul v1.4.1 with ACL  and i export CONSUL_HTTP_TOKEN. But that doesn't work.

**Comment by sang-kevin** [comment]
I encountered the same problem, how did you solve it?
