### ISSUE TITLE
Using  ./build  to build stolon 

### ISSUE THREAD

**Issue by sathyu** [sorintlab/stolon#611]
### Submission type
Help
$ sh -x ./build
+ set -e
++ dirname ./build
+ source ./scripts/readlinkdashf.sh
+++ dirname ./build
++ readlinkdashf .
++ [[ -d . ]]
++ cd .
++ pwd -P
+ BASEDIR=/home/sjois1/go/src/stolon
+ BINDIR=/home/sjois1/go/src/stolon/bin
+ '[' /home/sjois1/go/src/stolon '!=' /home/sjois1/go/src/stolon ']'
+ ORG_PATH=github.com/sorintlab
+ REPO_PATH=github.com/sorintlab/stolon
+ mkdir -p /home/sjois1/go/src/stolon/bin
++ /home/sjois1/go/src/stolon/scripts/git-version.sh
+ VERSION=8b928d6775d3df1cf9b0e054ce9bb0e35d76651e
+ LD_FLAGS='-s -X github.com/sorintlab/stolon/cmd.Version=8b928d6775d3df1cf9b0e054ce9bb0e35d76651e'
+ use_go_install=
++ go env GOROOT
+ go_root_dir=/usr/local/go
++ go env GOHOSTOS
+ go_host_os=linux
++ go env GOHOSTARCH
+ go_host_arch=amd64
+ cgodisabled_pkg_dir=/usr/local/go/pkg/linux_amd64_cgo
+ '[' -e /usr/local/go/pkg/linux_amd64_cgo ']'
+ '[' -w /usr/local/go/pkg ']'
+ for cmd in sentinel proxy
+ CGO_ENABLED=0
+ go build -installsuffix cgo -ldflags '-s -X github.com/sorintlab/stolon/cmd.Version=8b928d6775d3df1cf9b0e054ce9bb0e35d76651e' -o /home/sjois1/go/src/stolon/bin/stolon-sentinel github.com/sorintlab/stolon/cmd/sentinel
can't load package: package github.com/sorintlab/stolon/cmd/sentinel: cannot find package "github.com/sorintlab/stolon/cmd/sentinel" in any of:
        /usr/local/go/src/github.com/sorintlab/stolon/cmd/sentinel (from $GOROOT)
        /home/sjois1/go/src/stolon/src/github.com/sorintlab/stolon/cmd/sentinel (from $GOPATH)

Not sure how to build, any help is appreciated.

**Comment by dineshba** [comment]
What is the path where you cloned the repo. What is the value of $GOPATH ?

**Comment by sgotti** [comment]
@sathyu you should `go get` it to put in the right path (that is `$GOPATH/src/github.com/sorintlab/stolon`) under GOPATH or clone it outside GOPATH and use go 1.11 modules feature.

**Comment by sathyu** [comment]
hi dineshba
Build command issued from 
/home/user/stolon/build

Clone path:   /home/user/stolon
gopath=/usr/local/src

pasting go env output for better understanding:
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/src/github.com/sorintlab/stolon"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build069347355=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
