### ISSUE TITLE
Confusion on "Simulate master death"  description under k8s

### ISSUE THREAD

**Issue by cotigao** [sorintlab/stolon#612]
I might be missing something obvious but I quite didn't  follow the description from [Simulate Master Death](https://github.com/sorintlab/stolon/blob/master/examples/kubernetes/README.md#simulate-master-death), under k8s section

>There are different ways to tests this. In a multi node setup you can just shutdown the host executing
>the master keeper pod.
>
>In a single node setup we can kill the current master keeper pod but usually the statefulset controller will recreate a new pod before the sentinel declares it as failed. To avoid the restart we'll first remove the statefulset without removing the pod and then kill the master keeper pod.

_To avoid the restart we'll first remove the statefulset without removing the pod and then kill the master keeper pod_ ― How will one ensure this in real world scenario? or what's the connection between multi node/single node here?  I am yet to try stolon. Thought get this doubt cleared first.

**Comment by sgotti** [comment]
@cotigao that's just an example to try it. For real world scenarios see the stolon integration gets that cover tons of cases.
