### ISSUE TITLE
Use 2 node stolon without proxy ( with vip)

### ISSUE THREAD

**Issue by skilyazhnev** [sorintlab/stolon#615]
Hi. 

### Submission type
 - Request for enhancement (RFE)

#### Stolon version
v0.13

### Environment 
oracle linux 7 

### note
I deployed the 2 node stolon with keepalived(VIP). I think we can do without a proxy when using VIP.
if weteach keepalived to interact with the sentinel, then it will be possible to avoid the situation with two vip and avoid unnecessary load in the form of a proxy

### Enhancement Description
create an interface between keepalived and sentinel

###  need for improvement

For simpler installations, this will reduce the number of points of failure (proxy) and allow you to go directly to the master server.

**Comment by sgotti** [comment]
@skilyazhnev the proxy cannot be skipped. Without it you can end up with transactions committed to the wrong instance (and then lost). This is clearly explained in the architecture doc, in the FAQ and in various similar issues.

**Comment by maksm90** [comment]
Hi @skilyazhnev
Theoretically the [vip-manager](https://github.com/cybertec-postgresql/vip-manager) would be appropriate solution. But this requires to find DCS keys on updates of which subscription is required.
