### ISSUE TITLE
Installing Stolon into the current cluster PostgreSQL without downtime

### ISSUE THREAD

**Issue by Valeriyy** [sorintlab/stolon#616]
Hello!
I already have cluster PostgreSQL and I want to switch it to Stolon without downtime.
I can take the current PostgreSQL slave instance and run stolon-kepper on it. But during this time master that works without Stolon will be filled with new data. Can I somehow run the first Keeper in slave mode, which will receive replica from the master running not under the control of Stolon? That would be a great solution because after migration such the slave under control of stolon-keeper, I could switch it to master and also switch the application to stolon-proxy.
Thus, I will get a minimal downtime, the application will lose connection with master for a few seconds.
I can not afford to stop the current master for a few minutes to switch it under the control of the stolon-keeper.

**Comment by sgotti** [comment]
@Valeriyy use a standby stolon cluster: https://github.com/sorintlab/stolon/blob/master/doc/standbycluster.md  
such questions are not issues so should be asked on the gitter channel: https://github.com/sorintlab/stolon#contacts
