### ISSUE TITLE
Infer stolonctl flags from environment variables

### ISSUE THREAD

**Issue by arunvelsriram** [sorintlab/stolon#617]
### Submission type

 - Request for enhancement (RFE)

### Enhancement Description

Currently `stolonctl` requires `cluster-name`, `store-backend`, `store-endpoints` to be passed explicitly as flags. This could be hard to work with when we have multiple stolon clusters and they use different store backends. My suggestion is to consider environment variables (like `ST_CLUSTER_NAME`, `ST_STORE_BACKEND`, `ST_STORE_ENDPOINTS`) as well for these flags. 

In this way, `stolonctl` within any stolon cluster will refer to that cluster unless the values are overridden. For example, when inside a keeper we could just run `stolon status` to get the status of the cluster. We can even run one `stolonctl` instance per stolon cluster.

Am happy to work and raise a PR for this enhancement.

**Comment by sgotti** [comment]
They are already available: 
https://github.com/sorintlab/stolon/blob/master/doc/commands_invocation.md for all the components and stolonctl. Have you tried them?
