### ISSUE TITLE
Could not init stolon cluster in Azure k8s service

### ISSUE THREAD

**Issue by tumluliu** [sorintlab/stolon#618]
### Submission type

 - Bug report (perhaps)

### Environment

Azure Kubernetes Service with 1.12.5 k8s
client kubectl version: 1.13.4

#### Stolon version

v0.13.0-pg9.6

### Expected behaviour you didn't see

Successfully finishing init the stolon cluster

### Unexpected behaviour you saw

kubectl complained with:
```
cannot get cluster data: failed to get latest version of configmap: Get https://SUBDOMAIN.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/default/configmaps/stolon-cluster-kube-stolon: dial tcp: i/o timeout
```

if running the one-line command
```
kubectl run -i -t stolonctl --image=sorintlab/stolon:v0.13.0-pg9.6 --restart=Never --rm -- /usr/local/bin/stolonctl --cluster-name=kube-stolon --store-backend=kubernetes --kube-resource-kind=configmap init
```

BUT, if I run it with two steps
```
kubectl run -it stolonctl --image=sorintlab/stolon:v0.13.0-pg9.6 --restart=Never -- bash
```
```
root@stolonctl:/# /usr/local/bin/stolonctl --cluster-name=kube-stolon --store-backend=kubernetes --kube-resource-kind=configmap init
WARNING: The databases managed by the keepers will be overwritten depending on the provided cluster spec.
Are you sure you want to continue? [yes/no] yes
root@stolonctl:/#
```
It works fine without that `timeout` error

### Steps to reproduce the problem

1. Create an rbac-enabled AKS
2. Run the steps as in the kubenetes example [readme](https://github.com/sorintlab/stolon/tree/master/examples/kubernetes)

p.s. This issue happens both on rbac-enabled and -disabled AKS

**Comment by tumluliu** [comment]
just tried another way:
1. launch a `stolonctl` container with `kubectl run stolonctl --image=sorintlab/stolon:v0.13.0-pg9.6 --restart=Never`
2. run `kubectl exec stolonctl -- /usr/local/bin/stolonctl init --cluster-name=kube-stolon --store-backend=kubernetes --kube-resource-kind=configmap --yes` --> will fail with
```
cannot get cluster data: failed to get latest version of configmap: Get https://SUBDOMAIN.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/default/configmaps/stolon-cluster-kube-stolon: dial tcp: lookup SUBDOMAIN.hcp.westeurope.azmk8s.io on 10.0.0.10:53: read udp 10.244.1.11:47609->10.0.0.10:53: i/o timeout
command terminated with exit code 1
```

but if run the same command in the container, it can succeed:
```
$ kubectl exec -it stolonctl -- bash
root@stolonctl:/# /usr/local/bin/stolonctl init --cluster-name=kube-stolon --store-backend=kubernetes --kube-resource-kind=configmap --yes
WARNING: The current cluster data will be removed
WARNING: The databases managed by the keepers will be overwritten depending on the provided cluster spec.
root@stolonctl:/#
```
a bit weird to me, could any of you help me to explain the reason behind the scene? many thanks!

**Comment by tumluliu** [comment]
I think I have confirmed that this is an AKS issue, which is not related to stolon actually. 
close it for now. sorry for disturbing..

**Comment by tumluliu** [comment]
As a note for anyone (including myself) encounters the same issue, the root reason in my case is the AKS is using a customized VNET which has already an NSG defined. After changing the subnet's NSG to the one created by the aks deployment (with a name looks like `aks-agentpool-xxx`), everything works fine.

**Comment by linuraj** [comment]
@tumluliu Were you able to figure out a way for making it work in an aks cluster created via cli? We face the same problem with Azure created via terraform too. Really appreciate your help.

**Comment by tumluliu** [comment]
@linuraj We have abandoned the idea of provisioning a dbms within k8s since 2y ago after a lot of nightmare experiences. So I'm sorry that I could not really help here
