### ISSUE TITLE
open files to small

### ISSUE THREAD

**Issue by liuyongqing1** [sorintlab/stolon#626]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

#### Stolon version
v0.13.0-pg9.6

### Enhancement Description

![image](https://user-images.githubusercontent.com/13477384/54732919-80a42580-4bd1-11e9-9f69-a7ab7ab3bded.png)
![image](https://user-images.githubusercontent.com/13477384/54732930-8d287e00-4bd1-11e9-816c-01a97d4818dd.png)

I want to ask this open files is 1024 postgres is this stolon boot. But my max connections is 2000 open files is the number of connections affecting the database

thanks

**Comment by sgotti** [comment]
@liuyongqing1 setting process limits should be done outside stolon based on how you start the stolon keeper (systems, k8s etc...). Then the limits will be inherited by the postgres instance.
