### ISSUE TITLE
Clusterdata too large to store in consul

### ISSUE THREAD

**Issue by jewelzqiu** [sorintlab/stolon#629]
### Submission type

 - Request for enhancement (RFE)

### Environment

two hosts, proxy+keeper+sentinel on each host
store backend: consul

#### Stolon version

v0.13.0-pg10

#### Additional environment information if useful to understand the bug

All stolon services running in docker container.
I am testing stolon by randomly killing some stolon component(s).

### Expected behaviour you didn't see

One keeper failed to restore after `docker restart` command

### Unexpected behaviour you saw

I noticed stolon will store keeper recovery history in clusterdata,  
but on the 3205th recovery process,  
clusterdata size exceeds k/v store value size limit (512KB).  
Then stolon failed to write clusterdata to consul.  

`timelinesHistory` is full of:
```
{
    "timelineID": 1,
    "switchPoint": 301989984,
    "reason": "no recovery target specified"
},
```

### Enhancement Description
I tried to remove `timelinesHistory` entries in clusterdata,  
but it didn't work, looks like `timelineID`s are used elsewhere.  

Are there any methods to clean `timelinesHistory` in clusterdata?

**Comment by sgotti** [comment]
@jewelzqiu Yes, that's an open TODO. We should just keep the last N timelines.

**Comment by jewelzqiu** [comment]
@sgotti For now, can we clean old history records without losing postgres data?
I tried to remove all history entries except the latest one by overwriting clusterdata,
but it seems all history records will come back after failover and keeper reboot.
