### ISSUE TITLE
Add timeout for all calls to store

### ISSUE THREAD

**Issue by dineshba** [sorintlab/stolon#647]
There is **no timeout** for store other than `etcd`? Is there a reason for that? If no specific reason, can we add it?

#### Reason for the requirement of timeout:
We have faced a problem with Kubernetes backend because of not having timeout for GetClusterData method. 

Given
> Every keeper will get the clusterdata (https://github.com/sorintlab/stolon/blob/master/cmd/keeper/cmd/keeper.go#L954) and do some action.

> Every sentinel will also get the clusterdata (https://github.com/sorintlab/stolon/blob/master/cmd/sentinel/cmd/sentinel.go#L1813) and do some action. 

Sometimes, the call from the keeper is getting **hanged**, because of which sentinel decides that keeper is failed and elects the new master.

I would to contribute for the same if the issue is valid. Thanks

**Comment by sgotti** [comment]
@dineshba libkv looks not maintained and it doesn't suppor context.Context. For k8s the k8s go client context support wasn't available at the time of writing it. If it's now possible to pass a context to the k8s go client feel free to implement it.

**Comment by dineshba** [comment]
Will implement and raise the PR soon. Thanks for the inputs @sgotti

**Comment by dineshba** [comment]
Even now `k8s client` **doesn't support** context based timeout. Can we set the timeout for the underlying `restclient.Config`? Like
```
kubecfg.Timeout = cluster.DefaultStoreTimeout
```
at line https://github.com/sorintlab/stolon/blob/master/cmd/common.go#L217

> Note: I was able to create a kubeclient with timeout and it is working fine.
