### ISSUE TITLE
How to add a new standby to cluster?

### ISSUE THREAD

**Issue by mmpei** [sorintlab/stolon#654]
i couldn't find the answer after i checked lots of issues and docs.
i deploy stolon on k8s and how to add a standby to cluster?
add PV and PVC and increase replicas? then exec 'stolonctl init --cluster-name stolon --store-backend kubernetes --kube-resource-kind=configmap' in the new keeper? is that correct?

and another case, if my node down, and something wrong with data in the down node keeper.
how should i do to make cluster work again?

**Comment by arunvelsriram** [comment]
@mmpei did you try this [doc](https://github.com/sorintlab/stolon/blob/master/doc/standbycluster.md)?

**Comment by maksm90** [comment]
@arunvelsriram I think there was meant a standby **node**, not **cluster**

@mmpei 

> how to add a standby to cluster?

You have to run more keepers. First one will be master, others - standbys.

> exec 'stolonctl init --cluster-name stolon --store-backend kubernetes --kube-resource-kind=configmap' in the new keeper

`stolonctl` have to be executed on client side

>  if my node down, and something wrong with data in the down node keeper.
> how should i do to make cluster work again?

The data have to be reserved on another keeper (DB) node (or on remote backup in case of overall disaster).

**Comment by mmpei** [comment]
so i just add a new keeper into cluster if i want to add a new standby?

second case, i mean that,
1. i have a cluster with two keepers, keeper-0 is master and keeper-1 is slave.
2. node0 which keeper-0 is on down, and then keeper-1 promotes to master.
3. then keeper-1 recovers, if something is wrong with the store of keeper-1.  and keeper-1 can't work.
log like,
`2019-05-30T03:36:01.167Z        INFO    cmd/keeper.go:1049      current db UID different than cluster data db UID       {"db": "", "cdDB": "da1a464f"}
2019-05-30T03:32:10.737Z        ERROR   cmd/keeper.go:1346      different local dbUID but init mode is none, this shouldn't happen. Something bad happened to the keeper data. Check that keeper data is on a persistent volume and that the keeper state files weren't removed`
so how to make the cluster work?

**Comment by maksm90** [comment]
> so i just add a new keeper into cluster if i want to add a new standby?

Yes. By the term *standby* I mean a **slave node**.

> is it needed to register a keeper to a stolon cluster?

Surely

>     3\. something is wrong with the store of keeper-1.  and keeper-1 can't work

Are database files in the directory `KEEPER_DATA/postgres` safe? Can you connect to PostgreSQL directly and check the consistency of DB objects?

**Comment by mmpei** [comment]
> 
> 
> > so i just add a new keeper into cluster if i want to add a new standby?
> 
> Yes. By the term _standby_ I mean a **slave node**.
> 
> > is it needed to register a keeper to a stolon cluster?
> 
> Surely
so how to register a keeper to a stolon cluster in stolonctl v12.0?

> 
> > ```
> > 3\. something is wrong with the store of keeper-1.  and keeper-1 can't work
> > ```
> 
> Are database files in the directory `KEEPER_DATA/postgres` safe? Can you connect to PostgreSQL directly and check the consistency of DB objects?
data in keeper-0 is broken. and keeper-1 which promotes to master after keeper-0 down works well.
so how to fix?

**Comment by mmpei** [comment]
refer to
https://github.com/sorintlab/stolon/issues/562
https://github.com/sorintlab/stolon/issues/604
 find the answer. and any way thank you @maksm90
