### ISSUE TITLE
What is the reason why the postgres process is constantly restarting?

### ISSUE THREAD

**Issue by koulq** [sorintlab/stolon#661]
![image](https://user-images.githubusercontent.com/18571340/58882655-51507f80-870f-11e9-98ae-3127035d1e78.png)
![image](https://user-images.githubusercontent.com/18571340/58882707-6d542100-870f-11e9-9f2b-2750e20ed5ec.png)

**Comment by sgotti** [comment]
@koulq Please provide all the needed info in the issue template (with the steps to reproduce the problem). Without such info it's quite impossible to understand what's happening. Will reopen when the info will be provided.
