### ISSUE TITLE
Data persistance is not working in postgres with chart version v0.13.0

### ISSUE THREAD

**Issue by Amithpn** [sorintlab/stolon#671]
### Submission type Bug/Enquiry

 - Bug report

### Environment
Kubernetes

#### Stolon version
stolon-postgres-0.8.0

#### Additional environment information if useful to understand the bug:
We are running the 3 replications of keepers, proxy and sentinels each.

### Expected behaviour you didn't see
We expected data to be retained everytime in the keepers.
### Unexpected behaviour you saw
All the databases and tables created are gone when we restart the pods(helm delete)
### Steps to reproduce the problem
1. Install the postgres cluster using helm charts
2. Add some data to the postgres pointing to stolon-proxy service.
3. Restart the pods using helm delete command

We are using proxy pods to connect to postgres. Let us know what is the issue.

We have downloaded charts from the below URL: https://github.com/sorintlab/stolon/releases
Version: v0.13.0

Im using dockerfile of postgres v10.8 as postgres image

**Comment by sgotti** [comment]
@Amithpn I don't think this issue is related to stolon. Something (helm?) is deleting your persistent volumes or not using them. Please ask to the helm chart creators.
