### ISSUE TITLE
could not close file "base/194007/204823.1": Input/output error

### ISSUE THREAD

**Issue by Frank111** [sorintlab/stolon#672]
Hi ,My K8S-stolon-keeper service often fails, stolon-data is stored in nfs.
`2019-06-12 05:10:33.314 UTC [12564] PANIC:  could not close file "base/194007/204823.1": Input/output error

and

2019-06-12T05:12:29.170Z	ERROR	cmd/keeper.go:1624	failed to save db local state	{"error": "sync /stolon-data/dbstate689049274: input/output error"}
`

**Comment by sgotti** [comment]
@Frank111 That's an io error reported both by postgres and stolon so it's not a stolon issue. You should investigate your storage infrastructure (in your case look at nfs errors both on client and server side).
