### ISSUE TITLE
Question of  'check timeout timer fired'

### ISSUE THREAD

**Issue by illmatik12** [sorintlab/stolon#674]
In my cluster doing some fail test. ( some case of 'check timeout timer fired' ) 
I start stolon-proxy with "--stop-listening=false " 
and I confirmed log message without 'Stopping listening'.
but current connection(db session) is disconnected. 
Is that right operation? 

## Environment
3node stolon cluster
### etcd --version
etcd Version: 3.3.9
Git SHA: fca8add78
Go Version: go1.10.3
Go OS/Arch: linux/amd64
### stolon-proxy --version
stolon-proxy version v0.12.0

### cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
-bash-4.2$

**Comment by sgotti** [comment]
Closing since this is an old issue and the question is not really clear.
