### ISSUE TITLE
Full KV-storage 

### ISSUE THREAD

**Issue by skilyazhnev** [sorintlab/stolon#686]
### Submission type

 - Bug report

### Environment

Oracle Linux Server release 7.6

#### Stolon version

version v0.13.0
over consul 1.4 

stolon filled KV-storage, which led to the inability to switch the master node.
returns error Unexpected response code: 413 (Value exceeds 524288 byte limit) "}
at the same time, KV-storage remains clogged even when it is reinitialized.

the position of the master did not change, but the keeper's KV-storage was filled with values

{
         "timelineID": 3013,
         "switchPoint": 185639909024,
         "reason": "no recovery target specified"
 }

**Comment by sgotti** [comment]
@skilyazhnev This has already been fixed in current master. Or you can wait for next v0.14.0 release.
