### ISSUE TITLE
A sidecar container run in keeper pod, proxy cannot access

### ISSUE THREAD

**Issue by aixeshunter** [sorintlab/stolon#687]
### Submission type

Hi, I runned a sidecar container named `pg-agent` in `keeper` pod, and I want to access this `pg-agent` container by `proxy`, does `proxy` support this situation?

**Comment by sgotti** [comment]
@aixeshunter such questions should be asked on the stolon gitter channel: https://github.com/sorintlab/stolon#contacts. And please provide more details on what you're trying to achieve.
