### ISSUE TITLE
Reading and writing separation

### ISSUE THREAD

**Issue by 3tem** [sorintlab/stolon#703]
the stolon of  support reading and writing separation?
and  proxy can distinguish between read and write operations?

**Comment by sgotti** [comment]
@3tem such questions should be asked in the gitter channel.

Stolon is for postgres high availability. Please see the FAQ https://github.com/sorintlab/stolon/blob/master/doc/faq.md#does-the-stolon-proxy-sends-read-only-requests-to-standbys and this issue comment https://github.com/sorintlab/stolon/issues/132#issuecomment-396870211

**Comment by 3tem** [comment]
thanks

**Comment by 3tem** [comment]
thanks
