### ISSUE TITLE
default podManagementPolicy prevents cluster from recovering

### ISSUE THREAD

**Issue by drdivano** [sorintlab/stolon#705]
### Submission type

 - Bug report

### Environment

Kubernetes 1.14

#### Stolon version

N/A

#### Additional environment information if useful to understand the bug

Stolon Keeper is set up with local PersistentVolumes (plain disks, no network attached storage)

1. Create Kubernetes cluster containing 2 nodes
2. Create Stolon cluster using StatefulSet with 2 replicas: keeper-0, keeper-1. Make sure the replicas start on different nodes (using local PersistentVolumes with node affinity)
3. Shutdown the whole cluster
4. Start the node containing keeper-1 (while keeping keeper-0 down)
5. StatefulSet refuses to start keeper-1 since the node with keeper-0 with is down (due to default podManagementPolicy: OrderedReady

After deleting and recreating the StatefulSet with podManagementPolicy: Parallel, the replica keeper-1 starts normally and gets promoted to master.

Should the "Parallel" policy be the default? Are there any gotchas?

**Comment by sgotti** [comment]
@drdivano Are you referring to the k8s example? If so then it's just an example and that policy wasn't available when it was created.

Are you using node local volumes? If you're using classic PV that can be mounted on every node than keeper-0 should be scheduled on another node.

Anyway it's not a stolon bug.

**Comment by drdivano** [comment]
Yes, I realise it's not a bug in stolon itself. Your reply explains the reason why the example is configured this way, that's what I wanted to find out.

If stolon doesn't care about the order in which replicas start, maybe it would make sense to add t "podManagementPolicy: Parallel" to the example.

Anyway, we love stolon, and appreciate your work, thanks!

**Comment by sgotti** [comment]
> If stolon doesn't care about the order in which replicas start, maybe it would make sense to add t "podManagementPolicy: Parallel" to the example.

Yeah, would you like to open a Pull Request?


> Anyway, we love stolon, and appreciate your work, thanks!

Thanks!
