### ISSUE TITLE
stolonctl: don't show null cluster spec options

### ISSUE THREAD

**Issue by viggy28** [sorintlab/stolon#723]
### Submission type

 - Bug report

#### Stolon version
v0.13.0 (and the recent commit too)

Unable to remove these parameters `additionalWalSenders`, `additionalMasterReplicationSlots` & `automaticPgRestart` from cluster spec.

### Expected behaviour you didn't see
As per https://github.com/sorintlab/stolon/blob/master/doc/cluster_spec.md, patching cluster spec with null should remove the parameter whereas it didn't happen

### Steps to reproduce the problem
Cluster spec already has default value of 	
"additionalWalSenders": null, "additionalMasterReplicationSlots": null, and "automaticPgRestart": null. 

stolonctl --cluster-name stolon-cluster --store-backend=etcdv3 update --patch '{"automaticPgRestart":null}' doesn't do anything.

It's likely that https://github.com/sorintlab/stolon/blob/14bc5473237ee3a9a361d83967926940a934077b/internal/cluster/cluster.go#L290 `omitempty` is not mentioned in the JSON tag.

**Comment by sgotti** [comment]
@viggy28 I think that what's confusing is that they are printed as null during a `stolonctl spec`. They were really removed (so I'm going to change your title) and there's no bug or issue on this side.

`omitempty` will avoid showing them as null when marshalled to json and print.

**Comment by sgotti** [comment]
Fixed by #736
