### ISSUE TITLE
Is there a way to update max_connections PgParameters after stolon runs?

### ISSUE THREAD

**Issue by duyanghao** [sorintlab/stolon#725]
Request for enhancement (RFE)

### Environment

Stolon version: 0.7.0

### Enhancement Description

Now we can only set `max_connections` when stolon starts. Is there a way to update this PgParameters during stolon run-time? After all, this is a common action on production environments.

**Comment by viggy28** [comment]
Try to upgrade your version.
Also, have you looked at this https://github.com/sorintlab/stolon/blob/master/doc/cluster_spec.md#set-some-postgres-parameters

This works for me `stolonctl --cluster-name stolon-cluster --store-backend=etcdv3 update --patch '{ "pgParameters" : {"max_connections" : "222" } }'`

**Comment by Forsure-Wang** [comment]
**Agree with @viggy28 ,but this change requires restart，so this is what I do**

`stolonctl --cluster-name=kube-stolon --store-backend=kubernetes --kube-resource-kind=configmap update --patch '{ "automaticPgRestart" : true }'`

`stolonctl --cluster-name=kube-stolon --store-backend=kubernetes --kube-resource-kind=configmap update --patch '{"pgParameters":{"max_connections":"300"}}'`

**By the way,you can do like this when init stolon cluster**

`stolonctl --cluster-name=kube-stolon --store-backend=kubernetes --kube-resource-kind=configmap init '{ "initMode": "new","pgParameters":{"max_connections":"300"} }'`

**Comment by sgotti** [comment]
@duyanghao Closing since already answered. Next time please ask on the gitter channel: https://github.com/sorintlab/stolon#contacts
