### ISSUE TITLE
SleepInterval not respected by proxy

### ISSUE THREAD

**Issue by dineshba** [sorintlab/stolon#729]
Currently, `sleepInterval` is respected by `keeper` and `sentinel`. It is not there for proxy. @sgotti Correct me if I am wrong. Can we add it proxy ?

**Comment by sgotti** [comment]
@dineshba Proxy main purpose is to close connections in a specified timeout that must work with the the sentinels ("self fence") so it currently has hardcoded timeouts. Changing them will require a lot of work and checks to verify that everything doesn't break and connections are always closed in the right timeout to avoid connections going to old primaries.

**Comment by sgotti** [comment]
@dineshba Have I answered your question? If you have the need to be able to change these parameters feel free to open a PR with various test cases to ensure that nothing will break.

**Comment by sgotti** [comment]
Implemented in #756 . Proxy doesn't use `sleepInterval` but `proxyCheckInterval`.
