### ISSUE TITLE
Failed to get latest version of configmap in k8s

### ISSUE THREAD

**Issue by ccmehk** [sorintlab/stolon#742]
### Submission type

 - Bug report

### Environment
k8s 1.16.3

#### Stolon version
v1.15.0

### Expected behaviour you didn't see
i have 2 nodes for stolon in k8s. I started to try to failover from one node to the other node. The proxy start repeat with the following logs.

        INFO    cmd/proxy.go:303        check function error    {"error": "cannot get cluster data: failed to get latest version of configmap: Get https://10.96.0.1:443/api/v1/namespaces/dt-prod/configmaps/stolon-cluster-mt-stolon: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}

I wonder why it cannot get the latest version of configmap.

### Unexpected behaviour you saw
It can fetch the latest version of configmap

### Steps to reproduce the problem
1. start stolon with two nodes
2. remove the master of stolon

**Comment by sgotti** [comment]
@ccmehk 

The error 
```
{"error": "cannot get cluster data: failed to get latest version of configmap: Get https://10.96.0.1:443/api/v1/namespaces/dt-prod/configmaps/stolon-cluster-mt-stolon: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

says that you're using the k8s store but the api isn't responding in time (timeout). So you should try to understand why your k8s api are so slow (machine overloaded, not enough ram etc...). We cannot do anything here.


Please discuss such support requests on gitter: https://github.com/sorintlab/stolon#contacts
