### ISSUE TITLE
Query result of pg_is_in_recovery is wrong

### ISSUE THREAD

**Issue by shangjin92** [sorintlab/stolon#745]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### Environment
stolon on kubernetes
#### Stolon version
v0.15.0
### Expected behaviour you didn't see
Execute _select pg_is_in_recovery()_ on standby instance, the result should be t.

### Unexpected behaviour you saw
While execute _select pg_is_in_recovery()_  on all instance, all the result is f.
![image](https://user-images.githubusercontent.com/7251928/71139274-afc2f280-2248-11ea-91f2-0f4608faf183.png)

### Steps to reproduce the problem
Default setup.

**Comment by sgotti** [comment]
@shangjin92 you are connecting to the stolon proxy service endpoints so in every attempt you're connecting to one of the stolon proxies and they'll always connect to the primary instance.

For any support question (like explained in the issue template) please use the gitter channel: https://github.com/sorintlab/stolon#contacts
