### ISSUE TITLE
RFE document syncTimeout

### ISSUE THREAD

**Issue by johannesboon** [sorintlab/stolon#748]
As multiple users have experienced the hard way, the default timeout is currently an undocumented arbitrary number of minutes that can easily become a problem if you need to recover from a full backup a day ago and need to replay a large number of transactions.

Out of scope: A nicer solution might be to monitor the progress of the recovery, but I'm not sure how to implement that. Yet another option may be to remove the timeout entirely.

For now the least I can do is try and improve the user experience by improving the documentation as suggested previously:

@johannesboon Feel free to open an RFE issue to request this to be documented and also a PR to add this to the doc.

_Originally posted by @sgotti in https://github.com/sorintlab/stolon/issues/685#issuecomment-563191033_

**Comment by sgotti** [comment]
@johannesboon 

> As multiple users have experienced the hard way, the default timeout is currently an undocumented arbitrary number of minutes that can easily become a problem if you need to recover from a full backup a day ago and need to replay a large number of transactions.

The best idea would be to set the default as no timeout and document it so user could set it to a preferred value. I saw you created #749, can you update it?

**Comment by johannesboon** [comment]
@sgotti 
> The best idea would be to set the default as no timeout and document it so user could set it to a preferred value. I saw you created #749, can you update it?

That sounds interesting but isn't trivial to implement as the code is now completely build around Durations and I'm no Golang developer. I could trivially increase the default duration to something like a year if that suits most practical needs?

**Comment by sgotti** [comment]
@johannesboon I created PR #752 to make it defaults to 0 (infinite). Can you please update your PR #749 to add the related documentation (removing any code change)?

**Comment by sgotti** [comment]
Fixed by #749
