### ISSUE TITLE
[ Question ] Rolling upgrade, how short downtime can be? How to implement?

### ISSUE THREAD

**Issue by Samusername** [sorintlab/stolon#757]
I saw old discussion, regarding same kind of a topic:
https://github.com/sorintlab/stolon/issues/255  ( It refers also to: https://github.com/sorintlab/stolon/issues/88 .)
It is a little be unclear to me.

I am trying to check downtimes regarding Stolon, in rolling upgrades, from client point of view.

How short downtime can be achieved in rolling upgrade? Tens of seconds? Ten seconds? Less?
My setup: Master - sync replica - async replica. I install stolon with helm.

How should the rolling upgrade be implemented with Stolon?

**Comment by sgotti** [comment]
@Samusername for such kind of support question please use the gitter channel https://github.com/sorintlab/stolon#contacts

Anyway I can't understand your question.

> I am trying to check downtimes regarding Stolon, in rolling upgrades

What do you mean by rolling upgrades? Stolon doesn't do rolling upgrades. 

> from client point of view.

What is the client point of view? The client connects to the stolon-proxy and should handle errors and reconnect like every postgres client with or without stolon.

**Comment by Samusername** [comment]
Thanks for the hint about the discussion channel!
Continuing there.
When helm upgrade is executed, a rolling upgrade will be triggered.

**Comment by sgotti** [comment]
@Samusername that's k8s deployment/statefulset pods rolling upgrade not postgres upgrade. It's outside stolon control but it's just one of the many  ways to deploy stolon (and we aren't the helm chart maintainers).
