### ISSUE TITLE
build containers for arm architectures

### ISSUE THREAD

**Issue by Josua-SR** [sorintlab/stolon#761]
### Submission type

 - Request for enhancement (RFE)

### Expected behaviour you didn't see

- images on dockerhub built for armv7/aarch64v8
- Dockerfile for building my own arm container

### Steps to reproduce the problem

- Pull sorintlab/stolon from dockerhub
- Run stolon on an ARM device

### Enhancement Description

Please build binaries, and docker images for the most common (and powerful) arm platforms armv7a and aarch64v8.
I really liked using stolon on kubernetes, but I am running a mixed architecture cluster with most nodes being of the arm architectures. Therefore I'd really like the ability for scheduling stolon transparently on any of those.

**Comment by Josua-SR** [comment]
If you need any help doing this, and want so share e.g. the Dockerfile, or any relevant CI pieces you're using, feel free to get in touch!

**Comment by sgotti** [comment]
@Josua-SR The provided images as explained in the doc are **EXAMPLE** images since we don't want to support all possible updates, security fixes, requests to add additional extensions, backup tools etc... Just build your own images.

**Comment by Josua-SR** [comment]
Imo Even examples benefit from functioning on more than one architecture. However I get your point and will be doing so.

**Comment by unixfox** [comment]
If need I've an automatic build of stolon postgresql 10 for AMD64, ARM64 and ARMv7: https://quay.io/repository/unixfox/stolon
