### ISSUE TITLE
metrics exposes only golang metrics

### ISSUE THREAD

**Issue by emrahcetiner** [sorintlab/stolon#768]
**What happened**:
:8080/metrics endpoint exposes only golang metrics.

**What you expected to happen**:
any of stolon metrics (eg. "stolon_sentinel_is_leader") result should be exposed

**Environment**:
- Stolon version: v0.16.0
- Others:

**Comment by sgotti** [comment]
@emrahcetiner We already provide additional metrics, see: #639 #656.
