### ISSUE TITLE
Getting "Cannot get configured pg parameters" error while running stolon keeper

### ISSUE THREAD

**Issue by Raghavsalotra** [sorintlab/stolon#770]
I am trying to create pg cluster using stolon.
Spec:
OS: Ubuntu 18.04
etcd: V3

Before running keeper i have issued commands for initdb and started sentinel as stated in documentation.

Below is the error we are getting:

`ERROR	cmd/keeper.go:673	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}`

Below is the command i ran:
`./bin/stolon-keeper --cluster-name stolon-cluster --store-backend=etcdv3 --uid postgres0 --data-dir data/postgres0 --pg-su-password=admin@123 --pg-repl-username=replication1 --pg-repl-password=admin@123 --pg-listen-address=127.0.0.1`

Can anyone help here if i am missing something.

Thanks in advance.

**Comment by sgotti** [comment]
@Raghavsalotra I suppose you also wrote here: https://talk.stolon.io/t/db-failed-to-initialize-or-resync/35/2 

Closing.

**Comment by gormed** [comment]
Just leaving it here if anyone gets the error when running stolon on MacOs, MacBook M1/M2: Make sure you enable Rosetta in your Docker Desktop client.
