### ISSUE TITLE
Add support for SCRAM-SHA-256 authentication

### ISSUE THREAD

**Issue by Sourav1407** [sorintlab/stolon#775]
Getting the below error 

**unknown authentication response: 10** 

when application is trying to connect to the DB server via pgbouncer

**Comment by sgotti** [comment]
@Sourav1407 You have ignored the required issues templates and probably you should first read this https://www.postgresql.org/docs/12/auth-password.html that will explain how it works in postgres.

For support questions please use the Stolon Users Forum: https://github.com/sorintlab/stolon#contacts

Instead if you think that something should be implemented you should propose an enhancement following the right template or just create a PR with the proposed implementation.

**Comment by Sourav1407** [comment]
I know how SCRAM-SHA-256 works in postgres. we have taken care of the same. Non-HA postgres is working fine with SHA 256 encrption but HA postgres which is implemented with Stolon is failing and in the Stolon architecture (link mentioned below) it is clearly quotes in its postgreSQL user section that
"Currently trust (password-less) and md5 password based authentication are supported. In the future, different authentication mechanisms will be added."  
https://github.com/sorintlab/stolon/blob/master/doc/architecture.md

Will create a PR
