### ISSUE TITLE
Confusing stolon keeper update/error

### ISSUE THREAD

**Issue by izelnakri** [sorintlab/stolon#778]
Hi there,

This might seem like an insufficient/basic issue however is a big problem for developer/debugging experience, caused me few hours of confusion. I automated my stolon deployments with kustomize and when I deploy my templates to digitalocean everything works perfectly. Recently I've been experimenting with scaleaway and I get this error "after initializing the cluster". I've read the source code and the line that causes it.

The error message itself isnt descriptive, have no idea whats going on, it could be RBAC/Role related error but the error trace cant tell me anything below concretely. Is there a way to see these errors in a more clear way?

`kubectl logs stolon-keeper-0 --namespace stolon` ->

```
2020-04-08T21:50:03.612Z        ERROR   cmd/keeper.go:778       failed to update keeper info    {"error": "update failed: failed to get latest version of pod: v1.Pod.ObjectMeta: v1.ObjectMeta.readObjectFieldAsBytes: expect : after object field, but found u, error found in #10 byte of ...|:{},\"k:{\\\"uid\\\":\\\"5f|..., bigger context ...|on-cluster\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"5f3d60cf-ae09-45ee-8bf8-cf971ef43a15\\\"}\":{|..."}
```

Also digitalocean k8s cluster runs on v1.16.6 meanwhile scaleway runs on v1.18, This could be a kubernetes store/etcd/label  yaml parsing error due to a breaking change but Im not sure.

**Comment by izelnakri** [comment]
Hi @sgotti,

I've investigated the issue further and had a discovery, latest stolon on helm(stable/stolon) is incompatible with the latest kubernetes(1.18.x). When I use kubernetes 1.16x just like digitalocean stolon works. So at this point Im 100% sure that the latest helm chart on stable/stolon is not compatible with Kubernetes 1.18.1 and I get the error mentioned above. Probably a YAML parsing bug on stolon.

**Comment by sgotti** [comment]
@izelnakri stolon work correctly on a "standard" k8s cluster (like minikube). So you should investigate what's different on scaleway k8s clusters.

**Comment by izelnakri** [comment]
@sgotti it worked on scaleway k8s 1.16.x, didnt work on scaleway k8s 1.18.x. Im checking now deeper what the issue is..

**Comment by izelnakri** [comment]
last updates:
- helm stable chart is running on stolon v0.13. This makes debugging particularly difficult for me, Im sure at this point this is a bug on v0.13, but might be fixed since then. We should provide a standard helm chart that traces the latest stolon version. Since helm 3 we no longer need to manually create a PR to offical stable helm charts, it is possible to provide a custom helm repo, most high traction projects started to offer their own helm repos, it is probably possible to host it in this repo as well. We should look into this. For example: ```helm repo add jaegertracing https://jaegertracing.github.io/helm-charts``` 
- Helm chart also worked on scaleway k8s v1.17.x in addition to v1.16.x, it just doesnt work on the latest v1.18.x, could still be existing. I'll see if I can run this on the latest stolon.

**Comment by izelnakri** [comment]
I updated the chart images to ```sorintlab/stolon:v0.16.0-pg12```, everything is working now on scaleway k8s v1.18.x!

Im closing this issue now, we should have a helm chart that is in-sync with this project. Thanks for your interest and stolon project @sgotti .
