### ISSUE TITLE
postgresql backup and restore chart using pg_dumpall/psql/other 

### ISSUE THREAD

**Issue by sunilvancha** [sorintlab/stolon#782]
**What would you like to be added**:

I am trying to automate postgresql backup and restoration. Do you have any feature in this chart to take backup and restore automatically when the chart is deployed? if not do you have separate chart available for the backup and restoration?

kubernetes cluster.

**Why is this needed**:

Automatation for postgres db backups/restore

**Comment by sunilvancha** [comment]
I have created automation job for backup and restoration. Hene closing this issue

**Comment by shishirkh** [comment]
Can you share? @sunilvancha

**Comment by princewadhwa** [comment]
@sunilvancha  Can you please share that automation job of backup and restore?
