### ISSUE TITLE
Stolon generates unsupported wal_keep_segments settings

### ISSUE THREAD

**Issue by pyhalov** [sorintlab/stolon#803]
**What happened**:
When run with PostgreSQL 13, Stolon can't init cluster as it generates config with `wal_keep_segment`  parameters, but it was dropped, `wal_keep_size` should be used instead.

**What you expected to happen**:
Stolon should detect necessary setting, for example, based on PostgreSQL version, or trying to invoke postgres with specified parameters.

**Comment by sgotti** [comment]
Created Posgres13 support issue #807. Pull Requests are welcome!
