### ISSUE TITLE
check timeout timer fired

### ISSUE THREAD

**Issue by mmpei** [sorintlab/stolon#818]
v0.12.0

log is from stolon-proxy. 
![图片](https://user-images.githubusercontent.com/30788120/104895083-65aec200-59b0-11eb-93b5-a63ec26facb9.png)

i checked the source code, and found that it will assign the destAddress to a channel after the log 'proxying to master address xxxx'. this could nerver suspend the process.
so what's causing it to run out of time?

**Comment by sgotti** [comment]
@mmpei If you want to open a bug report please fill the template provided when you open a new issue, if this is a question please ask it in the [stolon forum](https://talk.stolon.io/): https://github.com/sorintlab/stolon#contacts

**Comment by mmpei** [comment]
OK move to talk.stolon.

**Comment by mmpei** [comment]
it's caused by resource limit of Kubernetes.(acturally CPU limit in our case).
but network unstable, api-server timeout or something like that will bring the stolon-proxy timeout and break the connection of clients, this will make a `broken pipe` error sometimes.
