### ISSUE TITLE
Bus error (core dumped) with hugepage in k8s.

### ISSUE THREAD

**Issue by 271560sj** [sorintlab/stolon#824]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Stolon version:
- Stolon running environment (if useful to understand the bug):
- Others:

**Comment by sgotti** [comment]
@271560sj Please use the provided issue template. Though I can't understand how this could be a stolon issue.
