### ISSUE TITLE
stolonctl: implement postgres reload/restart

### ISSUE THREAD

**Issue by sgotti** [sorintlab/stolon#88]

**Comment by sgotti** [comment]
Closing since it's old and without any context.

**Comment by prabhu43** [comment]
Hi @sgotti 

We need this feature of postgres restart to take effect of updated pgParameters like `max_connections`. 

I went through this issue (#255) and got an idea of restarting the postgres instance of slave keepers first and then restarting the postgres instance of master. On restarting the postgres of master, sentinal will elect another healthy keeper as master

We thought of implementing this feature as follows:

1. Introduce a flag `PgRestart` in keeper status in cluster data
2. Keepers: If Status.PgRestart is true, 
      - Set Status.PgRestart is false,
      - Set keeper status as unhealthy(Status.healthy as false)
      - Restart postgres instance
      - Set keeper status as healthy(Status.healthy as true)
3. On executing `stolonctl pgRestart`:
	- Update Cluster Data: Set `Status.PgRestart: true` for slave keepers
	-  If atleast one slave is restarted and healthy, Update Cluster Data: Set `Status.PgRestart: true` for master keeper 

What do you think?

**Comment by sgotti** [comment]
@prabhu43 I reopened the issue (it was closed and I was losing your comment).

Your proposal is basically an **operator** that handles a long running transaction. It requires a lot of logic to handle all the possible failures (it implements one of the possible workflows but there can be others). And as you said there're different gotchas that are difficult to know ahead of time since you should reimplement all the postgresql parameter checking logic.

For this reason I won't add a command like `stolonctl pgrestart` that will be a blocking command carrying all of this logic.
Perhaps this could be implemented (in go or as shell script or whatever) as a contrib script/tool outside stolonctl.

## Some notes

* ideally a keeper can automatically discover (and report) if an instance needs a restart querying the pg_parameters table. It's simply not yet implemented.

> On restarting the postgres of master, sentinal will elect another healthy keeper as master

To be precise, restarting the master keeper doesn't imply that a new primary will be elected, if the restart is fast enough (usually) and doesn't fail due to wrong parameters the sentinel won't detect the master as failed and won't elect a new master.

**Comment by aswinkarthik** [comment]
> if the restart is fast enough (usually) and doesn't fail due to wrong parameters the sentinel won't detect the master as failed and won't elect a new master.

@prabhu43 and myself tried exactly this in this PR #561 

We just blindy restart all 3 postgres and tested it out. It restarted very fast with very minimal downtime (lesser than 1 second).
