### ISSUE TITLE
Multiple vulnerabilities found in [Stolon:master-pg14] during JFrog scan.

### ISSUE THREAD

**Issue by HimanshuPanwarSF** [sorintlab/stolon#885]
**What happened**: Hi, we've faced several security issues when scanning the Stolon (master-pg14) with JFrog X-Ray. There were **27 critical** security issues, the rest were high, medium and low.

**What you expected to happen**: Expected was minimal security issues while the JFrog scan.

**How to reproduce it (as minimally and precisely as possible)**: Just scanning Stolon:master-pg14 with JFrog Xray.

**Anything else we need to know?**: We request you to fix the issues as we have to move our project to the production stage.

**Environment**:
- Stolon version: master-pg14
- Stolon running environment (if useful to understand the bug): Kubernetes
- Others: 
- ScreenShot:
![image](https://user-images.githubusercontent.com/83944925/186094266-aff6c2bc-724d-4778-a212-b13e2b6ef282.png)
- JFrog Report:
[Stolon_master-pg14_Security_Export.csv](https://github.com/sorintlab/stolon/files/9400191/Stolon_master-pg14_Security_Export.csv)

**Comment by sgotti** [comment]
@HimanshuPanwarSF As stated in the documentation the image is just an example image built after a release since we don't have time to also maintain all possible images. Just build your preferred images.
