### ISSUE TITLE
Update the example of kubernetes and question about helm chart.

### ISSUE THREAD

**Issue by ghiyastfarisi** [sorintlab/stolon#889]
**What would you like to be added**:
Need update the yaml manifest for rolebinding.yaml and role.yaml within `/examples/kubernetes/` directory. 

Current apiVersion:
`apiVersion: rbac.authorization.k8s.io/v1beta1`

update to:
`apiVersion: rbac.authorization.k8s.io/v1`

**Why is this needed**:
Kubernetes already drop the support for v1beta1 apiVersion for rolebinding and role, at version 1.22+
source https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122

Is there any further plan to create helm chart for more simplified kube deployment version ?

**Comment by sgotti** [comment]
> Need update the yaml manifest for rolebinding.yaml and role.yaml within `/examples/kubernetes/` directory.

Please open a PR.

> Is there any further plan to create helm chart for more simplified kube deployment version ?

There should already be stolon helm charts in official helm repositories. We don't want to support all the possible deploy methods but just provide some examples.

**Comment by ghiyastfarisi** [comment]
link to the [PR](https://github.com/sorintlab/stolon/pull/894)
