### ISSUE TITLE
Why PSQL version is 10 at the helm chart?

### ISSUE THREAD

**Issue by emoxam** [sorintlab/stolon#893]
I used helm chart
helm repo add iomedstolon [Stolon Helm Chart | helm_stolon](https://iomedhealth.github.io/helm_stolon/)
and i reilized that PSQL version is 10. Why is so old ?
Thanks

**Comment by sgotti** [comment]
@emoxam That helm chart is not maintained by this project. You should ask to the chart maintainers.

**Comment by emoxam** [comment]
> @emoxam That helm chart is not maintained by this project. You should ask to the chart maintainers.

why not to make one?

**Comment by sgotti** [comment]
@emoxam This is the project for the stolon software. We just provide example images (not production image) and some examples.
It's impossible to maintain all the combinations of images, deployment modes etc... You're free to create your own images and helm charts, publish and maintain them.
