### ISSUE TITLE
stolonctl run inide kubernetes pod

### ISSUE THREAD

**Issue by Lxml-q** [sorintlab/stolon#898]
root@stolon-keeper-0:/# stolonctl status --cluster-name=pg1 --store-backend=kubernetes
unspecified kubernetes resource kind

stolonctl run inside a pod, but it terminated with exit code 1: unspecified kubernetes resource kind

**Comment by Vsevosemnog** [comment]
I do it for myself, bc i always forget the solution
One should add --kube-resource-kind=configmap (or another resource kind)

stolonctl status --cluster-name=stolon --store-backend=kubernetes --kube-resource-kind=configmap
